"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useLanguage } from "../Common/LanguageContext";
import { languages } from "../../lib/language";
const FLAGS:{key:keyof typeof languages;name:string;src:string}[]=[
 {key:"RU",name:"Русский",src:"/images/flags/ru.svg"},{key:"UA",name:"Українська",src:"/images/flags/ua.svg"},{key:"EN",name:"English",src:"/images/flags/en.svg"},{key:"PL",name:"Polski",src:"/images/flags/pl.svg"}
];
type Notice={id:string;title:string;body:string;createdAt:string;status:string};
export default function Header(){
 const{language,setLanguage,t}=useLanguage();
 const[user,setUser]=useState<{id:string;nickname:string;balance:string;role?:string;avatarUrl?:string|null;steamAvatarUrl?:string|null}|null>(null);
 const[langOpen,setLangOpen]=useState(false); const[menuOpen,setMenuOpen]=useState(false); const[profileOpen,setProfileOpen]=useState(false); const[noticeOpen,setNoticeOpen]=useState(false); const[notices,setNotices]=useState<Notice[]>([]); const[unread,setUnread]=useState(0);
 async function loadUser(){try{const r=await fetch("/api/auth/me",{cache:"no-store"});const d=await r.json();setUser(d.user??null);if(d.user){const n=await fetch("/api/notifications",{cache:"no-store"});const nd=await n.json();setNotices(nd.notifications??[]);setUnread(Number(nd.unread||0));}}catch{}}
 useEffect(()=>{loadUser();const timer=setInterval(loadUser,20000);return()=>clearInterval(timer)},[]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setUser(null);window.location.href="/"}
 async function markNotice(id:string){await fetch("/api/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});setNotices(v=>v.map(n=>n.id===id?{...n,status:"READ"}:n));setUnread(v=>Math.max(0,v-1));}
 async function markAll(){await fetch("/api/notifications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true})});setNotices(v=>v.map(n=>({...n,status:"READ"})));setUnread(0)}
 const current=FLAGS.find(x=>x.key===language)||FLAGS[0]; const navClass="cursor-pointer rounded-lg px-2 py-1 text-sm text-zinc-400 transition hover:bg-[var(--theme-accent-bg)] hover:text-[var(--theme-accent)] active:scale-95";
 const links=<><Link className={navClass} href="/" onClick={()=>setMenuOpen(false)}>{t.home}</Link><Link className={navClass} href="/matches" onClick={()=>setMenuOpen(false)}>{t.matches}</Link><Link className={navClass} href="/live" onClick={()=>setMenuOpen(false)}><span className="inline-flex items-center gap-2"><span className="site-live-dot"/>{t.live}</span></Link><Link className={navClass} href="/rating" onClick={()=>setMenuOpen(false)}>{t.rating}</Link><Link className={navClass} href="/profile" onClick={()=>setMenuOpen(false)}>{t.profile}</Link></>;
 const avatar=user?.avatarUrl||user?.steamAvatarUrl;
 return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#050507]/80 backdrop-blur-xl">
  <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6">
   <div className="flex items-center gap-2"><button className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-white/5 text-zinc-300 md:hidden" aria-label="Menu" onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?"×":"☰"}</button><Link href="/" className="flex items-center gap-2 font-black tracking-tight transition hover:opacity-90"><img src="/branding/duelplay-wolf.png" alt="DuelPlay" className="h-11 w-11 rounded-xl object-cover"/><span className="hidden text-xl tracking-[-.03em] sm:block">DUEL<span className="text-[var(--theme-accent)]">PLAY</span></span></Link></div>
   <nav className="hidden items-center gap-3 text-sm md:flex">{links}</nav>
   <div className="flex items-center gap-2">
    <div className="relative"><button type="button" aria-label="Language" onClick={()=>setLangOpen(v=>!v)} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/5 p-2 hover:border-[var(--theme-accent)]/30"><img src={current.src} alt={current.name} className="h-6 w-8 rounded object-cover"/></button>{langOpen&&<><button type="button" className="fixed inset-0 z-10 cursor-default" aria-label="Close languages" onClick={()=>setLangOpen(false)}/><div className="absolute right-0 top-12 z-20 w-44 rounded-2xl border border-white/10 bg-[#0b0b10] p-2 shadow-2xl">{FLAGS.map(x=><button key={x.key} type="button" onClick={()=>{setLanguage(x.key);setLangOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left text-sm hover:bg-white/5 ${language===x.key?"bg-[var(--theme-accent-bg)] text-[var(--theme-accent)]":"text-zinc-300"}`}><img src={x.src} alt={x.name} className="h-6 w-9 rounded object-cover"/><span>{x.name}</span></button>)}</div></>}</div>
    {user?<>
      <div className="relative"><button type="button" aria-label="Notifications" onClick={()=>setNoticeOpen(v=>!v)} className="relative grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/5 text-lg hover:border-[var(--theme-accent)]/40" ><svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4" strokeLinecap="round" strokeLinejoin="round"/></svg>{unread>0&&<span className="absolute right-1 top-1 grid h-4 min-w-4 place-items-center rounded-full bg-[var(--theme-accent)] px-1 text-[9px] font-black text-black">{unread>9?"9+":unread}</span>}</button>{noticeOpen&&<><button className="fixed inset-0 z-10" onClick={()=>setNoticeOpen(false)} aria-label="Close notifications"/><div className="absolute right-0 top-12 z-20 w-[360px] max-w-[calc(100vw-2rem)] rounded-2xl border border-white/10 bg-[#0b0b10] p-3 shadow-2xl"><div className="flex items-center justify-between px-2 py-1"><b>Уведомления</b><button onClick={markAll} className="text-xs text-[var(--theme-accent)]">Прочитать всё</button></div><div className="mt-2 max-h-96 space-y-2 overflow-auto">{notices.length?notices.map(n=><button key={n.id} onClick={()=>markNotice(n.id)} className={`block w-full rounded-xl border p-3 text-left transition hover:border-[var(--theme-accent)]/30 ${n.status==="UNREAD"?"border-[var(--theme-accent)]/20 bg-[var(--theme-accent-bg)]":"border-white/5 bg-white/[.02]"}`}><div className="flex items-start gap-2"><span className="mt-0.5 text-[var(--theme-accent)]">●</span><span><b className="text-sm">{n.title}</b><span className="mt-1 block text-xs leading-5 text-zinc-400">{n.body}</span><span className="mt-1 block text-[10px] text-zinc-600">{new Date(n.createdAt).toLocaleString()}</span></span></div></button>):<div className="p-6 text-center text-sm text-zinc-500">Пока нет уведомлений</div>}</div></div></>}</div>
      <div className="relative"><button type="button" onClick={()=>setProfileOpen(v=>!v)} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-2.5 py-1.5 text-sm font-semibold transition hover:border-[var(--theme-accent)]/30"><img src={avatar||"/avatars/premium/01-cyan.svg"} alt="" className="h-8 w-8 rounded-lg object-cover"/><span className="hidden sm:inline">{user.nickname}</span><span className="text-xs text-zinc-500">⌄</span></button>{profileOpen&&<><button className="fixed inset-0 z-10" onClick={()=>setProfileOpen(false)} aria-label="Close profile menu"/><div className="absolute right-0 top-12 z-20 w-64 rounded-2xl border border-white/10 bg-[#0b0b10] p-2 shadow-2xl"><div className="border-b border-white/5 px-3 py-3"><div className="font-bold">{user.nickname}</div><div className="mt-1 text-xs text-zinc-500">Steam ID: {user.steamId||"—"}</div><div className="mt-2 text-lg font-black text-[var(--theme-accent)]">${Number(user.balance).toFixed(2)}</div></div><Link href="/profile" className="block rounded-xl px-3 py-2 text-sm hover:bg-white/5">Профиль</Link><Link href="/wallet" className="block rounded-xl px-3 py-2 text-sm hover:bg-white/5">Кошелёк</Link><Link href="/profile#theme" className="block rounded-xl px-3 py-2 text-sm hover:bg-white/5">Оформление</Link>{user.role&&user.role!=="USER"&&<Link href="/admin" className="block rounded-xl px-3 py-2 text-sm text-[var(--theme-accent)] hover:bg-white/5">Панель администратора</Link>}<button onClick={logout} className="mt-1 w-full rounded-xl border border-red-400/20 px-3 py-2 text-left text-sm text-red-300 hover:bg-red-500/10">{t.logout}</button></div></>}</div>
    </>:<Link href="/login" className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm font-semibold hover:border-[var(--theme-accent)]/30 hover:text-[var(--theme-accent)]">{t.loginSteam}</Link>}
   </div>
  </div>
  {menuOpen&&<div className="border-t border-white/10 bg-[#050507] px-4 py-3 md:hidden"><nav className="flex flex-col gap-1">{links}</nav>{user&&<div className="mt-2 flex gap-2 border-t border-white/5 pt-3"><Link href="/wallet" className="flex-1 rounded-xl border border-white/10 px-3 py-2 text-center text-sm">Кошелёк</Link><button onClick={logout} className="flex-1 rounded-xl border border-white/10 px-3 py-2 text-sm">{t.logout}</button></div>}</div>}
 </header>
}
