"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { useLanguage } from "../Common/LanguageContext";
import { languages } from "../../lib/language";
const FLAGS:{key:keyof typeof languages;name:string;src:string}[]=[
 {key:"RU",name:"Русский",src:"/images/flags/ru.svg"},{key:"UA",name:"Українська",src:"/images/flags/ua.svg"},{key:"EN",name:"English",src:"/images/flags/en.svg"},{key:"PL",name:"Polski",src:"/images/flags/pl.svg"}
];
export default function Header(){
 const{language,setLanguage,t}=useLanguage(); const[user,setUser]=useState<{nickname:string;balance:string;role?:string}|null>(null); const[langOpen,setLangOpen]=useState(false); const[menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{fetch("/api/auth/me",{cache:"no-store"}).then(r=>r.json()).then(d=>setUser(d.user??null)).catch(()=>{})},[]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});setUser(null);window.location.href="/"}
 const current=FLAGS.find(x=>x.key===language)||FLAGS[0]; const navClass="cursor-pointer rounded-lg px-2 py-1 text-sm text-zinc-400 transition hover:bg-pink-400/[.06] hover:text-pink-300 active:scale-95";
 const links=<><Link className={navClass} href="/" onClick={()=>setMenuOpen(false)}>{t.home}</Link><Link className={navClass} href="/matches" onClick={()=>setMenuOpen(false)}>{t.matches}</Link><Link className={navClass} href="/live" onClick={()=>setMenuOpen(false)}>{t.live}</Link><Link className={navClass} href="/rating" onClick={()=>setMenuOpen(false)}>{t.rating}</Link><Link className={navClass} href="/profile" onClick={()=>setMenuOpen(false)}>{t.profile}</Link></>;
 return <header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#050507]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6">
  <div className="flex items-center gap-2"><button className="grid h-9 w-9 place-items-center rounded-xl border border-white/10 bg-white/5 text-zinc-300 md:hidden" aria-label="Menu" onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?"×":"☰"}</button><Link href="/" className="flex items-center gap-2 font-black tracking-tight transition hover:opacity-90"><span className="grid h-9 w-9 place-items-center rounded-xl border border-pink-400/30 bg-pink-400/[.08] text-sm font-black text-pink-300">D</span><span className="text-xl tracking-[-.03em]">DUEL<span className="text-pink-400">PLAY</span></span></Link></div>
  <nav className="hidden items-center gap-3 text-sm md:flex">{links}</nav>
  <div className="flex items-center gap-2">
   <div className="relative"><button type="button" aria-label="Language" onClick={()=>setLangOpen(v=>!v)} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/5 p-2 hover:border-pink-400/30"><img src={current.src} alt={current.name} className="h-6 w-8 rounded object-cover"/></button>{langOpen&&<><button type="button" className="fixed inset-0 z-10 cursor-default" aria-label="Close languages" onClick={()=>setLangOpen(false)}/><div className="absolute right-0 top-12 z-20 w-44 rounded-2xl border border-white/10 bg-[#0b0b10] p-2 shadow-2xl">{FLAGS.map(x=><button key={x.key} type="button" onClick={()=>{setLanguage(x.key);setLangOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left text-sm hover:bg-white/5 ${language===x.key?"bg-pink-400/[.08] text-pink-300":"text-zinc-300"}`}><img src={x.src} alt={x.name} className="h-6 w-9 rounded object-cover"/><span>{x.name}</span></button>)}</div></>}</div>
   {user?<div className="flex items-center gap-2"><Link href="/wallet" className="hidden rounded-xl border border-pink-400/20 bg-pink-400/[.04] px-3 py-2 text-xs font-bold text-pink-300 sm:block">${Number(user.balance).toFixed(2)}</Link>{user.role&&user.role!=="USER"&&<Link href="/admin" title={t.adminAccess} aria-label={t.adminAccess} className="grid h-10 w-10 place-items-center rounded-xl border border-white/10 bg-white/5 text-zinc-300 hover:border-pink-400/30 hover:text-pink-300">⚙</Link>}<Link href="/profile" className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm font-semibold transition hover:border-pink-400/30 hover:text-pink-300">{user.nickname}</Link><button onClick={logout} className="hidden rounded-xl border border-white/10 px-3 py-2 text-xs text-zinc-400 hover:border-red-400/50 hover:bg-red-500/15 sm:block">{t.logout}</button></div>:<><Link href="/login" className="rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-sm font-semibold hover:border-pink-400/30 hover:text-pink-300">{t.loginSteam}</Link></>}
  </div></div>
  {menuOpen&&<div className="border-t border-white/10 bg-[#050507] px-4 py-3 md:hidden"><nav className="flex flex-col gap-1">{links}</nav>{user&&<div className="mt-2 flex gap-2 border-t border-white/5 pt-3"><Link href="/wallet" className="flex-1 rounded-xl border border-white/10 px-3 py-2 text-center text-sm">${Number(user.balance).toFixed(2)}</Link><button onClick={logout} className="flex-1 rounded-xl border border-white/10 px-3 py-2 text-sm">{t.logout}</button></div>}</div>}
 </header>
}
