"use client";
import {useEffect,useState} from "react";
import CenterModal from "../Common/CenterModal";
import {useAuth} from "../Common/AuthContext";
import {useLanguage} from "../Common/LanguageContext";

type Message={id:string;message:string;createdAt:string;sender?:{nickname:string;role?:string}|null};
type Ticket={id:string;subject:string;category:string;status:string;priority:string;createdAt:string;messages:Message[]};

export default function SupportWidget(){
 const{user}=useAuth(); const{t}=useLanguage();
 const[open,setOpen]=useState(false),[tickets,setTickets]=useState<Ticket[]>([]),[subject,setSubject]=useState(""),[message,setMessage]=useState(""),[category,setCategory]=useState("GENERAL"),[active,setActive]=useState<Ticket|null>(null),[reply,setReply]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[unread,setUnread]=useState(0);
 async function load(){if(!user){setTickets([]);setUnread(0);return}try{const [r,nr]=await Promise.all([fetch("/api/support",{cache:"no-store"}),fetch("/api/notifications",{cache:"no-store"})]);const d=await r.json().catch(()=>({}));const nd=await nr.json().catch(()=>({}));if(r.ok)setTickets(d.tickets??[]);const supportUnread=(nd.notifications??[]).filter((n:any)=>n.status==="UNREAD"&&(n.title==="Ответ поддержки"||n.title==="Обращение закрыто")).length;setUnread(supportUnread)}catch{}}
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),7000);return()=>window.clearInterval(timer)},[user?.id]);
 async function openTicket(t:Ticket){setActive(t);await fetch("/api/support",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketId:t.id})});await load()}
 async function send(){if(!subject.trim()||!message.trim()||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/support",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject,message,category})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Не удалось отправить");setSubject("");setMessage("");await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка отправки")}finally{setBusy(false)}}
 async function sendReply(){if(!active||!reply.trim()||busy)return;setBusy(true);setError("");try{const r=await fetch("/api/support",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketId:active.id,message:reply})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Не удалось отправить");setReply("");setActive(d.ticket);await load()}catch(e){setError(e instanceof Error?e.message:"Ошибка отправки")}finally{setBusy(false)}}
 function statusLabel(status:string){const m:any={OPEN:t.supportStatusOpen,ASSIGNED:t.supportStatusAssigned,IN_PROGRESS:t.supportStatusProgress,WAITING_ON_USER:t.supportStatusWaiting,RESOLVED:t.supportStatusResolved,CLOSED:t.supportStatusClosed};return m[status]||status}
 function categoryLabel(category:string){const m:any={GENERAL:t.supportCategoryGeneral,MATCH:t.supportCategoryMatch,PAYMENT:t.supportCategoryPayment,ACCOUNT:t.supportCategoryAccount,SECURITY:t.supportCategorySecurity};return m[category]||category}
 if(!user)return null;
 return <><button onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-40 flex items-center gap-3 rounded-2xl border border-[var(--theme-accent)]/35 bg-[#0b0b10]/95 px-4 py-3 text-left shadow-2xl backdrop-blur-xl transition hover:-translate-y-0.5 hover:border-[var(--theme-accent)]" aria-label={t.supportTitle}><span className="relative grid h-9 w-9 place-items-center rounded-xl bg-[var(--theme-accent-bg)] text-lg text-[var(--theme-accent)]">?{unread>0&&<span className="support-unread">{unread>9?"9+":unread}</span>}</span><span className="hidden sm:block"><b className="block text-sm">{t.supportTitle}</b><span className="text-xs text-zinc-500">{t.supportSubtitle}</span></span></button>
 <CenterModal open={open} title={t.supportTitle} onClose={()=>{if(!busy)setOpen(false)}}>
   {active?<div><button onClick={()=>setActive(null)} className="mb-4 text-sm font-bold text-[var(--theme-accent)]">{t.supportBack}</button><div className="rounded-2xl border border-white/5 bg-white/[.025] p-4"><b>{active.subject}</b><div className="mt-1 text-xs text-zinc-600">{statusLabel(active.status)} · {active.priority}</div></div><div className="mt-4 max-h-72 space-y-2 overflow-auto">{(active.messages??[]).map(m=><div key={m.id} className={`rounded-2xl p-3 ${m.sender?.nickname===user.nickname?"bg-[var(--theme-accent-bg)]":"bg-white/[.035]"}`}><div className="text-xs font-bold">{m.sender?.nickname||"Пользователь"}{m.sender?.role&&<span className="ml-2 text-zinc-600">{m.sender.role}</span>}</div><div className="mt-1 text-sm leading-6 text-zinc-300">{m.message}</div><div className="mt-1 text-[10px] text-zinc-600">{new Date(m.createdAt).toLocaleString()}</div></div>)}</div><textarea className="input mt-4 min-h-24 resize-none" value={reply} onChange={e=>setReply(e.target.value)} placeholder={t.supportMessagePlaceholder}/>{error&&<div className="mt-3 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</div>}<button disabled={!reply.trim()||busy} onClick={sendReply} className="mt-3 w-full rounded-xl bg-[var(--theme-accent)] py-3 font-black text-black disabled:opacity-40">{busy?t.supportSending:t.supportReplyButton}</button></div>
   :<div><div className="rounded-2xl border border-white/5 bg-white/[.025] p-4"><b>{t.supportNeedHelp}</b><p className="mt-1 text-sm leading-6 text-zinc-500">{t.supportDescription}</p></div><input className="input mt-4" value={subject} onChange={e=>setSubject(e.target.value)} placeholder={t.supportSubjectPlaceholder}/><select className="input mt-3" value={category} onChange={e=>setCategory(e.target.value)}><option value="GENERAL">{t.supportCategoryGeneral}</option><option value="MATCH">{t.supportCategoryMatch}</option><option value="PAYMENT">{t.supportCategoryPayment}</option><option value="ACCOUNT">{t.supportCategoryAccount}</option><option value="SECURITY">{t.supportCategorySecurity}</option></select><textarea className="input mt-3 min-h-28 resize-none" value={message} onChange={e=>setMessage(e.target.value)} placeholder={t.supportMessagePlaceholder2}/>{error&&<div className="mt-3 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</div>}<button disabled={!subject.trim()||!message.trim()||busy} onClick={send} className="mt-4 w-full rounded-xl bg-[var(--theme-accent)] py-3 font-black text-black disabled:opacity-40">{busy?t.supportSending:t.supportSendButton}</button><div className="mt-6"><div className="mb-2 text-xs font-black uppercase tracking-widest text-zinc-600">{t.supportMyTickets}</div>{tickets.length?tickets.map(ticket=><button key={ticket.id} onClick={()=>void openTicket(ticket)} className="mb-2 w-full rounded-xl border border-white/5 bg-white/[.025] p-3 text-left hover:border-[var(--theme-accent)]/30"><div className="flex items-center justify-between gap-3"><div className="font-bold">{ticket.subject}</div>{(ticket.messages??[]).some(m=>m.sender?.role&&m.sender.role!=="USER")&&<span className="text-[10px] font-black text-[var(--theme-accent)]">{t.supportAnswer}</span>}</div><div className="mt-1 text-xs text-zinc-600">{t.status} · {(ticket.messages??[]).length} {t.supportMessages}</div></button>):<div className="text-sm text-zinc-600">{t.supportNoTickets}</div>}</div></div>}
 </CenterModal></>
}
