"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import type {ReactNode} from "react";
import GlobalPlayerCard from "@/components/Profile/GlobalPlayerCard";

type Result={players:any[];clans:any[];events:any[];tournaments:any[];cases:any[];query:string};
const EMPTY:Result={players:[],clans:[],events:[],tournaments:[],cases:[],query:""};
export default function SearchPage(){
 const [q,setQ]=useState(""); const [data,setData]=useState<Result>(EMPTY); const [busy,setBusy]=useState(false);
 useEffect(()=>{const timer=window.setTimeout(async()=>{const term=q.trim();if(term.length<2){setData({...EMPTY,query:term});return}setBusy(true);try{const r=await fetch(`/api/search?q=${encodeURIComponent(term)}`,{cache:"no-store"});if(r.ok)setData(await r.json())}finally{setBusy(false)}},250);return()=>window.clearTimeout(timer)},[q]);
 return <main className="mx-auto min-h-screen max-w-6xl px-4 pb-20 pt-28 sm:px-6"><section className="panel rounded-3xl p-6 sm:p-9"><span className="pill">GLOBAL SEARCH</span><h1 className="mt-4 text-4xl font-black">Global Search</h1><p className="mt-2 text-zinc-500">Search players, clans, events, tournaments and cases.</p><div className="mt-7 relative"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Start typing…" className="input h-14 w-full pr-24 text-lg"/><span className="absolute right-4 top-4 text-xs text-zinc-600">{busy?"SEARCHING":"2+ chars"}</span></div>
 {q.trim().length>=2&&<div className="mt-8 grid gap-8 lg:grid-cols-2"><SearchSection title={`Players · ${data.players.length}`} empty="No players found.">{data.players.map(p=><GlobalPlayerCard key={p.id} player={{...p,rating:p.playerStats?.rating??1000}} />)}</SearchSection><SearchSection title={`Clans · ${data.clans.length}`} empty="No clans found.">{data.clans.map(c=><Link key={c.id} href={`/clans?clan=${encodeURIComponent(c.id)}`} className="flex items-center gap-3 rounded-2xl border border-white/5 bg-white/[.025] p-3 hover:border-pink-400/30"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/5 font-black">{c.tag||"CL"}</div><div className="min-w-0 flex-1"><b className="block truncate">{c.name}</b><span className="text-xs text-zinc-500">[{c.tag}] · Rating {c.rating} · {c._count?.members??0} members</span></div></Link>)}</SearchSection><SearchSection title={`Events · ${data.events.length}`} empty="No events found.">{data.events.map(e=><Link key={e.id} href="/events" className="flex items-center gap-3 rounded-2xl border border-white/5 bg-white/[.025] p-3 hover:border-pink-400/30"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/5">{e.icon||"🎉"}</div><div className="min-w-0 flex-1"><b className="block truncate">{e.name}</b><span className="text-xs text-zinc-500">{e.status} · {new Date(e.startsAt).toLocaleDateString()}</span></div></Link>)}</SearchSection><SearchSection title={`Tournaments · ${data.tournaments.length}`} empty="No tournaments found.">{data.tournaments.map(t=><Link key={t.id} href="/tournaments" className="flex items-center gap-3 rounded-2xl border border-white/5 bg-white/[.025] p-3 hover:border-pink-400/30"><div className="grid h-11 w-11 place-items-center rounded-xl bg-white/5">🏆</div><div className="min-w-0 flex-1"><b className="block truncate">{t.name}</b><span className="text-xs text-zinc-500">{t.status} · {t._count?.participants??0}/{t.maxPlayers} · ${t.prizePool?.toFixed?.(2)??"0.00"}</span></div></Link>)}</SearchSection><SearchSection title={`Cases · ${data.cases.length}`} empty="No cases found.">{data.cases.map(c=><Link key={c.id} href="/cases" className="flex items-center gap-3 rounded-2xl border border-white/5 bg-white/[.025] p-3 hover:border-pink-400/30"><img src={c.imageUrl} alt="" className="h-11 w-11 rounded-xl object-cover"/><div className="min-w-0 flex-1"><b className="block truncate">{c.name}</b><span className="text-xs text-zinc-500">${c.price.toFixed(2)} · {c.slug}</span></div></Link>)}</SearchSection></div>}
 <Link href="/hub" className="mt-8 inline-block text-sm text-pink-400">← HUB</Link></section></main>;
}
function SearchSection({title,empty,children}:{title:string;empty:string;children:ReactNode}){const has=Array.isArray(children)?children.length>0:!!children;return <section><div className="mb-3 text-xs font-black uppercase tracking-[.2em] text-zinc-600">{title}</div><div className="space-y-2">{has?children:<div className="rounded-2xl border border-white/5 p-6 text-sm text-zinc-500">{empty}</div>}</div></section>}
