"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function AnalyticsPage(){
 const[d,setD]=useState<any>();const[e,setE]=useState("");
 useEffect(()=>{fetch("/api/analytics",{cache:"no-store"}).then(async r=>{const x=await r.json();if(!r.ok)throw new Error(x.error||"Analytics error");setD(x)}).catch(x=>setE(x.message||"Analytics error"))},[]);
 if(e)return <main className="pt-28 text-center text-red-300">{e}</main>;if(!d)return <main className="pt-28 text-center text-zinc-500">Loading…</main>;
 const cards=[["K/D",d.kd],["HS%",`${d.hsPercent}%`],["AVG DMG",d.averageDamage],["RATING",d.rating],["WIN STREAK",`🔥 ${d.streak}`],["BEST STREAK",d.bestStreak],["BEST MAP",d.bestMap],["FAV WEAPON",d.favouriteWeapon]];
 return <main className="mx-auto min-h-screen max-w-7xl px-4 pb-20 pt-28 sm:px-6"><section className="panel rounded-3xl p-7 sm:p-10"><span className="pill">PLAYER ANALYTICS</span><h1 className="mt-4 text-4xl font-black">Performance Center</h1><p className="mt-3 text-zinc-500">K/D, headshots, damage, rating, streak and verified finished-match history.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4">{cards.map(([a,b])=><div key={a} className="rounded-2xl border border-white/5 bg-white/[.025] p-5"><div className="text-xs text-zinc-600">{a}</div><b className="mt-2 block truncate text-xl text-pink-400">{b}</b></div>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-4"><Stat label="WINS" value={d.wins}/><Stat label="LOSSES" value={d.losses}/><Stat label="DUELS" value={d.totalDuels}/><Stat label="RECORDED" value={d.recordedMatches}/></div><div className="mt-8 rounded-2xl border border-white/5 p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Recent match data</h2><span className="text-xs text-zinc-600">{d.recordedMatches} recorded</span></div><div className="mt-4 space-y-2">{d.history.length?d.history.map((x:any)=><Link href={`/matches/${x.matchId}`} key={`${x.matchId}-${x.createdAt}`} className="grid grid-cols-2 gap-3 rounded-xl bg-white/[.025] p-3 text-xs transition hover:bg-white/[.05] sm:grid-cols-6"><span>{x.mapName||"—"}</span><span>{x.weapon||"—"}</span><span>{x.kills}K / {x.deaths}D</span><span>{x.headshots} HS</span><span>{x.damage} DMG</span><span className={x.result==="WIN"?"text-emerald-300":"text-red-300"}>{x.result}</span></Link>):<p className="text-zinc-600">Данные появятся после завершённых матчей с GSI.</p>}</div></div></section></main>
}
function Stat({label,value}:{label:string;value:any}){return <div className="rounded-2xl border border-white/5 bg-white/[.02] p-4"><div className="text-[10px] font-black tracking-wider text-zinc-600">{label}</div><b className="mt-1 block text-lg">{value}</b></div>}
