// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const rawDatabaseUrl = process.env["DIRECT_URL"] || process.env["DATABASE_URL"] || "";
// Prisma migrations need session-level advisory locks. Neon pooled endpoints can
// time out on those locks, so prefer DIRECT_URL and safely fall back to the
// direct Neon hostname when DATABASE_URL points at a Neon pooler endpoint.
const migrationDatabaseUrl = rawDatabaseUrl.replace(/-pooler\./, ".");

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationDatabaseUrl!,
  },
});