<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>DuelPlayPlayerNameTest</AssemblyName>
    <RootNamespace>DuelPlayPlayerNameTest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DuelPlayPlayerNameTest.cs" />
    <Reference Include="CounterStrikeSharp.API">
      <HintPath>$(MSBuildProjectDirectory)\CounterStrikeSharp.API.server.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
