"use client";
import { useEffect, useState } from "react";

type AccessData={users:Array<{id:string;nickname:string;steamId:string|null;role:string;status:string}>;me:{id:string;nickname:string;roleCode:string|null;level:number;permissions:string[]};founder:boolean;roles:Array<{code:string;level:number;title:string;description:string;permissions:string[]}>;assignments:Array<{id:string;userId:string;roleCode:string;level:number;user:{id:string;nickname:string;steamId:string|null;role:string;status:string}}>} ;

export default function AdminAccessPage(){
 const [data,setData]=useState<AccessData|null>(null); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/admin/access",{cache:"no-store"});const j=await r.json();if(!r.ok){setError(j.error||"Ошибка доступа");return;}setData(j)}
 useEffect(()=>{void load()},[]);
 async function assign(userId:string,roleCode:string){setBusy(true);setError("");try{const r=await fetch("/api/admin/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,roleCode})});const j=await r.json();if(!r.ok){setError(j.error||"Не удалось изменить роль");return;}await load()}finally{setBusy(false)}}
 if(error&&!data)return <main className="min-h-screen bg-black px-6 pt-24 text-white"><div className="mx-auto max-w-5xl rounded-3xl border border-red-400/20 bg-red-400/5 p-8"><b>ACCESS DENIED</b><p className="mt-2 text-zinc-400">{error}</p><a className="mt-5 inline-block rounded-xl border border-white/10 px-4 py-2" href="/admin">Назад</a></div></main>;
 if(!data)return <main className="min-h-screen bg-black px-6 pt-24 text-white"><div className="mx-auto max-w-5xl text-zinc-500">Загрузка Admin Access Center…</div></main>;
 const canManage=data.me.permissions.includes("*")||data.me.permissions.includes("roles.manage");
 return <main className="min-h-screen bg-black px-4 pb-20 pt-24 text-white sm:px-6"><div className="mx-auto max-w-7xl">
  <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="text-xs font-black uppercase tracking-[.25em] text-pink-400">ADMIN ACCESS CENTER</div><h1 className="mt-2 text-3xl font-black sm:text-4xl">Уровни и права DuelPlay</h1><p className="mt-2 text-zinc-500">Backend RBAC. Интерфейс не является границей безопасности.</p></div><a href="/admin" className="rounded-xl border border-white/10 px-4 py-3 text-sm font-bold">← Центр управления</a></div>
  <div className="mt-6 rounded-3xl border border-pink-400/20 bg-pink-400/5 p-5"><div className="text-sm text-zinc-400">Текущий доступ</div><div className="mt-1 text-xl font-black">{data.me.nickname} · {data.me.roleCode||"NO ADMIN ROLE"} · LEVEL {data.me.level}</div><div className="mt-3 flex flex-wrap gap-2">{data.me.permissions.slice(0,24).map(p=><span key={p} className="rounded-full border border-white/10 px-2.5 py-1 text-[11px] text-zinc-400">{p}</span>)}{data.me.permissions.length>24&&<span className="rounded-full border border-white/10 px-2.5 py-1 text-[11px] text-zinc-500">+{data.me.permissions.length-24}</span>}</div></div>
  <section className="mt-8"><h2 className="text-xl font-black">10 уровней + Founder 999</h2><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.roles.map(r=><div key={r.code} className={`rounded-3xl border p-5 ${r.code==="FOUNDER"?"border-amber-400/30 bg-amber-400/5":"border-white/8 bg-white/[.025]"}`}><div className="flex items-center justify-between gap-3"><div className="font-black">{r.title}</div><div className="text-xs font-black text-pink-400">LEVEL {r.level}</div></div><p className="mt-2 text-sm leading-6 text-zinc-500">{r.description}</p><div className="mt-4 text-xs text-zinc-600">{r.permissions.includes("*")?"ALL PERMISSIONS":`${r.permissions.length} permissions`}</div></div>)}</div></section>
  {canManage&&<section className="mt-10"><h2 className="text-xl font-black">Назначить роль пользователю</h2><div className="mt-4 grid gap-3 rounded-3xl border border-white/8 bg-white/[.025] p-5 sm:grid-cols-[1fr_240px_auto]"><select id="rbac-user" className="rounded-xl border border-white/10 bg-black px-3 py-3"><option value="">Выберите пользователя…</option>{data.users.filter(u=>u.nickname!=="DuelPlayOwner").map(u=><option key={u.id} value={u.id}>{u.nickname} · {u.role}</option>)}</select><select id="rbac-role" className="rounded-xl border border-white/10 bg-black px-3 py-3">{data.roles.filter(r=>r.code!=="FOUNDER"||data.founder).map(r=><option key={r.code}>{r.code}</option>)}</select><button disabled={busy} onClick={()=>{const u=(document.getElementById("rbac-user") as HTMLSelectElement).value;const r=(document.getElementById("rbac-role") as HTMLSelectElement).value;if(u)void assign(u,r)}} className="rounded-xl bg-pink-400 px-5 py-3 font-black text-black disabled:opacity-40">Назначить</button></div></section>}
  {canManage&&<section className="mt-10"><h2 className="text-xl font-black">Назначенные роли</h2>{error&&<div className="mt-3 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</div>}<div className="mt-4 overflow-x-auto rounded-3xl border border-white/8"><table className="w-full min-w-[900px] text-sm"><thead className="bg-white/[.03] text-left text-zinc-500"><tr><th className="p-4">Пользователь</th><th className="p-4">Legacy role</th><th className="p-4">RBAC</th><th className="p-4">Level</th><th className="p-4">Статус</th><th className="p-4">Действие</th></tr></thead><tbody>{data.assignments.map(a=><tr key={a.id} className="border-t border-white/5"><td className="p-4 font-bold">{a.user.nickname}</td><td className="p-4 text-zinc-500">{a.user.role}</td><td className="p-4">{a.roleCode}</td><td className="p-4 text-pink-400">{a.level}</td><td className="p-4 text-zinc-500">{a.user.status}</td><td className="p-4"><select disabled={busy||a.user.nickname==="DuelPlayOwner"} value={a.roleCode} onChange={e=>void assign(a.userId,e.target.value)} className="rounded-xl border border-white/10 bg-black px-3 py-2">{data.roles.filter(r=>r.code!=="FOUNDER"||data.founder).map(r=><option key={r.code}>{r.code}</option>)}</select></td></tr>)}</tbody></table></div></section>}
 </div></main>
}
