"use client";
import {useEffect,useState} from "react";
import {useLanguage} from "../../components/Common/LanguageContext";

export default function ClansPage(){
  const{t}=useLanguage();
  const[selectedId,setSelectedId]=useState<string|null>(null); const[rows,setRows]=useState<any[]>([]); const[selected,setSelected]=useState<any>(null);
  const[mine,setMine]=useState<any>(null); const[name,setName]=useState(""); const[tag,setTag]=useState(""); const[msg,setMsg]=useState(""); const[busy,setBusy]=useState(false);
  async function load(){const [r,m]=await Promise.all([fetch("/api/clans",{cache:"no-store"}),fetch("/api/clans?mine=1",{cache:"no-store"})]);setRows(r.ok?await r.json():[]);setMine(m.ok?await m.json():null)}
  useEffect(()=>{void load();const q=new URLSearchParams(window.location.search).get("clan");setSelectedId(q)},[]);
  useEffect(()=>{if(!selectedId){setSelected(null);return}fetch(`/api/clans?id=${encodeURIComponent(selectedId)}`,{cache:"no-store"}).then(async r=>setSelected(r.ok?await r.json():null)).catch(()=>setSelected(null))},[selectedId]);
  async function action(action:string, clanId:string, userId?:string){setBusy(true);try{const r=await fetch("/api/clans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,clanId,userId})});const d=await r.json();setMsg(r.ok?"Done":d.error||t.error);if(r.ok)await load();if(r.ok&&action==="join"){setSelectedId(clanId)}}finally{setBusy(false)}}
  async function create(){setBusy(true);try{const r=await fetch("/api/clans",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create",name,tag})});const d=await r.json();setMsg(r.ok?t.clanCreated:d.error||t.error);if(r.ok){setName("");setTag("");await load();setSelectedId(d.id)}}finally{setBusy(false)}}
  const myRole=selected&&mine?.clanId===selected.id?mine.role:null;
  return <main className="mx-auto min-h-screen max-w-6xl px-4 pb-20 pt-28"><section className="panel rounded-3xl p-7 sm:p-10"><span className="pill">CLANS</span><h1 className="mt-4 text-4xl font-black">{t.clansTitle}</h1>
    {!mine&&<div className="mt-6 grid gap-2 sm:grid-cols-[1fr_120px_auto]"><input className="input" value={name} onChange={e=>setName(e.target.value)} maxLength={24} placeholder={t.clanName}/><input className="input uppercase" value={tag} onChange={e=>setTag(e.target.value.toUpperCase())} maxLength={6} placeholder={t.tag}/><button disabled={busy} onClick={create} className="rounded-xl bg-pink-400 px-5 font-black text-black disabled:opacity-50">{t.create}</button></div>}
    {mine&&<div className="mt-5 rounded-2xl border border-pink-400/20 bg-pink-400/[.035] p-4 text-sm">Your clan: <b>{mine.clan?.name}</b> <span className="text-pink-400">[{mine.clan?.tag}]</span> · {mine.role}<button disabled={busy} onClick={()=>action("leave",mine.clanId)} className="ml-4 rounded-lg border border-white/10 px-3 py-1 text-xs">Leave</button></div>}
    {msg&&<p className="mt-3 text-sm text-pink-300">{msg}</p>}
    {selected&&<section className="mb-6 mt-6 rounded-2xl border border-pink-400/20 bg-pink-400/[.035] p-5"><div className="flex items-start justify-between gap-4"><div><span className="pill">CLAN PROFILE</span><h2 className="mt-2 text-2xl font-black">{selected.name} <span className="text-pink-400">[{selected.tag}]</span></h2><p className="mt-1 text-sm text-zinc-500">Rank #{rows.find(x=>x.id===selected.id)?.rank||"—"} · Rating {selected.rating} · {selected.wins}W / {selected.losses}L · {selected.members?.length||0}/20 members</p></div><div className="flex gap-2"><a href="/clan-wars" className="rounded-lg border border-white/10 px-3 py-1 text-xs">Clan wars</a><a href="/clans" className="text-sm text-zinc-500">Close</a></div></div>
      {!mine&&<button disabled={busy||selected.members?.length>=20} onClick={()=>action("join",selected.id)} className="mt-4 rounded-xl bg-pink-400 px-4 py-2 text-sm font-black text-black disabled:opacity-50">Join clan</button>}
      <div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{(selected.members||[]).map((m:any)=><div key={m.id} className="rounded-xl border border-white/5 bg-white/[.025] p-3"><a href={`/profile/${encodeURIComponent(m.user.nickname)}`}><b>{m.user.nickname}</b></a><span className="mt-1 block text-xs text-zinc-600">Lv.{m.user.level} · {m.role}</span>{myRole&&m.user.id!==mine.userId&&m.role!=="LEADER"&&<div className="mt-2 flex gap-1">{myRole==="LEADER"&&m.role==="MEMBER"&&<button disabled={busy} onClick={()=>action("promote",selected.id,m.user.id)} className="rounded bg-white/5 px-2 py-1 text-[10px]">Promote</button>}{myRole==="LEADER"&&m.role==="OFFICER"&&<button disabled={busy} onClick={()=>action("demote",selected.id,m.user.id)} className="rounded bg-white/5 px-2 py-1 text-[10px]">Demote</button>}{(myRole==="LEADER"||(myRole==="OFFICER"&&m.role==="MEMBER"))&&<button disabled={busy} onClick={()=>action("kick",selected.id,m.user.id)} className="rounded bg-white/5 px-2 py-1 text-[10px]">Kick</button>}</div>}</div>)}</div></section>}
    <div className="mt-8 grid gap-3 sm:grid-cols-2">{rows.map(x=><article key={x.id} onClick={()=>{window.history.pushState({},"",`/clans?clan=${encodeURIComponent(x.id)}`);setSelectedId(x.id)}} className="cursor-pointer rounded-2xl border border-white/5 p-5 transition hover:-translate-y-0.5 hover:border-pink-400/30"><div className="flex justify-between"><b>#{x.rank} {x.name} <span className="text-pink-400">[{x.tag}]</span></b><span>{x.rating}</span></div><div className="mt-2 text-xs text-zinc-600">{x.members?.length||0}/20 {t.members} · {x.wins}W / {x.losses}L</div></article>)}</div>
  </section></main>
}
