"use client";
import {useEffect,useRef,useState} from "react";
import Header from "@/components/Header/Header";
import CenterModal from "@/components/Common/CenterModal";
import {useLanguage} from "@/components/Common/LanguageContext";
import {THEMES} from "@/lib/themes";

type AdminData={me:{nickname:string;role:string;level:number};themes:any[];standardTheme:string;backgroundTheme:string;users:any[];matches:any[];transactions:any[];disputes:any[];fraud:any[];tickets:any[];topSkins:any[];servers:any[];logs:any[];avatarPresets:any[]};
const BG=[{id:"stars",name:"Neon Stars",img:"/theme-backgrounds/stars.svg"},{id:"blue-nebula",name:"Blue Nebula",img:"/theme-backgrounds/blue-nebula.svg"},{id:"green-aurora",name:"Green Aurora",img:"/theme-backgrounds/green-aurora.svg"},{id:"purple-galaxy",name:"Purple Galaxy",img:"/theme-backgrounds/purple-galaxy.svg"},{id:"gold-space",name:"Gold Space",img:"/theme-backgrounds/gold-space.svg"}];
export default function AdminPage(){
 const{language}=useLanguage();const L=language==="EN"?{users:"Users",matches:"Matches",finance:"Finance",security:"Security",support:"Support",settings:"Settings",notifications:"Notifications",skins:"Top skins",balance:"Balance",locked:"Locked",search:"Search",credit:"Add funds",debit:"Subtract",amount:"Amount, USD",reason:"Reason",close:"Close",save:"Save",send:"Send notification",title:"Title",message:"Message",all:"All users",background:"Background atmosphere",theme:"Site theme"}:{users:"Пользователи",matches:"Матчи",finance:"Финансы",security:"Безопасность",support:"Поддержка",settings:"Настройки",notifications:"Уведомления",skins:"Топ скины",balance:"Баланс",locked:"Заблокировано",search:"Поиск",credit:"Пополнить",debit:"Списать",amount:"Сумма, USD",reason:"Причина",close:"Закрыть",save:"Сохранить",send:"Отправить уведомление",title:"Заголовок",message:"Текст",all:"Все пользователи",background:"Фоновая атмосфера",theme:"Тема сайта"};
 const[d,setD]=useState<AdminData|null>(null);const[tab,setTab]=useState("users");const[q,setQ]=useState("");const[err,setErr]=useState("");const[busy,setBusy]=useState(false);const[walletUser,setWalletUser]=useState<any>(null);const[walletMode,setWalletMode]=useState<"credit"|"debit">("credit");const[amount,setAmount]=useState("");const[reason,setReason]=useState("");const[noticeTitle,setNoticeTitle]=useState("");const[noticeBody,setNoticeBody]=useState("");const[noticeTarget,setNoticeTarget]=useState("ALL");const[skinName,setSkinName]=useState("");const[file,setFile]=useState<File|null>(null);const[filePreview,setFilePreview]=useState("");const fileRef=useRef<HTMLInputElement|null>(null);
 async function load(){const r=await fetch("/api/admin",{cache:"no-store"});const x=await r.json().catch(()=>({}));if(!r.ok){setErr(x.error||"Access denied");return}setD(x);}
 useEffect(()=>{load()},[]);
 async function act(body:any){setBusy(true);setErr("");try{const r=await fetch("/api/admin",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json().catch(()=>({}));if(!r.ok){setErr(x.error||"Operation failed");return false}await load();return true}catch{setErr("Operation failed");return false}finally{setBusy(false)}}
 async function saveWallet(){const n=Number(amount);if(!walletUser||!(n>0))return;const ok=await act({action:"walletAdjust",userId:walletUser.id,amount:walletMode==="debit"?-n:n,reason});if(ok){setWalletUser(null);setAmount("");setReason("")}}
 async function sendNotice(){const ok=await act({action:"sendNotification",title:noticeTitle,body:noticeBody,target:noticeTarget});if(ok){setNoticeTitle("");setNoticeBody("")}}
 function chooseFile(f:File|null){setFile(f);if(!f){setFilePreview("");return}const r=new FileReader();r.onload=()=>setFilePreview(String(r.result));r.readAsDataURL(f)}
 async function addSkin(){if(!filePreview||!skinName)return;await act({action:"topSkinAdd",name:skinName,imageData:filePreview});setSkinName("");setFile(null);setFilePreview("")}
 if(!d)return <><Header/><main className="pt-32 text-center text-zinc-500">Loading…</main></>;
 const users=d.users.filter(u=>!q||u.nickname.toLowerCase().includes(q.toLowerCase())||(u.steamId||"").includes(q));
 const menu=[[
  "users",L.users,d.users.length,"♟"],["matches",L.matches,d.matches.length,"⚔"],["finance",L.finance,d.transactions.length,"$"],["transactions","Транзакции",d.transactions.length,"↔"],["servers","Серверы",d.servers.length,"◈"],["settings",L.settings,d.themes.length,"⚙"],["logs","Логи",d.logs.length,"≡"],["notifications",L.notifications,0,"◉"],["skins",L.skins,d.topSkins.length,"◇"],["avatars","Аватары",d.avatarPresets.length,"✦"],["security",L.security,d.fraud.length+d.disputes.length,"!"],["support",L.support,d.tickets.length,"?"]];
 return <><Header/><main className="mx-auto min-h-screen max-w-7xl px-4 pb-20 pt-24 sm:px-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><span className="pill">ЦЕНТР УПРАВЛЕНИЯ · LEVEL {d.me.level}</span><h1 className="mt-3 text-4xl font-black">Центр управления</h1><p className="mt-2 text-zinc-500">Игроки, матчи, финансы, уведомления, серверы и оформление DuelPlay.</p></div><div className="rounded-2xl border border-[var(--theme-accent)]/25 bg-[var(--theme-accent-bg)] px-4 py-3 text-sm"><b>{d.me.nickname}</b><span className="ml-2 text-[var(--theme-accent)]">{d.me.role}</span></div></div>
 <div className="mt-8 grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="panel rounded-3xl p-3 h-fit lg:sticky lg:top-24">{menu.map(([id,name,n,icon])=><button key={String(id)} onClick={()=>setTab(String(id))} className={`mb-1 flex w-full items-center justify-between rounded-xl px-3 py-3 text-left text-sm transition ${tab===id?"bg-[var(--theme-accent-bg)] text-[var(--theme-accent)]":"text-zinc-400 hover:bg-white/5 hover:text-white"}`}><span><span className="mr-3 opacity-80">{icon}</span>{name}</span><span className="text-xs text-zinc-600">{n}</span></button>)}</aside>
 <section>{err&&<div className="mb-4 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{err}</div>}
 {tab==="users"&&<div className="panel rounded-3xl p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black">{L.users}</h2><input className="input max-w-xs" placeholder={L.search} value={q} onChange={e=>setQ(e.target.value)}/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-left text-zinc-500"><tr><th className="p-3">Игрок</th><th className="p-3">Steam ID</th><th className="p-3">Роль</th><th className="p-3">Статус</th><th className="p-3">{L.balance}</th><th className="p-3">{L.locked}</th><th className="p-3">Действия</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-white/5"><td className="p-3"><b>{u.nickname}</b></td><td className="p-3 text-xs text-zinc-500">{u.steamId||"—"}</td><td className="p-3"><select disabled={d.me.level<5} value={u.role} onChange={e=>act({action:"userRole",userId:u.id,role:e.target.value})} className="rounded-lg border border-white/10 bg-black px-2 py-2">{["USER","SUPPORT","MODERATOR","ADMIN","SUPERADMIN"].map(x=><option key={x}>{x}</option>)}</select></td><td className="p-3">{u.status}</td><td className="p-3 font-bold">${Number(u.balance).toFixed(2)}</td><td className="p-3">${Number(u.lockedBalance).toFixed(2)}</td><td className="p-3"><div className="flex gap-2"><button onClick={()=>{setWalletUser(u);setWalletMode("credit");setAmount("");setReason("")}} className="rounded-lg border border-[var(--theme-accent)]/30 px-3 py-2 text-xs text-[var(--theme-accent)]">{L.credit}</button><button disabled={u.role==="SUPERADMIN"} onClick={()=>{setWalletUser(u);setWalletMode("debit");setAmount("");setReason("")}} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{L.debit}</button></div></td></tr>)}</tbody></table></div></div>}
 {tab==="matches"&&<Panel title={L.matches}>{d.matches.map(m=><div key={m.id} className="mb-2 flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white/[.03] p-4"><div><b>{m.playerOne.nickname}</b> <span className="text-[var(--theme-accent)]">VS</span> <b>{m.playerTwo?.nickname||"—"}</b><div className="mt-1 text-xs text-zinc-500">{m.mapName} · ${Number(m.betAmount).toFixed(2)} · {m.status}</div></div>{["WAITING_FOR_PLAYERS","READY"].includes(m.status)&&<button onClick={()=>act({action:"cancelMatch",matchId:m.id})} className="rounded-xl border border-red-400/25 px-3 py-2 text-xs text-red-300">Отменить</button>}</div>)}</Panel>}
 {tab==="finance"&&<Panel title={L.finance}><div className="grid gap-3 md:grid-cols-2">{d.transactions.map(x=><div key={x.id} className="rounded-2xl border border-white/5 bg-white/[.03] p-4"><div className="flex justify-between gap-3"><b>{x.wallet.user.nickname}</b><span className={Number(x.amount)>=0?"text-emerald-300":"text-red-300"}>{Number(x.amount)>=0?"+":""}${Number(x.amount).toFixed(2)}</span></div><div className="mt-1 text-xs text-zinc-500">{x.type} · {x.status}</div><div className="mt-2 text-sm text-zinc-300">{x.description}</div><div className="mt-2 text-[11px] text-zinc-600">{new Date(x.createdAt).toLocaleString()}</div></div>)}</div></Panel>}
 {tab==="transactions"&&<Panel title="Транзакции"><div className="space-y-2">{d.transactions.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-white/5 bg-white/[.025] p-4"><div><b>{x.wallet.user.nickname}</b><div className="mt-1 text-sm text-zinc-400">{x.description||x.type}</div><div className="mt-1 text-[11px] text-zinc-600">{new Date(x.createdAt).toLocaleString()}</div></div><span className={Number(x.amount)>=0?"text-emerald-300":"text-red-300"}>{Number(x.amount)>=0?"+":""}${Number(x.amount).toFixed(2)}</span></div>)}</div></Panel>}
 {tab==="servers"&&<Panel title="Серверы"><div className="grid gap-3 sm:grid-cols-2">{d.servers.map(s=><div key={s.id} className="rounded-2xl border border-white/5 bg-white/[.025] p-5"><div className="flex items-center justify-between"><b>{s.name}</b><span className={s.status==="READY"?"text-emerald-300":"text-zinc-400"}>{s.status}</span></div><div className="mt-2 text-sm text-zinc-400">{s.host}:{s.port}</div><div className="mt-2 text-xs text-zinc-500">Матч: {s.match?`#${s.match.id.slice(0,8)} · ${s.match.status} · ${s.match.mapName||"—"}`:"Свободен"}</div><div className="mt-1 text-xs text-zinc-600">PID: {s.processId||"—"} · heartbeat: {s.lastHeartbeat?new Date(s.lastHeartbeat).toLocaleString():"—"}</div></div>)}</div></Panel>}
 {tab==="logs"&&<Panel title="Логи"><div className="space-y-2">{d.logs.map(x=><div key={x.id} className="rounded-2xl border border-white/5 bg-white/[.025] p-4"><div className="flex flex-wrap justify-between gap-2"><b>{x.action}</b><span className="text-xs text-zinc-600">{new Date(x.createdAt).toLocaleString()}</span></div><div className="mt-1 text-sm text-zinc-400">Админ: {x.user?.nickname||"—"} · {x.targetType||"—"} {x.targetId?`· ${x.targetId}`:""}</div></div>)}</div></Panel>}
 {tab==="notifications"&&<div className="panel rounded-3xl p-6"><h2 className="text-2xl font-black">{L.notifications}</h2><p className="mt-2 text-sm text-zinc-500">Отправляй системные объявления о доработках, изменениях, профилактике и важных событиях.</p><div className="mt-6 grid gap-4"><input className="input" placeholder={L.title} value={noticeTitle} onChange={e=>setNoticeTitle(e.target.value)}/><textarea className="input min-h-32 resize-y" placeholder={L.message} value={noticeBody} onChange={e=>setNoticeBody(e.target.value)}/><select className="input" value={noticeTarget} onChange={e=>setNoticeTarget(e.target.value)}><option value="ALL">{L.all}</option>{d.users.map(u=><option key={u.id} value={u.id}>{u.nickname}</option>)}</select><button disabled={busy||!noticeTitle.trim()||!noticeBody.trim()} onClick={sendNotice} className="rounded-2xl bg-[var(--theme-accent)] py-4 font-black text-black disabled:opacity-40">{L.send}</button></div></div>}
 {tab==="skins"&&<div className="panel rounded-3xl p-6"><h2 className="text-2xl font-black">{L.skins}</h2><p className="mt-2 text-sm text-zinc-500">Загружай лучшие работы сообщества. После публикации они появляются в общем блоке на главной.</p><div className="mt-6 grid gap-4 sm:grid-cols-[1fr_1fr_auto] items-end"><label><span className="mb-2 block text-xs text-zinc-500">Название</span><input className="input" value={skinName} onChange={e=>setSkinName(e.target.value)} placeholder="Например, Neon Dragon"/></label><label><span className="mb-2 block text-xs text-zinc-500">Изображение</span><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseFile(e.target.files?.[0]||null)} className="block w-full rounded-xl border border-white/10 bg-black px-3 py-3 text-sm"/></label><button disabled={!skinName||!filePreview||busy} onClick={addSkin} className="rounded-xl bg-[var(--theme-accent)] px-5 py-3 font-black text-black disabled:opacity-40">Добавить</button></div>{filePreview&&<img src={filePreview} alt="preview" className="mt-4 h-40 w-56 rounded-2xl object-cover border border-white/10"/>}<div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{d.topSkins.map(s=><div key={s.id} className="overflow-hidden rounded-2xl border border-white/7 bg-white/[.025]"><img src={s.imageData} alt={s.name} className="aspect-[4/3] w-full object-cover"/><div className="p-3"><div className="truncate text-sm font-bold">{s.name}</div><button onClick={()=>act({action:"topSkinDelete",id:s.id})} className="mt-2 text-xs text-red-300">Удалить</button></div></div>)}</div></div>}
 {tab==="avatars"&&<div className="panel rounded-3xl p-6"><h2 className="text-2xl font-black">Аватары DuelPlay</h2><p className="mt-2 text-sm text-zinc-500">Добавляй лучшие изображения сообщества в общий выбор аватаров профиля.</p><div className="mt-6 grid gap-4 sm:grid-cols-[1fr_1fr_auto] items-end"><label><span className="mb-2 block text-xs text-zinc-500">Название</span><input id="avatar-name" className="input" placeholder="Neon Wolf"/></label><label><span className="mb-2 block text-xs text-zinc-500">Изображение</span><input id="avatar-file" type="file" accept="image/png,image/jpeg,image/webp" className="block w-full rounded-xl border border-white/10 bg-black px-3 py-3 text-sm"/></label><AvatarUpload act={act}/></div><div className="mt-6 grid grid-cols-3 gap-3 sm:grid-cols-6">{d.avatarPresets.map(a=><div key={a.id} className="overflow-hidden rounded-2xl border border-white/7 bg-white/[.025]"><img src={a.imageData} alt={a.name} className="aspect-square w-full object-cover"/><div className="p-2"><div className="truncate text-xs font-bold">{a.name}</div><button onClick={()=>act({action:"avatarPresetDelete",id:a.id})} className="mt-1 text-[11px] text-red-300">Удалить</button></div></div>)}</div></div>}
 {tab==="settings"&&<div className="space-y-6"><Panel title={L.theme}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{d.themes.map(x=><button key={x.id} type="button" onClick={async()=>{const ok=await act({action:"standardTheme",theme:x.id});if(ok)window.dispatchEvent(new Event("duelplay:theme-changed"))}} className={`overflow-hidden rounded-2xl border text-left ${d.standardTheme===x.id?"border-[var(--theme-accent)]/80":"border-white/8"}`}><div className="h-16" style={{background:`linear-gradient(135deg,${x.preview[0]} 0 45%,${x.preview[1]} 45% 70%,${x.preview[2]} 70%)`}}/><div className="p-3"><b className="text-sm">{x.name}</b><div className="mt-1 text-[11px] text-zinc-500">{x.description}</div></div></button>)}</div></Panel><Panel title={L.background}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{BG.map(x=><button key={x.id} onClick={async()=>{const ok=await act({action:"backgroundTheme",background:x.id});if(ok)window.dispatchEvent(new Event("duelplay:theme-changed"))}} className={`overflow-hidden rounded-2xl border text-left ${d.backgroundTheme===x.id?"border-[var(--theme-accent)]/80":"border-white/8"}`}><img src={x.img} className="h-24 w-full object-cover" alt=""/><div className="p-3 text-sm font-bold">{x.name}</div></button>)}</div></Panel></div>}
 {tab==="security"&&<Panel title={L.security}><div className="grid gap-3 md:grid-cols-2">{d.fraud.map(x=><div key={x.id} className="rounded-2xl bg-white/[.03] p-4"><b>{x.user.nickname}</b><div className="text-xs text-zinc-500">Risk {x.riskScore} · {x.status}</div></div>)}{d.disputes.map(x=><div key={x.id} className="rounded-2xl bg-white/[.03] p-4"><b>{x.reporter.nickname}</b><div className="text-xs text-zinc-500">{x.status} · {x.reason}</div></div>)}</div></Panel>}
 {tab==="support"&&<Panel title={L.support}>{d.tickets.map(x=><div key={x.id} className="mb-2 rounded-2xl bg-white/[.03] p-4"><b>{x.subject}</b><div className="text-xs text-zinc-500">{x.user.nickname} · {x.status} · {x.priority}</div></div>)}</Panel>}
 </section></div></main>
 <CenterModal open={Boolean(walletUser)} title={walletMode==="debit"?"Списание средств":"Пополнение баланса"} onClose={()=>{if(!busy)setWalletUser(null)}}><div className="rounded-2xl border border-white/5 bg-white/[.025] p-4"><div className="text-sm text-zinc-500">Игрок</div><div className="mt-1 text-xl font-black">{walletUser?.nickname}</div><div className="mt-1 text-sm text-zinc-500">Баланс: <b className="text-white">${Number(walletUser?.balance||0).toFixed(2)}</b></div></div><label className="mt-5 block"><span className="mb-2 block text-xs text-zinc-500">{L.amount}</span><input autoFocus className="input" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="mt-4 block"><span className="mb-2 block text-xs text-zinc-500">{L.reason}</span><input className="input" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Например: компенсация / нарушение правил"/></label><div className="mt-4 rounded-2xl border border-[var(--theme-accent)]/10 bg-[var(--theme-accent-bg)] p-4 text-sm text-zinc-400">{walletMode==="debit"?"Сумма автоматически переводится в кошелёк владельца SUPERADMIN.":"Административное зачисление попадёт в историю транзакций и аудит."}</div><div className="mt-5 flex gap-3"><button onClick={()=>setWalletUser(null)} className="flex-1 rounded-2xl border border-white/10 py-3 font-bold">{L.close}</button><button disabled={busy||!(Number(amount)>0)} onClick={saveWallet} className="flex-1 rounded-2xl bg-[var(--theme-accent)] py-3 font-black text-black disabled:opacity-40">{L.save}</button></div></CenterModal></>}
function AvatarUpload({act}:{act:(body:any)=>Promise<boolean>}){const[busy,setBusy]=useState(false);async function run(){const n=(document.getElementById("avatar-name") as HTMLInputElement)?.value.trim();const f=(document.getElementById("avatar-file") as HTMLInputElement)?.files?.[0];if(!n||!f)return;setBusy(true);const r=new FileReader();r.onload=async()=>{const ok=await act({action:"avatarPresetAdd",name:n,imageData:String(r.result)});setBusy(false);if(ok){(document.getElementById("avatar-name") as HTMLInputElement).value="";(document.getElementById("avatar-file") as HTMLInputElement).value=""}};r.readAsDataURL(f)}return <button disabled={busy} onClick={run} className="rounded-xl bg-[var(--theme-accent)] px-5 py-3 font-black text-black disabled:opacity-40">{busy?"…":"Добавить"}</button>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="panel rounded-3xl p-6"><h2 className="text-2xl font-black">{title}</h2><div className="mt-5">{children}</div></div>}
