"use client";
import {useEffect,useState} from "react";
import Header from "@/components/Header/Header";
import {useTheme} from "@/components/Common/ThemeProvider";
import {useLanguage} from "@/components/Common/LanguageContext";

type AdminData={me:any;themes:any[];standardTheme:string;standardAccent?:string;users:any[];matches:any[];transactions:any[];disputes:any[];fraud:any[];tickets:any[]};
const copy:any={RU:{title:"Центр управления",sub:"Управление матчами, игроками, финансами, безопасностью и интерфейсом.",users:"Игроки",matches:"Матчи",finance:"Финансы",security:"Безопасность",support:"Поддержка",settings:"Настройки",standard:"Стандартная тема",role:"Роль",status:"Статус",balance:"Баланс",locked:"Заблокировано",save:"Сохранить",credit:"Зачислить",debit:"Списать",cancel:"Отменить",no:"Нет данных",search:"Поиск",themeNote:"Эта тема применяется только к пользователям со стандартным стилем.",player:"Игрок",actions:"Действия",style:"Стиль",fraudCases:"Проверки риска",disputes:"Споры",operationCredit:"Пополнить баланс",operationDebit:"Списать с баланса",matchCancel:"Отменить матч"},UA:{title:"Центр керування",sub:"Керування матчами, гравцями, фінансами, безпекою та інтерфейсом.",users:"Гравці",matches:"Матчі",finance:"Фінанси",security:"Безпека",support:"Підтримка",settings:"Налаштування",standard:"Стандартна тема",role:"Роль",status:"Статус",balance:"Баланс",locked:"Заблоковано",save:"Зберегти",credit:"Зарахувати",debit:"Списати",cancel:"Скасувати",no:"Немає даних",search:"Пошук",themeNote:"Тема застосовується лише до користувачів зі стандартним стилем.",player:"Гравець",actions:"Дії",style:"Стиль",fraudCases:"Перевірки ризику",disputes:"Спори",operationCredit:"Поповнити баланс",operationDebit:"Списати з балансу",matchCancel:"Скасувати матч"},EN:{title:"Control Center",sub:"Manage matches, players, finance, security and the interface.",users:"Players",matches:"Matches",finance:"Finance",security:"Security",support:"Support",settings:"Settings",standard:"Standard theme",role:"Role",status:"Status",balance:"Balance",locked:"Locked",save:"Save",credit:"Credit",debit:"Debit",cancel:"Cancel",no:"No data",search:"Search",themeNote:"This theme applies only to users who use the standard style.",player:"Player",actions:"Actions",style:"Style",fraudCases:"Risk checks",disputes:"Disputes",operationCredit:"Add to balance",operationDebit:"Subtract from balance",matchCancel:"Cancel match"},PL:{title:"Centrum zarządzania",sub:"Zarządzaj meczami, graczami, finansami, bezpieczeństwem i interfejsem.",users:"Gracze",matches:"Mecze",finance:"Finanse",security:"Bezpieczeństwo",support:"Wsparcie",settings:"Ustawienia",standard:"Motyw standardowy",role:"Rola",status:"Status",balance:"Saldo",locked:"Zablokowane",save:"Zapisz",credit:"Dodaj",debit:"Odejmij",cancel:"Anuluj",no:"Brak danych",search:"Szukaj",themeNote:"Motyw dotyczy tylko użytkowników korzystających ze stylu standardowego.",player:"Gracz",actions:"Akcje",style:"Styl",fraudCases:"Kontrole ryzyka",disputes:"Spory",operationCredit:"Dodaj do salda",operationDebit:"Odejmij z salda",matchCancel:"Anuluj mecz"}};
export default function AdminPage(){const {language}=useLanguage(); const L=copy[language]||copy.RU;const[d,setD]=useState<AdminData|null>(null);const[tab,setTab]=useState("users");const[q,setQ]=useState("");const[busy,setBusy]=useState("");const[err,setErr]=useState("");const{theme}=useTheme();
 async function load(){const r=await fetch("/api/admin",{cache:"no-store"});const x=await r.json();if(!r.ok){setErr(x.error||"Access denied");return}setD(x)}useEffect(()=>{load()},[]);
 async function act(body:any){setBusy(JSON.stringify(body));setErr("");const r=await fetch("/api/admin",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();if(!r.ok)setErr(x.error||"Operation failed");else await load();setBusy("")}
 if(err&&!d)return <><Header/><main className="mx-auto max-w-3xl px-4 pt-32"><div className="panel rounded-3xl p-10 text-center text-red-300">{err}</div></main></>;if(!d)return <><Header/><main className="pt-32 text-center text-zinc-500">Loading…</main></>;
 const users=d.users.filter(u=>!q||u.nickname.toLowerCase().includes(q.toLowerCase())||(u.email||"").toLowerCase().includes(q.toLowerCase()));
 return <><Header/><main className="mx-auto min-h-screen max-w-7xl px-4 pb-20 pt-28"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><span className="pill">ЦЕНТР УПРАВЛЕНИЯ · LEVEL {d.me.level}</span><h1 className="mt-3 text-4xl font-black">{L.title}</h1><p className="mt-2 text-zinc-500">{L.sub}</p></div><div className="rounded-2xl border border-white/10 bg-white/[.03] px-4 py-3 text-sm"><b>{d.me.nickname}</b><span className="ml-2 text-pink-400">{d.me.role}</span></div></div>
 <div className="mt-8 grid gap-2 sm:grid-cols-6">{[["users",L.users,d.users.length],["matches",L.matches,d.matches.length],["finance",L.finance,d.transactions.length],["security",L.security,d.fraud.length+d.disputes.length],["support",L.support,d.tickets.length],["settings",L.settings,"10"]].map(([id,name,n])=><button key={id} onClick={()=>setTab(String(id))} className={`rounded-2xl border p-4 text-left transition ${tab===id?"border-pink-400/50 bg-pink-400/[.07]":"border-white/8 bg-white/[.025] hover:bg-white/[.05]"}`}><div className="text-xs text-zinc-500">{name}</div><div className="mt-1 text-xl font-black text-pink-400">{n}</div></button>)}</div>
 {err&&<div className="mt-4 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{err}</div>}
 {tab==="users"&&<section className="panel mt-6 rounded-3xl p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-2xl font-black">{L.users}</h2><input className="input max-w-xs" placeholder={L.search} value={q} onChange={e=>setQ(e.target.value)}/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="text-left text-zinc-500"><tr><th className="p-3">{L.player}</th><th className="p-3">{L.role}</th><th className="p-3">{L.status}</th><th className="p-3">{L.balance}</th><th className="p-3">{L.locked}</th><th className="p-3">{L.style}</th><th className="p-3">{L.actions}</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t border-white/5"><td className="p-3"><b>{u.nickname}</b><div className="text-xs text-zinc-600">{u.email||"—"}</div></td><td className="p-3"><select disabled={d.me.level<5} value={u.role} onChange={e=>act({action:"userRole",userId:u.id,role:e.target.value})} className="rounded-lg border border-white/10 bg-black px-2 py-2">{["USER","SUPPORT","MODERATOR","ADMIN","SUPERADMIN"].map(x=><option key={x}>{x}</option>)}</select></td><td className="p-3"><select value={u.status} onChange={e=>act({action:"userStatus",userId:u.id,status:e.target.value})} className="rounded-lg border border-white/10 bg-black px-2 py-2">{["ACTIVE","SUSPENDED","BANNED","PENDING","DEACTIVATED"].map(x=><option key={x}>{x}</option>)}</select></td><td className="p-3 font-bold">${Number(u.balance).toFixed(2)}</td><td className="p-3">${Number(u.lockedBalance).toFixed(2)}</td><td className="p-3 text-xs">{u.themePreference==="STANDARD"?"STANDARD":"PERSONAL"}</td><td className="p-3"><div className="flex gap-2"><button disabled={!!busy} onClick={()=>{const a=prompt(L.operationCredit);if(a&&Number(a)>0)act({action:"walletAdjust",userId:u.id,amount:Number(a)})}} className="rounded-lg border border-pink-400/30 px-3 py-2 text-xs text-pink-300">{L.operationCredit}</button><button disabled={!!busy} onClick={()=>{const a=prompt(L.operationDebit);if(a&&Number(a)>0)act({action:"walletAdjust",userId:u.id,amount:-Number(a)})}} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-zinc-300">{L.operationDebit}</button></div></td></tr>)}</tbody></table></div></section>}
 {tab==="matches"&&<section className="panel mt-6 rounded-3xl p-6"><h2 className="text-2xl font-black">{L.matches}</h2><div className="mt-5 space-y-2">{d.matches.map(m=><div key={m.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white/[.03] p-4"><div><b>{m.playerOne.nickname}</b> <span className="text-pink-400">VS</span> <b>{m.playerTwo?.nickname||"—"}</b><div className="mt-1 text-xs text-zinc-500">{m.game.title} · {m.mapName} · ${Number(m.betAmount).toFixed(2)} · {m.status}</div></div>{["WAITING_FOR_PLAYERS","READY"].includes(m.status)&&<button onClick={()=>act({action:"cancelMatch",matchId:m.id})} className="rounded-xl border border-red-400/25 px-3 py-2 text-xs text-red-300">{L.cancel}</button>}</div>)}</div></section>}
 {tab==="finance"&&<section className="panel mt-6 rounded-3xl p-6"><h2 className="text-2xl font-black">{L.finance}</h2><div className="mt-5 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{d.transactions.map(x=><div key={x.id} className="rounded-2xl bg-white/[.03] p-4"><b>{x.wallet.user.nickname}</b><div className="text-xs text-zinc-500">{x.type} · {x.status}</div><div className="mt-2 font-black text-pink-400">${Number(x.amount).toFixed(2)}</div><div className="text-xs text-zinc-600">{x.description}</div></div>)}</div></section>}
 {tab==="security"&&<section className="panel mt-6 rounded-3xl p-6"><h2 className="text-2xl font-black">{L.security}</h2><div className="mt-5 grid gap-4 lg:grid-cols-2"><div><h3 className="font-bold">{L.fraudCases}</h3><div className="mt-3 space-y-2">{d.fraud.map(x=><div key={x.id} className="rounded-2xl bg-white/[.03] p-4"><b>{x.user.nickname}</b><span className="ml-2 text-pink-400">Risk {x.riskScore}</span><div className="text-xs text-zinc-500">{x.status} · {x.reason}</div></div>)}</div></div><div><h3 className="font-bold">{L.disputes}</h3><div className="mt-3 space-y-2">{d.disputes.map(x=><div key={x.id} className="rounded-2xl bg-white/[.03] p-4"><b>{x.reporter.nickname}</b><div className="text-xs text-zinc-500">{x.status} · {x.reason}</div></div>)}</div></div></div></section>}
 {tab==="support"&&<section className="panel mt-6 rounded-3xl p-6"><h2 className="text-2xl font-black">{L.support}</h2><div className="mt-5 space-y-2">{d.tickets.map(x=><div key={x.id} className="rounded-2xl bg-white/[.03] p-4"><div className="flex justify-between gap-3"><b>{x.subject}</b><span className="text-pink-400">{x.priority}</span></div><div className="mt-1 text-xs text-zinc-500">{x.user.nickname} · {x.status} · {x.category}</div></div>)}</div></section>}
 {tab==="settings"&&<section className="panel mt-6 rounded-3xl p-6"><h2 className="text-2xl font-black">{L.settings}</h2><div className="mt-6 rounded-3xl border border-white/8 bg-white/[.025] p-5"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><b>{L.standard}</b><p className="mt-1 text-sm text-zinc-500">{L.themeNote}</p></div><div className="flex items-center gap-2"><input type="color" value={d.standardAccent||"#ff2f91"} onChange={e=>act({action:"standardAccent",hex:e.target.value})} className="h-11 w-14 rounded-xl border border-white/10 bg-black p-1"/><select value={d.standardTheme} onChange={e=>act({action:"standardTheme",theme:e.target.value})} className="rounded-xl border border-white/10 bg-black px-4 py-3">{d.themes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div></div><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">{d.themes.map(x=><div key={x.id} className={`rounded-2xl border p-4 ${d.standardTheme===x.id?"border-pink-400/50":"border-white/8"}`}><div className="h-10 rounded-xl" style={{background:`linear-gradient(135deg,${x.preview[0]} 0%,${x.preview[0]} 45%,${x.preview[1]} 45%,${x.preview[1]} 70%,${x.preview[2]} 70%)`}}/><b className="mt-3 block">{x.name}</b><span className="text-xs text-zinc-500">{x.description}</span></div>)}</div></div></section>}
 </main></>}
