"use client";
import {useEffect,useState} from "react";
import Header from "@/components/Header/Header";
import CenterModal from "@/components/Common/CenterModal";
import {useLanguage} from "@/components/Common/LanguageContext";
const methods=[
 {id:"skins",title:"Скины CS2",sub:"Trade через Steam",img:"/payment-methods/skins.svg",steps:["Выберите скин","Откроется Steam Trade","Отправьте скин боту","Баланс пополнится автоматически"]},
 {id:"card",title:"Банковская карта",sub:"Visa / Mastercard",img:"/payment-methods/card.svg",steps:["Выберите сумму","Перейдите к защищённой оплате","Подтвердите платёж","Баланс пополнится автоматически"]},
 {id:"crypto",title:"Криптовалюта",sub:"USDT / BTC / ETH",img:"/payment-methods/crypto.svg",steps:["Выберите сеть и сумму","Получите адрес оплаты","Отправьте криптовалюту","Баланс пополнится автоматически"]},
 {id:"paypal",title:"PayPal",sub:"PayPal",img:"/payment-methods/paypal.svg",steps:["Выберите сумму","Перейдите в PayPal","Подтвердите платёж","Баланс пополнится автоматически"]},
 {id:"other",title:"Другие методы",sub:"Skrill / QIWI / WebMoney",img:"/payment-methods/other.svg",steps:["Выберите метод","Укажите сумму","Подтвердите оплату","Баланс пополнится автоматически"]},
];
export default function WalletPage(){const{t}=useLanguage();const[user,setUser]=useState<any>(null);const[txs,setTxs]=useState<any[]>([]);const[modal,setModal]=useState<"deposit"|"withdraw"|null>(null);const[method,setMethod]=useState(methods[0]);const[amount,setAmount]=useState("");
 async function load(){const r=await fetch("/api/auth/me",{cache:"no-store"});const d=await r.json();if(!d.user){location.href="/login";return}setUser(d.user);const tr=await fetch("/api/wallet/transactions",{cache:"no-store"});const td=await tr.json();setTxs(td.transactions??[])}useEffect(()=>{load()},[]);if(!user)return <><Header/><main className="pt-28 text-center text-zinc-500">{t.loading}</main></>;
 return <><Header/><main className="mx-auto min-h-screen max-w-6xl px-4 pb-20 pt-24 sm:px-6"><div className="grid gap-6 lg:grid-cols-[1fr_1.2fr]"><section className="panel rounded-3xl p-7"><span className="pill">USD WALLET</span><div className="mt-4 text-sm text-zinc-500">{t.availableBalance}</div><div className="mt-1 text-5xl font-black">${Number(user.balance).toFixed(2)}</div><div className="mt-2 text-sm text-zinc-500">{t.locked}: ${Number(user.lockedBalance||0).toFixed(2)}</div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button onClick={()=>{setAmount("");setModal("deposit")}} className="rounded-2xl bg-[var(--theme-accent)] p-5 text-left font-black text-black transition hover:brightness-110"><div className="text-xs uppercase">Пополнение</div><div className="mt-2 text-lg">Пополнить кошелёк</div><div className="mt-1 text-sm font-normal opacity-70">Карта, скины, крипто, PayPal и другие методы</div></button><button onClick={()=>{setAmount("");setModal("withdraw")}} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 text-left font-black transition hover:border-[var(--theme-accent)]/40"><div className="text-xs uppercase text-zinc-500">Вывод</div><div className="mt-2 text-lg">Вывести средства</div><div className="mt-1 text-sm font-normal text-zinc-500">Доступные способы вывода появятся здесь</div></button></div></section>
 <section className="panel rounded-3xl p-6"><div className="flex items-center justify-between"><div><span className="pill">PAYMENT CENTER</span><h2 className="mt-3 text-2xl font-black">Пополнение</h2></div><span className="text-sm text-zinc-500">USD</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{methods.map(m=><button key={m.id} onClick={()=>{setMethod(m);setModal("deposit")}} className="wallet-method flex items-center gap-3 rounded-2xl p-3 text-left"><img src={m.img} alt="" className="h-14 w-24 rounded-xl object-cover"/><span className="min-w-0"><b className="block truncate">{m.title}</b><span className="mt-1 block text-xs text-zinc-500">{m.sub}</span></span></button>)}</div><div className="mt-5 rounded-2xl border border-emerald-400/10 bg-emerald-400/[.03] p-4 text-sm text-emerald-300">Безопасно · Автоматически · Мгновенно</div></section></div>
 <section className="panel mt-6 rounded-3xl p-7"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">{t.transactions}</h2><span className="text-sm text-zinc-500">История операций</span></div><div className="mt-5 space-y-2">{txs.length?txs.map(tx=><div key={tx.id} className="flex items-center justify-between gap-4 rounded-2xl border border-white/5 bg-white/[.025] p-4"><div className="min-w-0"><b>{t.transactionTypes[tx.type as keyof typeof t.transactionTypes]??tx.type}</b><div className="mt-1 text-sm text-zinc-400">{tx.description}</div><div className="mt-1 text-[11px] text-zinc-600">{new Date(tx.createdAt).toLocaleString()}</div></div><span className={Number(tx.amount)>=0?"shrink-0 text-emerald-300":"shrink-0 text-red-300"}>{Number(tx.amount)>=0?"+":""}${Number(tx.amount).toFixed(2)}</span></div>):<p className="text-zinc-500">{t.noTransactions}</p>}</div></section></main>
 <CenterModal open={Boolean(modal)} title={modal==="withdraw"?"Вывод средств":method.title} onClose={()=>setModal(null)}><div className="rounded-2xl border border-[var(--theme-accent)]/15 bg-[var(--theme-accent-bg)] p-4"><div className="flex items-center gap-3"><img src={modal==="withdraw"?"/branding/duelplay-wolf.png":method.img} className="h-12 w-20 rounded-xl object-cover" alt=""/><div><b>{modal==="withdraw"?"Доступный баланс":method.title}</b><div className="mt-1 text-xs text-zinc-500">${Number(user.balance).toFixed(2)} доступно</div></div></div></div>{modal==="deposit"&&<div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{method.steps.map((x,i)=><div key={x} className="rounded-xl border border-white/5 bg-white/[.025] p-3 text-center"><span className="step-circle active mx-auto">{i+1}</span><div className="mt-2 text-xs leading-5 text-zinc-400">{x}</div></div>)}</div>}<label className="mt-5 block"><span className="mb-2 block text-xs uppercase tracking-wider text-zinc-500">Сумма, USD</span><input autoFocus className="input" type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="50.00"/></label><div className="mt-4 rounded-2xl border border-white/5 bg-white/[.025] p-4 text-sm text-zinc-400">{modal==="deposit"?"Платёжная интеграция подключается к выбранному провайдеру. После подтверждения провайдера операция будет отражена в транзакциях.":"Запрос на вывод проходит проверку и после подтверждения отображается в истории операций."}</div><button disabled={!(Number(amount)>0)} className="mt-5 w-full rounded-2xl bg-[var(--theme-accent)] py-4 font-black text-black disabled:opacity-40">{modal==="deposit"?"Продолжить пополнение":"Создать запрос на вывод"}</button></CenterModal></>}
