"use client";
import{useEffect,useState}from"react";
import Link from"next/link";
type N={id:string;type:string;status:string;title:string;body:string;createdAt:string;readAt:string|null};
export default function NotificationsPage(){const[data,setData]=useState<{notifications:N[];unread:number}>({notifications:[],unread:0});const[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/notifications',{cache:'no-store'});const x=await r.json();if(r.ok)setData({notifications:Array.isArray(x.notifications)?x.notifications:[],unread:Number(x.unread||0)})}
 useEffect(()=>{let disposed=false;let loading=false;const refresh=async()=>{if(disposed||document.visibilityState==="hidden"||loading)return;loading=true;try{await load()}finally{loading=false}};void refresh();const timer=window.setInterval(()=>void refresh(),10000);const onVisibility=()=>{if(document.visibilityState==="visible")void refresh()};document.addEventListener("visibilitychange",onVisibility);return()=>{disposed=true;window.clearInterval(timer);document.removeEventListener("visibilitychange",onVisibility)}},[]);
 async function read(id?:string){setBusy(true);await fetch('/api/notifications',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(id?{id}:{all:true})});await load();setBusy(false)}
 return <main className="mx-auto min-h-screen max-w-4xl px-4 pb-20 pt-28"><section className="panel rounded-3xl p-6 sm:p-9"><div className="flex items-start justify-between gap-4"><div><span className="pill">NOTIFICATIONS</span><h1 className="mt-4 text-4xl font-black">Notifications {data.unread>0&&<span className="text-pink-400">· {data.unread}</span>}</h1><p className="mt-2 text-zinc-500">Friend requests, duel invitations and important account events.</p></div>{data.unread>0&&<button disabled={busy} onClick={()=>read()} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold">Mark all read</button>}</div><div className="mt-7 space-y-3">{data.notifications.length?data.notifications.map(n=><article key={n.id} className={`rounded-2xl border p-4 ${n.status==='UNREAD'?'border-pink-400/20 bg-pink-400/[.04]':'border-white/5 bg-white/[.02]'}`}><div className="flex items-start justify-between gap-4"><div><div className="text-xs uppercase tracking-widest text-zinc-600">{n.type}</div><h2 className="mt-1 font-black">{n.title}</h2><p className="mt-1 text-sm text-zinc-400">{n.body}</p><time className="mt-2 block text-xs text-zinc-600">{new Date(n.createdAt).toLocaleString()}</time></div>{n.status==='UNREAD'&&<button disabled={busy} onClick={()=>read(n.id)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Read</button>}</div></article>):<div className="rounded-2xl border border-white/5 p-10 text-center text-zinc-500">No notifications yet.</div>}</div><Link href="/social" className="mt-6 inline-block text-sm text-pink-400">← Social Center</Link></section></main>}
