"use client";
import { useEffect, useState } from "react";
import { createMatch } from "@/lib/api/matches";
import { useLanguage } from "../Common/LanguageContext";
const maps=["Mirage","Dust2","Ancient","Train","Overpass","Inferno","Nuke","Anubis"]; const bets=[3,5,10,25,50,100,250,500,1000];
export default function CreateMatch({onCreated}:{onCreated?:()=>void}){const{t}=useLanguage();const[bet,setBet]=useState("3");const[custom,setCustom]=useState("");const[map,setMap]=useState("Mirage");const[busy,setBusy]=useState(false);const[msg,setMsg]=useState("");const[balance,setBalance]=useState<number|null>(null);
useEffect(()=>{fetch("/api/auth/me",{cache:"no-store"}).then(r=>r.json()).then(d=>setBalance(d.user?Number(d.user.balance):null)).catch(()=>{});const fn=(e:Event)=>{const name=(e as CustomEvent<string>).detail;if(maps.includes(name))setMap(name)};window.addEventListener("duelplay:select-map",fn);return()=>window.removeEventListener("duelplay:select-map",fn)},[]);
const amount=bet==="custom"?Number(custom):Number(bet);const valid=Number.isFinite(amount)&&amount>=3&&amount<=10000;const fee=amount*2*.10;const winner=amount*2-fee;
async function submit(){if(!valid||busy)return;setBusy(true);setMsg("");try{await createMatch({mode:"SOLO_1V1",mapName:map,betAmount:amount});setBalance(v=>v===null?null:v-amount);setMsg(t.created);onCreated?.()}catch(e){setMsg(e instanceof Error?e.message:"Не удалось создать матч")}finally{setBusy(false)}}
return <section id="create" className="border-y border-white/5 bg-[#0a0d12] px-4 py-20 sm:px-6"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_460px] lg:items-center"><div><span className="pill">{t.matchmaking}</span><h2 className="mt-5 text-4xl font-black tracking-tight sm:text-5xl">{t.createTitle}<br/><span className="text-pink-400">{t.createTitle2}</span></h2><p className="mt-5 max-w-xl text-zinc-400">{t.createText}</p><div className="mt-8 grid max-w-xl grid-cols-3 gap-3">{[["1v1",t.format],["10%",t.commission],["$3",t.minBet]].map(([a,b])=><div key={b} className="panel p-4"><div className="text-xl font-bold">{a}</div><div className="mt-1 text-xs text-zinc-500">{b}</div></div>)}</div></div><div className="panel rounded-3xl p-6 sm:p-7"><div className="mb-6 flex items-center justify-between"><div><h3 className="text-xl font-bold">{t.newMatch}</h3><p className="text-sm text-zinc-500">Counter-Strike 2 · 1 vs 1 · USD</p></div><span className="status waiting">{t.open}</span></div>{balance!==null&&<div className="mb-4 rounded-xl bg-white/[.03] px-4 py-3 text-sm text-zinc-400">{t.balance} <b className="text-white">${balance.toFixed(2)}</b> · <a className="text-pink-400" href="/wallet">{t.deposit}</a></div>}<div className="space-y-4"><Field label={t.bet}><select value={bet} onChange={e=>setBet(e.target.value)} className="input">{bets.map(v=><option key={v} value={v}>${v.toFixed(2)}</option>)}<option value="custom">Custom amount</option></select>{bet==="custom"&&<input className="input mt-3" type="number" min="3" max="10000" step="0.01" value={custom} onChange={e=>setCustom(e.target.value)} placeholder="$3 — $10 000"/>}</Field><Field label={t.map}><select value={map} onChange={e=>setMap(e.target.value)} className="input">{maps.map(m=><option key={m}>{m}</option>)}</select></Field></div><div className="mt-5 rounded-2xl border border-pink-400/10 bg-pink-400/5 p-4 text-sm"><div className="flex justify-between text-zinc-400"><span>{t.feeFromPot}</span><span>10% · ${fee.toFixed(2)}</span></div><div className="mt-2 flex justify-between font-semibold"><span>{t.winnerGets}</span><span className="text-pink-400">${winner.toFixed(2)}</span></div></div>{msg&&<div className="mt-4 rounded-xl border border-white/10 bg-white/[.03] p-3 text-sm text-pink-300">{msg}</div>}<button onClick={submit} disabled={!valid||busy} className="mt-5 w-full rounded-2xl bg-pink-400 py-4 font-black text-black transition hover:bg-pink-300 disabled:cursor-not-allowed disabled:opacity-40">{busy?t.creating:t.create}</button>{balance===null&&<p className="mt-3 text-center text-xs text-zinc-600"><a href="/login" className="text-pink-400">{t.goLogin}</a>, {t.loginToCreate.toLowerCase()}</p>}</div></div></section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-zinc-500">{label}</span>{children}</label>}
