"use client";
import {useEffect,useRef,useState} from "react";
import {useLanguage} from "@/components/Common/LanguageContext";
const FALLBACK="/avatars/premium/01-cyan.svg";
const DEFAULTS=[
 {id:"cyan",name:"Cyan",src:"/avatars/premium/01-cyan.svg"},{id:"violet",name:"Violet",src:"/avatars/premium/02-violet.svg"},{id:"red",name:"Red",src:"/avatars/premium/03-red.svg"},{id:"amber",name:"Amber",src:"/avatars/premium/04-amber.svg"},{id:"emerald",name:"Emerald",src:"/avatars/premium/05-emerald.svg"},{id:"blue",name:"Blue",src:"/avatars/premium/06-blue.svg"},{id:"pink",name:"Pink",src:"/avatars/premium/07-pink.svg"},{id:"orange",name:"Orange",src:"/avatars/premium/08-orange.svg"}
];
export default function AvatarPicker({value,steamAvatarUrl,nickname,onSaved}:{value:string|null;steamAvatarUrl:string|null;nickname:string;onSaved:(url:string|null)=>void}){
 const{t}=useLanguage();const inputRef=useRef<HTMLInputElement|null>(null);const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[presets,setPresets]=useState(DEFAULTS.map(x=>({id:x.id,name:x.name,imageData:x.src})));
 useEffect(()=>{fetch("/api/avatar-presets",{cache:"no-store"}).then(r=>r.json()).then(d=>{if(Array.isArray(d.presets)&&d.presets.length)setPresets([...DEFAULTS.map(x=>({id:x.id,name:x.name,imageData:x.src})),...d.presets] )}).catch(()=>{})},[]);
 async function saveAvatar(url:string|null){setSaving(true);setMessage("");try{const res=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({avatarUrl:url})});const data=await res.json();if(!res.ok)throw new Error(data.error||t.avatarSaveError);onSaved(data.user.avatarUrl);setOpen(false);setMessage(url===null?t.useSteamAvatar:t.avatarSaved)}catch(e){setMessage(e instanceof Error?e.message:t.avatarSaveError)}finally{setSaving(false)}}
 async function upload(file:File){if(!file.type.startsWith("image/")){setMessage(t.avatarImageOnly);return}if(file.size>5*1024*1024){setMessage(t.avatarTooLarge);return}const image=new Image();const reader=new FileReader();reader.onload=()=>{image.onload=()=>{const size=512;const canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d");if(!ctx)return;const scale=Math.max(size/image.width,size/image.height);const w=image.width*scale,h=image.height*scale;ctx.drawImage(image,(size-w)/2,(size-h)/2,w,h);saveAvatar(canvas.toDataURL("image/jpeg",.9))};image.src=String(reader.result)};reader.readAsDataURL(file)}
 const src=value||steamAvatarUrl||FALLBACK;
 return <div className="relative"><button type="button" onClick={()=>setOpen(v=>!v)} className="group relative aspect-square h-24 w-24 overflow-hidden rounded-3xl border border-white/15 bg-black transition hover:border-[var(--theme-accent)]/60" aria-label={t.changeAvatar}><img src={src} alt={nickname} className="avatar-square" onError={e=>{e.currentTarget.src=FALLBACK}}/><span className="absolute inset-x-0 bottom-0 bg-black/75 py-1 text-[10px] font-bold text-white opacity-0 transition group-hover:opacity-100">{t.changeAvatar}</span></button>{open&&<><button type="button" aria-label="Close" onClick={()=>setOpen(false)} className="fixed inset-0 z-20 bg-black/20"/><div className="absolute left-0 top-28 z-30 w-[350px] max-w-[calc(100vw-2rem)] rounded-2xl border border-white/10 bg-[#0b0d12] p-4 shadow-2xl"><button type="button" onClick={()=>setOpen(false)} className="absolute right-3 top-3 grid h-8 w-8 place-items-center rounded-lg border border-white/10 text-lg text-zinc-400">×</button><div className="mb-3 pr-10 text-sm font-bold">{t.chooseAvatar}</div><div className="grid max-h-64 grid-cols-4 gap-2 overflow-auto">{presets.map(p=><button key={p.id} type="button" disabled={saving} onClick={()=>saveAvatar(p.imageData)} className="avatar-preset aspect-square overflow-hidden rounded-xl border border-white/10 bg-black hover:border-[var(--theme-accent)]/70"><img src={p.imageData} alt={p.name} className="avatar-square"/></button>)}</div><button type="button" disabled={saving||!steamAvatarUrl||value===null} onClick={()=>saveAvatar(null)} className="mt-3 w-full rounded-xl border border-white/10 px-4 py-3 text-sm font-bold hover:border-[var(--theme-accent)]/40">{t.useSteamAvatar}</button><button type="button" disabled={saving} onClick={()=>inputRef.current?.click()} className="mt-2 w-full rounded-xl bg-[var(--theme-accent)] px-4 py-3 text-sm font-black text-black">{saving?t.saving:t.uploadAvatar}</button><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)upload(f);e.currentTarget.value=""}}/>{message&&<p className="mt-2 text-xs text-[var(--theme-accent)]">{message}</p>}<p className="mt-2 text-[11px] text-zinc-500">{t.avatarHint}</p></div></>}</div>
}
