"use client";
import { useState } from "react";
import { useLanguage } from "../Common/LanguageContext";
import { useRouter } from "next/navigation";
import { DUEL_MODES, type DuelModeId } from "@/lib/duel-modes";

const maps = ["ALL", "Mirage", "Dust2", "Ancient", "Train", "Overpass", "Inferno", "Nuke", "Anubis"];
const stakes = [3, 5, 10, 25, 50, 100];
type Candidate = { id:string; nickname:string; mapName:string|null; betAmount:number; rating:number; ratingDifference:number };

export default function MatchmakingPanel(){
 const {t}=useLanguage(); const router=useRouter();
 const [stake,setStake]=useState("3"),[mapName,setMapName]=useState("ALL"),[ratingWindow,setRatingWindow]=useState("200"),[mode,setMode]=useState<DuelModeId>("SOLO_1V1"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[candidates,setCandidates]=useState<Candidate[]>([]);
 const text=t.matchmaking;
 async function joinCandidate(id:string){setBusy(true);setMessage("");try{const r=await fetch(`/api/matches/${id}/join`,{method:"POST"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to join match");router.push(`/matches/${id}`)}catch(error){setMessage(error instanceof Error?error.message:"Unable to join match");await search()}finally{setBusy(false)}}
 async function search(){setBusy(true);setMessage("");setCandidates([]);try{const response=await fetch("/api/matchmaking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,stake:Number(stake),ratingWindow:Number(ratingWindow),...(mapName!=="ALL"?{mapName}: {})})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Matchmaking failed");if(data.joined&&data.match?.id){router.push(`/matches/${data.match.id}`);return;}setCandidates(Array.isArray(data.candidates)?data.candidates:[]);setMessage(data.candidates?.length?text.found:text.none);}catch(error){setMessage(error instanceof Error?error.message:"Matchmaking failed")}finally{setBusy(false)}}
 return <section className="mx-auto max-w-7xl px-4 pt-20 sm:px-6"><div className="panel overflow-hidden rounded-3xl border border-pink-400/10 bg-pink-400/[.025] p-6 sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="max-w-2xl"><span className="pill">MATCHMAKING · 1V1</span><h1 className="mt-4 text-3xl font-black sm:text-4xl">{text.title}</h1><p className="mt-2 text-sm leading-6 text-zinc-500">{text.subtitle}</p></div><div className="grid w-full min-w-0 gap-3 sm:grid-cols-2 lg:flex-1 lg:max-w-[760px] lg:grid-cols-5"><label className="text-xs font-bold text-zinc-500">{text.mode}<select className="input mt-1" value={mode} onChange={e=>setMode(e.target.value as DuelModeId)}>{DUEL_MODES.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label className="text-xs font-bold text-zinc-500">{text.stake}<select className="input mt-1" value={stake} onChange={e=>setStake(e.target.value)}>{stakes.map(x=><option key={x} value={x}>${x}</option>)}</select></label><label className="text-xs font-bold text-zinc-500">{text.map}<select className="input mt-1" value={mapName} onChange={e=>setMapName(e.target.value)}>{maps.map(x=><option key={x} value={x}>{x==="ALL"?text.anyMap:x}</option>)}</select></label><label className="text-xs font-bold text-zinc-500">{text.rating}<select className="input mt-1" value={ratingWindow} onChange={e=>setRatingWindow(e.target.value)}><option value="100">±100</option><option value="200">±200</option><option value="300">±300</option><option value="500">±500</option></select></label><button onClick={search} disabled={busy} className="w-full self-end rounded-xl bg-pink-400 sm:w-auto px-5 py-3 font-black text-black transition hover:bg-pink-300 disabled:opacity-40">{busy?text.searching:text.search}</button></div></div>{message&&<p className="mt-5 text-sm text-pink-300">{message}</p>}{candidates.length>0&&<div className="mt-5 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{candidates.map(c=><div key={c.id} className="flex items-center justify-between rounded-2xl border border-white/5 bg-black/20 p-4"><div><b>{c.nickname}</b><div className="mt-1 text-xs text-zinc-500">{c.mapName||text.anyMap} · ${c.betAmount.toFixed(2)} · {text.diff} {c.ratingDifference}</div></div><button onClick={()=>joinCandidate(c.id)} disabled={busy} className="rounded-lg border border-pink-400/20 px-3 py-2 text-xs font-bold text-pink-300">{text.open}</button></div>)}</div>}</div></section>
}
