"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import AvatarPicker from "@/components/Profile/AvatarPicker";
import { useLanguage } from "@/components/Common/LanguageContext";
import { useTheme } from "@/components/Common/ThemeProvider";
import { THEMES, ThemeId } from "@/lib/themes";
import { getDuelMap } from "@/lib/duel-maps";

type User={id:string;nickname:string;steamId:string|null;email:string|null;avatarUrl:string|null;steamAvatarUrl:string|null;themePreference:string;profileVisibility:string;showStatsPublic:boolean;allowChallenges:boolean;allowMessages:boolean;level:number;xp:number;reputation:number;trustScore:string;referralCode:string;balance:string;lockedBalance:string};
type Data={referralLink:string;user:User;stats:{matches:number;wins:number;losses:number;active:number;winRate:number;referralCount:number;referralEarned:number};profileCompletion:number;profileCompletionProgress:{completed:number;total:number;rewardUnlocked:boolean;friends:number;finishedMatches:number;achievements:number;hasCustomAvatar:boolean};matches:any[];achievements:any[]};


export default function ProfilePage(){
 const {t,language}=useLanguage(); const {theme,setTheme}=useTheme(); const [data,setData]=useState<Data|null>(null); const [error,setError]=useState(""); const [authRequired,setAuthRequired]=useState(false); const [copied,setCopied]=useState(false); const [editingNickname,setEditingNickname]=useState(false); const [nicknameDraft,setNicknameDraft]=useState(""); const [nicknameBusy,setNicknameBusy]=useState(false); const [nicknameMessage,setNicknameMessage]=useState("");
 async function loadProfile(){const r=await fetch("/api/profile",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.status===401){setAuthRequired(true);return}if(!r.ok){setError(t.profileLoadError);return}setData(d)}
 useEffect(()=>{
  void loadProfile();
  const refresh=()=>{if(document.visibilityState!=="hidden")void loadProfile()};
  const onWalletUpdated=()=>{void loadProfile()};
  const onProfileUpdated=()=>{void loadProfile()};
  const timer=window.setInterval(refresh,10000);
  window.addEventListener("duelplay:wallet-updated",onWalletUpdated);
  window.addEventListener("duelplay:profile-updated",onProfileUpdated);
  document.addEventListener("visibilitychange",refresh);
  return()=>{window.clearInterval(timer);window.removeEventListener("duelplay:wallet-updated",onWalletUpdated);window.removeEventListener("duelplay:profile-updated",onProfileUpdated);document.removeEventListener("visibilitychange",refresh)}
},[t.profileLoadError]);
 if(authRequired)return <><main className="mx-auto min-h-screen max-w-xl px-4 pb-20 pt-28"><section className="panel rounded-3xl p-8 text-center sm:p-10"><span className="pill">DUELPLAY</span><h1 className="mt-4 text-3xl font-black">{t.profile}</h1><p className="mt-3 text-zinc-500">{t.profileLoginRequired}</p><a href="/login" className="mt-6 inline-flex rounded-2xl bg-pink-400 px-6 py-3 font-black text-black hover:bg-pink-300">{t.goLogin}</a></section></main></>;
 if(!data)return <><main className="min-h-screen pt-28 text-center text-zinc-500">{error||t.loading}</main></>;
 const u=data.user; const nicknameCopy=({RU:{edit:"Изменить никнейм",save:"Сохранить",cancel:"Отмена",placeholder:"Новый никнейм",hint:"3–20 символов: латиница, цифры и _",invalid:"Никнейм должен содержать 3–20 символов: латиница, цифры и _",taken:"Этот никнейм уже занят"},UA:{edit:"Змінити нікнейм",save:"Зберегти",cancel:"Скасувати",placeholder:"Новий нікнейм",hint:"3–20 символів: латиниця, цифри та _",invalid:"Нікнейм має містити 3–20 символів: латиниця, цифри та _",taken:"Цей нікнейм вже зайнятий"},EN:{edit:"Change nickname",save:"Save",cancel:"Cancel",placeholder:"New nickname",hint:"3–20 characters: letters, numbers and _",invalid:"Nickname must be 3–20 characters using letters, numbers and _",taken:"This nickname is already taken"},PL:{edit:"Zmień nick",save:"Zapisz",cancel:"Anuluj",placeholder:"Nowy nick",hint:"3–20 znaków: litery, cyfry i _",invalid:"Nick musi mieć 3–20 znaków: litery, cyfry i _",taken:"Ten nick jest już zajęty"}} as any)[language]||({edit:"Change nickname",save:"Save",cancel:"Cancel",placeholder:"New nickname",hint:"3–20 characters: letters, numbers and _",invalid:"Nickname must be 3–20 characters using letters, numbers and _",taken:"This nickname is already taken"});
 const referralCopyLabel=({RU:"Скопировать ссылку",UA:"Копіювати посилання",EN:"Copy link",PL:"Kopiuj link"} as any)[language]||"Copy link";
 async function saveNickname(){const nickname=nicknameDraft.trim();if(!/^[A-Za-z0-9_]{3,20}$/.test(nickname)){setNicknameMessage(nicknameCopy.invalid);return}setNicknameBusy(true);setNicknameMessage("");try{const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({nickname})});const x=await r.json().catch(()=>({}));if(!r.ok){setNicknameMessage(x.error==="Этот никнейм уже занят"||x.error==="This nickname is already taken"?nicknameCopy.taken:x.error||nicknameCopy.invalid);return}setData(prev=>prev?{...prev,user:{...prev.user,nickname:x.user?.nickname??nickname}}:prev);setEditingNickname(false);setNicknameMessage("");}finally{setNicknameBusy(false)}}
 const referralLink = data.referralLink;
 async function copy(value:string){await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1200)}
 const completionCopy=({
  RU:{title:"Заполнение профиля",subtitle:"Заполни профиль до 100% и разблокируй эксклюзивную аватарку.",avatar:"Выбрать аватар",friends:"Добавить 3 друзей",match:"Сыграть первый матч",achievement:"Получить первое достижение",reward:"🎁 Награда разблокирована — эксклюзивная аватарка DuelPlay Complete"},
  UA:{title:"Заповнення профілю",subtitle:"Заповни профіль до 100% та розблокуй ексклюзивну аватарку.",avatar:"Обрати аватар",friends:"Додати 3 друзів",match:"Зіграти перший матч",achievement:"Отримати перше досягнення",reward:"🎁 Нагороду розблоковано — ексклюзивна аватарка DuelPlay Complete"},
  PL:{title:"Uzupełnienie profilu",subtitle:"Uzupełnij profil do 100% i odblokuj ekskluzywnego awatara.",avatar:"Wybierz awatar",friends:"Dodaj 3 znajomych",match:"Zagraj pierwszy mecz",achievement:"Zdobądź pierwsze osiągnięcie",reward:"🎁 Nagroda odblokowana — ekskluzywny awatar DuelPlay Complete"},
  EN:{title:"Profile completion",subtitle:"Complete your profile to 100% and unlock an exclusive avatar.",avatar:"Choose an avatar",friends:"Add 3 friends",match:"Play your first match",achievement:"Earn your first achievement",reward:"🎁 Reward unlocked — exclusive DuelPlay Complete avatar"},
 } as const)[language] || ({title:"Profile completion",subtitle:"Complete your profile to 100% and unlock an exclusive avatar.",avatar:"Choose an avatar",friends:"Add 3 friends",match:"Play your first match",achievement:"Earn your first achievement",reward:"🎁 Reward unlocked — exclusive DuelPlay Complete avatar"} as const);
 async function privacy(patch:Record<string,unknown>){const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});const x=await r.json().catch(()=>({}));if(r.ok&&x.user)setData(prev=>prev?{...prev,referralLink:x.referralLink??prev.referralLink??"",stats:prev.stats,user:{...prev.user,...x.user}}:prev)}
 return <><main className="mx-auto min-h-screen max-w-6xl px-4 pb-20 pt-28">
  <div className="panel rounded-3xl p-7 sm:p-10">
   <div className="flex flex-col gap-7 lg:flex-row lg:items-start lg:justify-between">
    <div className="flex items-center gap-5"><AvatarPicker value={u.avatarUrl} steamAvatarUrl={u.steamAvatarUrl} nickname={u.nickname} onSaved={avatarUrl=>{setData(prev=>prev?{...prev,user:{...prev.user,avatarUrl}}:prev);window.dispatchEvent(new Event("duelplay:profile-updated"));void loadProfile()}}/><div><span className="pill">{t.playerProfile}</span><div className="mt-3 flex flex-wrap items-center gap-3"><h1 data-player-name className="text-4xl font-black">{u.nickname}</h1><button type="button" onClick={()=>{setNicknameDraft(u.nickname);setNicknameMessage("");setEditingNickname(v=>!v)}} className="rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-zinc-300 hover:border-pink-400/40 hover:text-pink-200">{nicknameCopy.edit}</button></div><p className="mt-2 text-zinc-500">{t.steamId}: {u.steamId||"—"}</p><p className="mt-2 text-xs text-zinc-600">{t.avatarHintShort}</p>{editingNickname&&<div className="mt-3 w-full max-w-md rounded-2xl border border-white/8 bg-white/[.025] p-3"><input value={nicknameDraft} onChange={e=>setNicknameDraft(e.target.value)} maxLength={20} className="input w-full" placeholder={nicknameCopy.placeholder} autoFocus/><p className="mt-2 text-xs text-zinc-600">{nicknameCopy.hint}</p><div className="mt-3 flex gap-2"><button type="button" disabled={nicknameBusy} onClick={saveNickname} className="rounded-xl bg-pink-400 px-4 py-2 text-sm font-black text-black">{nicknameBusy?"…":nicknameCopy.save}</button><button type="button" disabled={nicknameBusy} onClick={()=>{setEditingNickname(false);setNicknameMessage("")}} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold">{nicknameCopy.cancel}</button></div>{nicknameMessage&&<p className="mt-2 text-xs text-pink-300">{nicknameMessage}</p>}</div>}</div></div>
    <div className="flex gap-3"><Link href="/wallet" className="rounded-2xl bg-pink-400 px-5 py-3 font-black text-black">{t.wallet} · ${Number(u.balance).toFixed(2)}</Link><Link prefetch href="/create" className="rounded-2xl border border-white/10 px-5 py-3 font-bold">{t.createMatch}</Link></div>
   </div>
   <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Stat n={String(data.stats.matches)} t={t.matchesCount}/><Stat n={String(data.stats.wins)} t={t.wins}/><Stat n={String(data.stats.losses)} t={t.losses}/><Stat n={`${data.stats.winRate}%`} t={t.winRate}/><Stat n={String(u.level)} t={`${t.level} · ${u.xp} ${t.xp}`}/><Stat n={String(data.achievements?.length??0)} t={t.hubCards.achievements}/></div>
  </div>
  <section className="panel mt-6 rounded-3xl p-6 sm:p-7">
   <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><span className="pill">{completionCopy.title}</span><h2 className="mt-3 text-2xl font-black">{Math.round(data.profileCompletion)}%</h2><p className="mt-1 text-sm text-zinc-500">{completionCopy.subtitle}</p></div><span className="text-xs font-bold text-zinc-500">{data.profileCompletionProgress.completed}/{data.profileCompletionProgress.total}</span></div>
   <div className="mt-4 h-3 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-pink-400 transition-all" style={{width:`${Math.min(100,Math.max(0,Number(data.profileCompletion||0)))}%`}}/></div>
   <div className="mt-5 grid gap-2 sm:grid-cols-2">
    <ProgressRow done={data.profileCompletionProgress.hasCustomAvatar} label={completionCopy.avatar}/>
    <ProgressRow done={data.profileCompletionProgress.friends>=3} label={completionCopy.friends}/>
    <ProgressRow done={data.profileCompletionProgress.finishedMatches>=1} label={completionCopy.match}/>
    <ProgressRow done={data.profileCompletionProgress.achievements>=1} label={completionCopy.achievement}/>
   </div>
   {data.profileCompletionProgress.rewardUnlocked&&<div className="mt-4 rounded-2xl border border-pink-400/20 bg-pink-400/[.06] p-4 text-sm font-bold text-pink-200">{completionCopy.reward}</div>}
  </section>
  <nav aria-label="Profile sections" className="panel mt-6 rounded-3xl p-3 sm:p-4"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-6">{[
    [`${t.profile}`,"/profile"],[`📊 ${t.hubCards.analytics}`,"/analytics"],[`⚔ ${t.matches}`,"/matches"],[`🏆 ${t.hubCards.achievements}`,"/achievements"],[`🎒 ${t.hubCards.inventory}`,"/inventory"],[`💎 ${t.hubCards.collections}`,"/collections"],[`👥 ${t.hubCards.social}`,"/social"],[`🛡 ${t.hubCards.clans}`,"/clans"],[`🎟 ${t.hubCards.duelPass}`,"/duelpass"],[`👑 ${t.hubCards.prime}`,"/prime"],[`💳 ${t.wallet}`,"/wallet"]
  ].map(([label,href])=><a key={href} href={href} className="flex min-h-11 items-center justify-center rounded-xl border border-white/8 bg-white/[.025] px-3 py-2 text-center text-sm font-bold text-zinc-300 transition hover:border-pink-400/30 hover:text-white">{label}</a>)}</div></nav>
  <section className="panel mt-6 rounded-3xl p-5 sm:p-6">
   <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><span className="pill">STYLE</span><h2 className="mt-3 text-2xl font-black">{t.themeStyle}</h2><p className="mt-2 max-w-3xl text-sm text-zinc-500">{t.themeDescription}</p></div><span className="text-xs font-bold text-zinc-500">{theme==="STANDARD"?t.themeStandard:t.themePersonal}</span></div>
   <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">
    {THEMES.map(x=><button type="button" key={x.id} onClick={()=>setTheme(x.id as ThemeId)} className={`group overflow-hidden rounded-xl border text-left transition hover:-translate-y-0.5 ${theme===x.id?"border-pink-400/70 bg-pink-400/[.08]":"border-white/8 bg-white/[.025] hover:border-white/20"}`}>
      <div className="h-12 w-full" style={{background:`linear-gradient(135deg,${x.preview[0]} 0%,${x.preview[0]} 45%,${x.preview[1]} 45%,${x.preview[1]} 70%,${x.preview[2]} 70%)`}}/>
      <div className="p-3"><div className="text-sm font-bold">{x.name}</div><div className="mt-1 truncate text-[11px] text-zinc-500">{x.description}</div></div>
    </button>)}
   </div>
  </section>

  <section className="panel mt-6 rounded-3xl p-7"><div><span className="pill">PRIVACY</span><h2 className="mt-3 text-2xl font-black">{t.privacyTitle}</h2><p className="mt-2 text-sm text-zinc-500">{t.privacyDescription}</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><span className="text-sm font-bold">{t.profileVisibility}</span><select value={u.profileVisibility} onChange={e=>privacy({profileVisibility:e.target.value})} className="input mt-3"><option value="PUBLIC">{t.visibilityEveryone}</option><option value="FRIENDS">{t.visibilityFriends}</option><option value="PRIVATE">{t.visibilityPrivate}</option></select></label><Toggle label={t.showPublicStats} value={u.showStatsPublic} onChange={v=>privacy({showStatsPublic:v})}/><Toggle label={t.acceptChallenges} value={u.allowChallenges} onChange={v=>privacy({allowChallenges:v})}/><Toggle label={t.acceptMessages} value={u.allowMessages} onChange={v=>privacy({allowMessages:v})}/></div></section>
  <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.5fr]">
   <section className="panel rounded-3xl p-7"><h2 className="text-2xl font-black">{t.profile}</h2><div className="mt-5 space-y-3"><Row label={t.reputation} value={u.reputation}/><Row label={t.trust} value={`${Number(u.trustScore).toFixed(0)}%`}/><Row label={t.balance} value={`$${Number(u.balance).toFixed(2)}`}/><Row label={t.locked} value={`$${Number(u.lockedBalance).toFixed(2)}`}/></div><div className="mt-6 rounded-2xl border border-pink-400/10 bg-pink-400/[.035] p-4"><div className="text-xs uppercase tracking-wider text-pink-300">{t.referralTitle}</div><p className="mt-2 text-xs leading-5 text-zinc-500">{t.referralDescription}</p><div className="mt-3 flex gap-2"><input readOnly value={u.referralCode} className="input"/><button onClick={()=>copy(u.referralCode)} className="cursor-pointer rounded-xl border border-white/10 px-4 text-sm font-bold transition hover:border-pink-400/40 hover:bg-pink-400/5 hover:text-pink-200">{copied?t.copied:t.copy}</button></div><div className="mt-2 flex gap-2"><input readOnly value={referralLink} className="input text-xs"/><button onClick={()=>copy(referralLink)} className="cursor-pointer rounded-xl border border-white/10 px-4 text-sm font-bold transition hover:border-pink-400/40 hover:bg-pink-400/5">{referralCopyLabel}</button></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-black/20 p-3"><div className="text-[11px] text-zinc-600">{t.referralInvited}</div><b className="mt-1 block">{data.stats.referralCount}</b></div><div className="rounded-xl bg-black/20 p-3"><div className="text-[11px] text-zinc-600">{t.referralEarned}</div><b className="mt-1 block text-pink-400">${data.stats.referralEarned.toFixed(4)}</b></div></div><p className="mt-3 text-[11px] text-zinc-600">{t.referralReward}</p></div></section>
   <section className="panel rounded-3xl p-7"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">{t.recentMatches}</h2><Link href="/live" className="text-sm text-pink-400">LIVE →</Link></div><div className="mt-5 space-y-3">{data.matches.slice(0,5).length?data.matches.slice(0,5).map(m=><Link href={`/matches/${m.id}`} key={m.id} className="group flex items-center gap-3 rounded-2xl bg-white/[.03] p-2 transition hover:bg-white/[.07] hover:ring-1 hover:ring-pink-400/20"><div className="relative aspect-video w-24 shrink-0 overflow-hidden rounded-xl bg-black"><img src={getDuelMap(m.mapName)?.image||"/images/maps/aim_redline.svg"} alt={m.mapName||""} className="h-full w-full object-cover object-center transition duration-300 group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 to-transparent"/></div><div className="min-w-0 flex-1"><div className="truncate"><b>{m.game.title}</b><span className="ml-2 text-zinc-500">{m.mapName||"—"}</span></div><div className="mt-1 text-sm font-bold text-pink-400">${Number(m.betAmount).toFixed(2)}</div></div><span className="text-right text-[10px] font-bold text-zinc-400">{m.status}</span></Link>):<p className="text-zinc-500">{t.noHistory}</p>}</div></section>
  </div>
 </main></>
}
function Stat({n,t}:{n:string;t:string}){return <div className="rounded-2xl bg-white/[.03] p-5"><div className="text-2xl font-black text-pink-400">{n}</div><div className="text-xs text-zinc-500">{t}</div></div>}
function Row({label,value}:{label:string;value:React.ReactNode}){return <div className="flex justify-between border-b border-white/5 py-3 text-sm"><span className="text-zinc-500">{label}</span><b>{value}</b></div>}

function ProgressRow({done,label}:{done:boolean;label:string}){return <div className={`flex items-center gap-3 rounded-2xl border p-3 text-sm ${done?"border-emerald-400/15 bg-emerald-400/[.04]":"border-white/8 bg-white/[.025]"}`}><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full text-xs font-black ${done?"bg-emerald-400/15 text-emerald-300":"bg-white/5 text-zinc-500"}`}>{done?"✓":"○"}</span><span className={done?"text-zinc-200":"text-zinc-500"}>{label}</span></div>}

function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="flex cursor-pointer items-center justify-between rounded-2xl border border-white/8 bg-white/[.025] p-4"><span className="text-sm font-bold">{label}</span><button type="button" aria-pressed={value} onClick={()=>onChange(!value)} className={`relative h-7 w-12 rounded-full border transition ${value?"border-pink-400/70 bg-pink-400/20":"border-white/10 bg-black/30"}`}><span className={`absolute top-1 h-5 w-5 rounded-full transition ${value?"left-6 bg-pink-400":"left-1 bg-zinc-500"}`}/></button></label>}
