"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import AvatarPicker from "@/components/Profile/AvatarPicker";
import { useLanguage } from "@/components/Common/LanguageContext";
import { useTheme } from "@/components/Common/ThemeProvider";
import { THEMES, ThemeId } from "@/lib/themes";

type User={id:string;nickname:string;steamId:string|null;email:string|null;avatarUrl:string|null;steamAvatarUrl:string|null;themePreference:string;profileVisibility:string;showStatsPublic:boolean;allowChallenges:boolean;allowMessages:boolean;level:number;xp:number;reputation:number;trustScore:string;referralCode:string;balance:string;lockedBalance:string};
type Data={referralLink:string;user:User;stats:{matches:number;wins:number;losses:number;active:number;winRate:number;referralCount:number;referralEarned:number};matches:any[];achievements:any[]};
const MAP_IMAGES:Record<string,string>={Mirage:"/images/maps/mirage.jpg",Dust2:"/images/maps/dust2.jpg",Ancient:"/images/maps/ancient.jpg",Train:"/images/maps/train.jpg",Overpass:"/images/maps/overpass.jpg",Inferno:"/images/maps/inferno.jpg",Nuke:"/images/maps/nuke.jpg",Anubis:"/images/maps/anubis.jpg"};

export default function ProfilePage(){
 const {t,language}=useLanguage(); const {theme,setTheme}=useTheme(); const [data,setData]=useState<Data|null>(null); const [error,setError]=useState(""); const [authRequired,setAuthRequired]=useState(false); const [copied,setCopied]=useState(false);
 async function loadProfile(){const r=await fetch("/api/profile",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(r.status===401){setAuthRequired(true);return}if(!r.ok){setError(t.profileLoadError);return}setData(d)}
 useEffect(()=>{void loadProfile();const onWalletUpdated=()=>{void loadProfile()};window.addEventListener("duelplay:wallet-updated",onWalletUpdated);return()=>window.removeEventListener("duelplay:wallet-updated",onWalletUpdated)},[t.profileLoadError]);
 if(authRequired)return <><main className="mx-auto min-h-screen max-w-xl px-4 pb-20 pt-28"><section className="panel rounded-3xl p-8 text-center sm:p-10"><span className="pill">DUELPLAY</span><h1 className="mt-4 text-3xl font-black">{t.profile}</h1><p className="mt-3 text-zinc-500">{t.profileLoginRequired}</p><a href="/login" className="mt-6 inline-flex rounded-2xl bg-pink-400 px-6 py-3 font-black text-black hover:bg-pink-300">{t.goLogin}</a></section></main></>;
 if(!data)return <><main className="min-h-screen pt-28 text-center text-zinc-500">{error||t.loading}</main></>;
 const u=data.user; const referralCopyLabel=({RU:"Скопировать ссылку",UA:"Копіювати посилання",EN:"Copy link",PL:"Kopiuj link"} as any)[language]||"Copy link";
 const referralLink = data.referralLink;
 async function copy(value:string){await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1200)}
 async function privacy(patch:Record<string,unknown>){const r=await fetch("/api/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});const x=await r.json().catch(()=>({}));if(r.ok&&x.user)setData(prev=>prev?{...prev,referralLink:x.referralLink??prev.referralLink??"",stats:prev.stats,user:{...prev.user,...x.user}}:prev)}
 return <><main className="mx-auto min-h-screen max-w-6xl px-4 pb-20 pt-28">
  <div className="panel rounded-3xl p-7 sm:p-10">
   <div className="flex flex-col gap-7 lg:flex-row lg:items-start lg:justify-between">
    <div className="flex items-center gap-5"><AvatarPicker value={u.avatarUrl} steamAvatarUrl={u.steamAvatarUrl} nickname={u.nickname} onSaved={avatarUrl=>setData({...data,user:{...u,avatarUrl}})}/><div><span className="pill">{t.playerProfile}</span><h1 className="mt-3 text-4xl font-black">{u.nickname}</h1><p className="mt-2 text-zinc-500">{t.steamId}: {u.steamId||"—"}</p><p className="mt-2 text-xs text-zinc-600">{t.avatarHintShort}</p></div></div>
    <div className="flex gap-3"><a href="/wallet" className="rounded-2xl bg-pink-400 px-5 py-3 font-black text-black">{t.wallet} · ${Number(u.balance).toFixed(2)}</a><Link prefetch href="/create" className="rounded-2xl border border-white/10 px-5 py-3 font-bold">{t.createMatch}</Link></div>
   </div>
   <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><Stat n={String(data.stats.matches)} t={t.matchesCount}/><Stat n={String(data.stats.wins)} t={t.wins}/><Stat n={String(data.stats.losses)} t={t.losses}/><Stat n={`${data.stats.winRate}%`} t={t.winRate}/><Stat n={String(u.level)} t={`${t.level} · ${u.xp} ${t.xp}`}/><Stat n={String(data.achievements?.length??0)} t="Achievements"/></div>
  </div>
  <nav className="panel mt-6 rounded-3xl p-3 sm:p-4 overflow-x-auto"><div className="flex min-w-max gap-2">{[
    ["Overview","/profile"],["📊 Analytics","/analytics"],["⚔ Matches","/matches"],["🏆 Achievements","/achievements"],["🎒 Inventory","/inventory"],["💎 Collections","/collections"],["👥 Social","/social"],["🛡 Clans","/clans"],["🎟 DuelPass","/duelpass"],["👑 Prime","/prime"],["💳 Wallet","/wallet"]
  ].map(([label,href])=><a key={href} href={href} className="rounded-xl border border-white/8 bg-white/[.025] px-4 py-2 text-sm font-bold text-zinc-300 transition hover:border-pink-400/30 hover:text-white">{label}</a>)}</div></nav>
  <section className="panel mt-6 rounded-3xl p-5 sm:p-6">
   <div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><span className="pill">STYLE</span><h2 className="mt-3 text-2xl font-black">{t.themeStyle}</h2><p className="mt-2 max-w-3xl text-sm text-zinc-500">{t.themeDescription}</p></div><span className="text-xs font-bold text-zinc-500">{theme==="STANDARD"?t.themeStandard:t.themePersonal}</span></div>
   <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3 lg:grid-cols-5">
    {THEMES.map(x=><button type="button" key={x.id} onClick={()=>setTheme(x.id as ThemeId)} className={`group overflow-hidden rounded-xl border text-left transition hover:-translate-y-0.5 ${theme===x.id?"border-pink-400/70 bg-pink-400/[.08]":"border-white/8 bg-white/[.025] hover:border-white/20"}`}>
      <div className="h-12 w-full" style={{background:`linear-gradient(135deg,${x.preview[0]} 0%,${x.preview[0]} 45%,${x.preview[1]} 45%,${x.preview[1]} 70%,${x.preview[2]} 70%)`}}/>
      <div className="p-3"><div className="text-sm font-bold">{x.name}</div><div className="mt-1 truncate text-[11px] text-zinc-500">{x.description}</div></div>
    </button>)}
   </div>
  </section>

  <section className="panel mt-6 rounded-3xl p-7"><div><span className="pill">PRIVACY</span><h2 className="mt-3 text-2xl font-black">Profile & Social Privacy</h2><p className="mt-2 text-sm text-zinc-500">Control what other players can see and which interactions you accept.</p></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="rounded-2xl border border-white/8 bg-white/[.025] p-4"><span className="text-sm font-bold">Profile visibility</span><select value={u.profileVisibility} onChange={e=>privacy({profileVisibility:e.target.value})} className="input mt-3"><option value="PUBLIC">Everyone</option><option value="FRIENDS">Friends only</option><option value="PRIVATE">Private</option></select></label><Toggle label="Show public statistics" value={u.showStatsPublic} onChange={v=>privacy({showStatsPublic:v})}/><Toggle label="Accept duel challenges" value={u.allowChallenges} onChange={v=>privacy({allowChallenges:v})}/><Toggle label="Accept private messages" value={u.allowMessages} onChange={v=>privacy({allowMessages:v})}/></div></section>
  <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_1.5fr]">
   <section className="panel rounded-3xl p-7"><h2 className="text-2xl font-black">{t.profile}</h2><div className="mt-5 space-y-3"><Row label={t.reputation} value={u.reputation}/><Row label={t.trust} value={`${Number(u.trustScore).toFixed(0)}%`}/><Row label="Email" value={u.email||"—"}/><Row label={t.balance} value={`$${Number(u.balance).toFixed(2)}`}/><Row label={t.locked} value={`$${Number(u.lockedBalance).toFixed(2)}`}/></div><div className="mt-6 rounded-2xl border border-pink-400/10 bg-pink-400/[.035] p-4"><div className="text-xs uppercase tracking-wider text-pink-300">{t.referralTitle}</div><p className="mt-2 text-xs leading-5 text-zinc-500">{t.referralDescription}</p><div className="mt-3 flex gap-2"><input readOnly value={u.referralCode} className="input"/><button onClick={()=>copy(u.referralCode)} className="cursor-pointer rounded-xl border border-white/10 px-4 text-sm font-bold transition hover:border-pink-400/40 hover:bg-pink-400/5 hover:text-pink-200">{copied?t.copied:t.copy}</button></div><div className="mt-2 flex gap-2"><input readOnly value={referralLink} className="input text-xs"/><button onClick={()=>copy(referralLink)} className="cursor-pointer rounded-xl border border-white/10 px-4 text-sm font-bold transition hover:border-pink-400/40 hover:bg-pink-400/5">{referralCopyLabel}</button></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-black/20 p-3"><div className="text-[11px] text-zinc-600">{t.referralInvited}</div><b className="mt-1 block">{data.stats.referralCount}</b></div><div className="rounded-xl bg-black/20 p-3"><div className="text-[11px] text-zinc-600">{t.referralEarned}</div><b className="mt-1 block text-pink-400">${data.stats.referralEarned.toFixed(4)}</b></div></div><p className="mt-3 text-[11px] text-zinc-600">{t.referralReward}</p></div></section>
   <section className="panel rounded-3xl p-7"><div className="flex items-center justify-between"><h2 className="text-2xl font-black">{t.recentMatches}</h2><a href="/live" className="text-sm text-pink-400">LIVE →</a></div><div className="mt-5 space-y-3">{data.matches.filter(m=>MAP_IMAGES[m.mapName||""]).slice(0,8).length?data.matches.filter(m=>MAP_IMAGES[m.mapName||""]).slice(0,8).map(m=><a href={`/matches/${m.id}`} key={m.id} className="group flex items-center gap-3 rounded-2xl bg-white/[.03] p-2 transition hover:bg-white/[.07] hover:ring-1 hover:ring-pink-400/20"><div className="relative aspect-video w-24 shrink-0 overflow-hidden rounded-xl bg-black"><img src={MAP_IMAGES[m.mapName]} alt={m.mapName||""} className="h-full w-full object-cover object-center transition duration-300 group-hover:scale-[1.04]"/><div className="absolute inset-0 bg-gradient-to-t from-black/55 to-transparent"/></div><div className="min-w-0 flex-1"><div className="truncate"><b>{m.game.title}</b><span className="ml-2 text-zinc-500">{m.mapName||"—"}</span></div><div className="mt-1 text-sm font-bold text-pink-400">${Number(m.betAmount).toFixed(2)}</div></div><span className="text-right text-[10px] font-bold text-zinc-400">{m.status}</span></a>):<p className="text-zinc-500">{t.noHistory}</p>}</div></section>
  </div>
 </main></>
}
function Stat({n,t}:{n:string;t:string}){return <div className="rounded-2xl bg-white/[.03] p-5"><div className="text-2xl font-black text-pink-400">{n}</div><div className="text-xs text-zinc-500">{t}</div></div>}
function Row({label,value}:{label:string;value:React.ReactNode}){return <div className="flex justify-between border-b border-white/5 py-3 text-sm"><span className="text-zinc-500">{label}</span><b>{value}</b></div>}

function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="flex cursor-pointer items-center justify-between rounded-2xl border border-white/8 bg-white/[.025] p-4"><span className="text-sm font-bold">{label}</span><button type="button" aria-pressed={value} onClick={()=>onChange(!value)} className={`relative h-7 w-12 rounded-full border transition ${value?"border-pink-400/70 bg-pink-400/20":"border-white/10 bg-black/30"}`}><span className={`absolute top-1 h-5 w-5 rounded-full transition ${value?"left-6 bg-pink-400":"left-1 bg-zinc-500"}`}/></button></label>}
