const ru = {topPlayers:"ТОП ИГРОКИ",playersCount:"игроков",findOpponent:"Найди соперника",friendJoins:"Друг присоединится к матчу",playDuel:"Сыграй 1v1",connectCS2:"Оба подключаются к CS2",getWinnings:"Получи выигрыш",serverConfirms:"Сервер подтверждает результат",allMaps:"Все карты",allBets:"Все ставки",activeNo:"Сейчас нет активных матчей",activeHint:"Когда второй игрок подключится и матч станет READY, он появится здесь.",openMatch:"Открыть матч",showMore:"Показать ещё",hide:"Скрыть",createDuel:"СОЗДАТЬ ДУЭЛЬ",openDuels:"ОТКРЫТЫЕ ДУЭЛИ",activeDuels:"активных дуэлей",formatLabel:"формат",commissionLabel:"комиссия",openDuelsTitle:"Открытые дуэли",noOpenDuels:"Пока нет открытых дуэлей",inviteFriend:"Создай первую и пригласи друга.",viewAllDuels:"СМОТРЕТЬ ВСЕ ДУЭЛИ →",howItWorks:"КАК ЭТО РАБОТАЕТ",fromDuelToWin:"ОТ ДУЭЛИ",toVictory:"ДО ПОБЕДЫ.",fairPlay:"ЧЕСТНАЯ ИГРА",gameDecides:"МАТЧ РЕШАЕТ ИГРА,",notSiteButton:"НЕ КНОПКА НА САЙТЕ.",betLocked:"Ставка блокируется",bothPlayersStake:"Оба игрока вносят одинаковую сумму.",cs2Starts:"CS2 запускается",serverResultTitle:"Сервер подтверждает результат",serverResultText:"Сайт рассчитывает выплату только после подтверждения сервера.",matchTestCancel:"Отменить матч",openCS2:"Открыть CS2",connectServer:"Подключиться к серверу",matchRunning:"Матч идёт",serverResult:"Результат подтвердит игровой сервер.",
  home:"Главная",matches:"Матчи",live:"LIVE",tournaments:"Турниры",rating:"Рейтинг",login:"Войти через Steam",logout:"Выйти",register:"Регистрация",
  heroTitle:"Дуэль начинается сейчас.",heroText:"Создавай матчи CS2 1v1, находи соперников и соревнуйся за банк в одном быстром игровом лобби.",findMatch:"Найти матч",createMatch:"Создать матч",competitive:"COMPETITIVE GAMING PLATFORM",
  chooseMap:"Выбери карту",mapsText:"Популярные карты для быстрых дуэлей 1v1.",matchmaking:"MATCHMAKING",createTitle:"Создай дуэль.",createTitle2:"Забери банк.",createText:"CS2 1v1. Минимальная ставка — $3. Все ставки и баланс DuelPlay отображаются только в USD.",format:"Формат",commission:"Комиссия",minBet:"Мин. ставка",newMatch:"Новый матч",open:"OPEN",balance:"Баланс",deposit:"Пополнить",withdraw:"Вывод",paymentSoon:"Подключение платежей будет доступно на следующем этапе.",bet:"Ставка",server:"Сервер",feeFromPot:"Комиссия с банка",winnerGets:"Победитель получит",join:"Присоединиться",joining:"Подключение…",create:"⚔ Создать матч",creating:"Создание…",loginToCreate:"Войдите, чтобы создать матч.",created:"Матч создан — он появился в Матчах.",
  liveLobby:"LIVE LOBBY",matchesNow:"Матчи сейчас",liveText:"Реальные матчи из PostgreSQL · ставки только в USD.",refresh:"↻ Обновить",loading:"Загружаем лобби…",noMatches:"Пока нет открытых матчей",firstMatch:"Создай первый матч и он появится здесь.",players:"игроков",waiting:"WAITING",ready:"READY",full:"Матч заполнен",ownMatch:"Нельзя присоединиться к своему матчу",
  wallet:"Кошелёк",profile:"Профиль",history:"История матчей",transactions:"Транзакции",availableBalance:"Доступный баланс",noTransactions:"Транзакций пока нет.",
  playerProfile:"PLAYER PROFILE",level:"Уровень",reputation:"Репутация",email:"Email",matchesCount:"Матчей",wins:"Побед",losses:"Поражений",winRate:"Винрейт",xp:"XP",trust:"Доверие",referral:"Реферальный код",copy:"Копировать",copied:"Скопировано",recentMatches:"Последние матчи",noHistory:"Истории пока нет.",viewWallet:"Кошелёк",matchHistory:"История матчей",status:"Статус",pot:"Банк",game:"Игра",map:"Карта",
  matchReady:"MATCH READY",waitingOpponent:"Ожидаем второго игрока",bothReady:"Оба игрока внесли ставку. Матч готов к старту.",productionNote:"Для production нужен серверный referee и Steam verification.",backMatches:"← В Матчи",backLive:"← В LIVE",startMatch:"▶ Начать матч",chooseWinner:"Выберите победителя",finish:"Завершить матч",cancel:"Отменить матч",finished:"Матч завершён",winner:"Победитель",payout:"Выплата",cancelled:"Матч отменён",walletRequired:"Недостаточно средств для этой операции",
  tournamentsTitle:"Турниры CS2",tournamentsText:"Скоро здесь появятся полноценные турниры DuelPlay.",comingSoon:"СКОРО",ratingTitle:"Рейтинг игроков",ratingText:"Рейтинг, ELO и статистика игроков.",
  authLogin:"Вход в DuelPlay",authRegister:"Создать аккаунт",nickname:"Никнейм",password:"Пароль",confirmPassword:"Повторите пароль",enter:"Войти",createAccount:"Зарегистрироваться",noAccount:"Нет аккаунта?",hasAccount:"Уже есть аккаунт?",goRegister:"Зарегистрироваться",goLogin:"Войти",authHint:"3–20 символов, латиница, цифры и _.",
  referralCodeOptional:"Реферальный код (необязательно)",referralRegisterHint:"Если у тебя есть код друга, введи его — после регистрации ты будешь привязан к нему.",referralTitle:"Реферальная программа",referralDescription:"Приглашай игроков по своему коду. Когда приглашённый игрок выигрывает матч, 0,1% от его выигрышной выплаты перечисляется тебе из его выплаты.",referralReward:"Твоя награда: 0,1% от выигрышной выплаты приглашённого игрока удерживается из его выплаты.",referralInvited:"Приглашено игроков",referralEarned:"Заработано с рефералов",passwordMismatch:"Пароли не совпадают",transactionTypes:{DEPOSIT:"Пополнение",WITHDRAW:"Вывод",MATCH_BET:"Ставка",MATCH_WIN:"Выигрыш",REFUND:"Возврат",BONUS:"Бонус",REFERRAL:"Реферал",COMMISSION:"Комиссия"},
  mapNames:{Mirage:"Mirage",Dust2:"Dust2",Inferno:"Inferno",Nuke:"Nuke",Ancient:"Ancient",Anubis:"Anubis",Train:"Train",Overpass:"Overpass"}
, avatarSaved:"Аватар сохранён", avatarSaveError:"Не удалось сохранить аватар", avatarImageOnly:"Выбери изображение", avatarTooLarge:"Файл слишком большой. Максимум 5 МБ.", changeAvatar:"Изменить фото", chooseAvatar:"Выбери стандартный аватар", uploadAvatar:"Загрузить своё фото", saving:"Сохраняем…", avatarHint:"Можно выбрать стандартный аватар или загрузить своё фото. Изображение автоматически обрежется до квадрата.", avatarHintShort:"Нажми на фото, чтобы изменить аватар.", profileLoadError:"Не удалось загрузить профиль", locked:"Заблокировано",loginSteam:"Продолжить через Steam",registerSteam:"Зарегистрироваться через Steam",or:"или",steamVerifyError:"Не удалось подтвердить аккаунт Steam.",steamStateError:"Сессия входа Steam устарела. Попробуйте ещё раз.",steamError:"Не удалось войти через Steam.",accountDisabled:"Аккаунт временно недоступен.",themeStyle:"Стиль интерфейса",themeDescription:"Выбери оформление DuelPlay. Если оставить стандартную тему, она следует настройкам сайта.",themePersonal:"Персональная тема",themeStandard:"Стандартная тема",heroTitleNew:"Твоя игра. Твой матч. Твой результат.",heroTextNew:"Создавай честные дуэли CS2 1v1 и играй с соперниками через Steam.",liveSubtitle:"Игровые матчи, которые проходят прямо сейчас.",matchStarted:"Матч запущен. Подключайтесь к CS2.",serverPending:"Игровая сессия готовится. Подключение появится автоматически.",adminAccess:"Центр управления"}; export default ru;
