"use client";
import {useEffect,useState} from "react";
export default function EventsPage(){
 const [events,setEvents]=useState<any[]>([]); const [selected,setSelected]=useState<any|null>(null); const [pass,setPass]=useState<any>(null); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/events",{cache:"no-store"});const x=await r.json();setEvents(Array.isArray(x)?x:[])}
 useEffect(()=>{void load()},[]);
 async function openEvent(e:any){setSelected(e);setMsg("");const r=await fetch("/api/events/pass?eventId="+encodeURIComponent(e.id),{cache:"no-store"});const x=await r.json();if(r.ok)setPass(x);else setPass(null)}
 async function join(premium=false){if(!selected)return;setBusy(true);setMsg("");const r=await fetch("/api/events/pass",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventId:selected.id,action:"join",premium})});const x=await r.json();setMsg(r.ok?"Pass activated.":x.error||"Could not activate pass.");if(r.ok)await openEvent(selected);setBusy(false)}
 async function claim(level:number){if(!selected)return;setBusy(true);const r=await fetch("/api/events/pass",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventId:selected.id,action:"claim",level})});const x=await r.json();setMsg(r.ok?"Reward claimed.":x.error||"Could not claim reward.");if(r.ok)await openEvent(selected);setBusy(false)}
 return <main className="mx-auto min-h-screen max-w-6xl px-4 pb-20 pt-28"><section className="panel rounded-3xl p-7 sm:p-10"><span className="pill">EVENT CALENDAR</span><h1 className="mt-4 text-4xl font-black">Events & Promotions</h1><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{events.map(x=><button key={x.id} onClick={()=>openEvent(x)} className="rounded-2xl border border-white/5 p-5 text-left transition hover:border-pink-400/30"><div className="text-2xl">{x.icon||"🎉"}</div><h2 className="mt-3 text-xl font-black">{x.name}</h2><p className="mt-2 text-sm text-zinc-500">{x.theme||"DuelPlay Event"} · ×{Number(x.promoMultiplier||1)}</p><p className="mt-2 text-xs text-zinc-600">{new Date(x.startsAt).toLocaleString()} → {new Date(x.endsAt).toLocaleString()}</p><span className="mt-4 inline-block text-xs font-bold text-pink-400">{x.eventPass?"OPEN EVENT PASS":"VIEW EVENT"}</span></button>)}</div></section>
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onClick={()=>setSelected(null)}><section onClick={e=>e.stopPropagation()} className="panel mobile-modal max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><span className="pill">{selected.status}</span><h2 className="mt-3 text-3xl font-black">{selected.icon||"🎉"} {selected.name}</h2><p className="mt-2 text-sm text-zinc-500">{selected.theme||"DuelPlay Event"}</p></div><button onClick={()=>setSelected(null)} className="rounded-xl border border-white/10 px-3 py-2">×</button></div>{msg&&<div className="mt-5 rounded-xl border border-pink-400/20 bg-pink-400/5 p-3 text-sm">{msg}</div>}
 {selected.eventPass&&!pass?.pass&&<div className="mt-6 rounded-2xl border border-white/5 p-5"><h3 className="font-black">Event Pass</h3><p className="mt-2 text-sm text-zinc-500">Join the event progression and unlock rewards.</p><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy} onClick={()=>join(false)} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold">Join Free</button>{selected.premiumPass&&<button disabled={busy} onClick={()=>join(true)} className="rounded-xl bg-pink-500 px-4 py-2 text-sm font-bold text-black">Premium · {Number(selected.premiumPrice)} DP</button>}</div></div>}
 {pass?.pass&&<div className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black">Event Pass · Level {pass.pass.level}</h3><p className="text-sm text-zinc-500">{pass.pass.xp} XP total · {pass.progressSummary?.currentXp??0}/{pass.progressSummary?.nextLevelXp??100} to next level</p></div>{!pass.pass.premium&&selected.premiumPass&&<button disabled={busy} onClick={()=>join(true)} className="rounded-xl bg-pink-500 px-4 py-2 text-sm font-bold text-black">Upgrade Premium · {Number(selected.premiumPrice)} DP</button>}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full bg-pink-500" style={{width:`${Number(pass.progressSummary?.percent??(pass.pass.xp%100))}%`}}/></div>
 <div className="mt-6 rounded-2xl border border-white/5 p-4"><div className="font-black">Event Missions</div><div className="mt-3 space-y-2">{(pass.missions||[]).map((m:any)=>{const pr=(pass.progress||[]).find((x:any)=>x.missionId===m.id);return <div key={m.id} className="rounded-xl bg-white/[.03] p-3"><div className="flex justify-between gap-3"><span className="font-bold">{m.name}</span><span className="text-xs text-zinc-500">{pr?.progress??0}/{m.target}</span></div>{pr?.completed&&<div className="mt-1 text-xs font-bold text-emerald-400">Completed · reward granted</div>}</div>})}</div></div>
 <div className="mt-6 grid gap-2 sm:grid-cols-2">{(Array.isArray(selected.rewards)?selected.rewards:[]).slice(0,30).map((r:any)=><div key={String(r.level)} className="rounded-xl border border-white/5 p-3"><div className="flex items-center justify-between"><b>Level {r.level}</b><span className="text-xs text-zinc-500">{r.free&&r.premium?"FREE + PREMIUM":r.premium?"PREMIUM":"FREE"}</span></div><div className="mt-1 text-sm text-zinc-400">{r.name||[r.free&&"Free reward",r.premium&&"Premium reward"].filter(Boolean).join(" + ")||JSON.stringify(r)}</div>{Number(r.level)<=Number(pass.pass.level)&&<button disabled={busy||pass.claims.some((c:any)=>Number(c.level)===Number(r.level))} onClick={()=>claim(Number(r.level))} className="mt-2 rounded-lg border border-white/10 px-3 py-1 text-xs">{pass.claims.some((c:any)=>Number(c.level)===Number(r.level))?"Claimed":"Claim"}</button>}</div>)}</div></div>}
 </section></div>}</main>
}