"use client";
import { useEffect, useState } from "react";

export default function AdminSetupPage() {
  const [token, setToken] = useState(""); const [nickname, setNickname] = useState(""); const [role, setRole] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [done, setDone] = useState(false);
  useEffect(()=>{const t=new URLSearchParams(window.location.search).get("token")||"";setToken(t);if(!t)return;window.history.replaceState({},"","/admin/setup");fetch(`/api/admin/auth/setup?token=${encodeURIComponent(t)}`,{cache:"no-store"}).then(async r=>{const x=await r.json().catch(()=>({}));if(!r.ok){setError(x.error||"Ссылка недействительна.");return}setNickname(x.nickname||"");setRole(x.role||"");}).catch(()=>setError("Не удалось проверить приглашение."));},[]);
  async function save(){setBusy(true);setError("");try{const r=await fetch("/api/admin/auth/setup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,password,confirmPassword:confirm})});const x=await r.json().catch(()=>({}));if(!r.ok){setError(x.error||"Не удалось установить пароль.");return}setDone(true);}catch{setError("Не удалось установить пароль.");}finally{setBusy(false)}}
  if(done)return <main className="mx-auto min-h-screen max-w-md px-4 pb-20 pt-28"><div className="panel rounded-3xl p-6 sm:p-8 text-center"><div className="pill">DUELPLAY ADMIN</div><h1 className="mt-4 text-3xl font-black">Пароль создан</h1><p className="mt-3 text-sm leading-6 text-zinc-400">Админ-доступ для <b className="text-white">{nickname}</b> активирован. Теперь вход выполняется через отдельный админ-портал.</p><a href="/admin/login" className="mt-6 block rounded-2xl bg-[var(--theme-accent)] py-3 font-black text-black">Перейти ко входу</a></div></main>;
  return <main className="mx-auto min-h-screen max-w-md px-4 pb-20 pt-28"><div className="panel rounded-3xl p-6 sm:p-8"><div className="pill">DUELPLAY ADMIN INVITE</div><h1 className="mt-4 text-3xl font-black">Создай свой пароль</h1><p className="mt-3 text-sm leading-6 text-zinc-400">Ты получил персональное приглашение в команду DuelPlay. Придумай собственный пароль — общего пароля для админов нет.</p>{nickname&&<div className="mt-5 rounded-2xl bg-white/[.03] p-4"><div className="text-xs text-zinc-500">Аккаунт</div><div className="mt-1 font-black">{nickname}</div><div className="mt-1 text-xs text-zinc-500">Роль: {role}</div></div>}{error&&<div className="mt-5 rounded-xl border border-red-400/20 bg-red-400/5 p-3 text-sm text-red-300">{error}</div>}{token&&<><label className="mt-5 block"><span className="mb-2 block text-xs font-black uppercase tracking-widest text-zinc-500">Новый пароль</span><input className="input" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} /></label><label className="mt-4 block"><span className="mb-2 block text-xs font-black uppercase tracking-widest text-zinc-500">Повтор пароля</span><input className="input" type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} /></label><p className="mt-3 text-xs leading-5 text-zinc-500">Минимум 12 символов: заглавная, строчная, цифра и специальный символ.</p><button disabled={busy||!password||password!==confirm} onClick={()=>void save()} className="mt-6 w-full rounded-2xl bg-[var(--theme-accent)] py-3 font-black text-black disabled:opacity-40">{busy?"Сохраняем…":"Создать пароль"}</button></>}</div></main>;
}
