"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {useLanguage} from "@/components/Common/LanguageContext";

type Item={id:string;name:string;imageUrl:string;rarity:string;value:number;status:string;createdAt:string};
export default function InventoryPage(){
 const{t}=useLanguage(); const router=useRouter();const[items,setItems]=useState<Item[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{fetch("/api/inventory",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||"ERROR");setItems(d)}).catch(e=>setError(e instanceof Error?e.message:"Не удалось загрузить инвентарь")).finally(()=>setLoading(false))},[]);
 return <main className="mx-auto min-h-screen max-w-7xl px-4 pb-20 pt-28 sm:px-6"><div className="panel rounded-3xl p-7 sm:p-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="pill">INVENTORY</span><h1 className="mt-3 text-4xl font-black">{t.inventoryTitle}</h1><p className="mt-2 text-zinc-500">{t.inventoryText}</p></div><button type="button" onClick={()=>router.push("/cases")} className="rounded-xl border border-white/10 px-4 py-2 text-sm font-bold transition hover:border-[var(--theme-accent)]/40 hover:text-[var(--theme-accent)]">{t.toCases}</button></div>{loading?<div className="mt-8 p-10 text-center text-zinc-500">{t.loading}</div>:error?<div className="mt-8 rounded-2xl border border-red-400/20 bg-red-400/5 p-5 text-red-300">{error}</div>:!items.length?<div className="mt-8 rounded-2xl border border-white/5 bg-white/[.025] p-10 text-center"><div className="text-xl font-black">{t.emptyInventory}</div><p className="mt-2 text-sm text-zinc-500">{t.emptyInventoryText}</p><button type="button" onClick={()=>router.push("/cases")} className="mt-5 inline-flex rounded-xl bg-[var(--theme-accent)] px-5 py-3 font-black text-black">{t.openCases}</button></div>:<div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{items.map(i=><article key={i.id} className="overflow-hidden rounded-2xl border border-white/8 bg-white/[.025]"><img src={i.imageUrl} alt="" className="aspect-[4/3] w-full object-cover"/><div className="p-3"><div className="text-[10px] uppercase tracking-widest text-zinc-600">{i.rarity}</div><div className="mt-1 truncate font-bold">{i.name}</div><div className="mt-2 flex justify-between text-xs"><span className="text-[var(--theme-accent)]">${i.value.toFixed(2)}</span><span className="text-zinc-600">{t.inventoryAvailable}</span></div></div></article>)}</div>}</div></main>
}
