"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect,useState } from "react";
import Header from "@/components/Header/Header";
import CenterModal from "@/components/Common/CenterModal";
import { useLanguage } from "@/components/Common/LanguageContext";
const MAP_IMAGES:Record<string,string>={Mirage:"/images/maps/covers/mirage.jpg",Dust2:"/images/maps/covers/dust2.jpg",Ancient:"/images/maps/covers/ancient.jpg",Train:"/images/maps/covers/train.jpg",Overpass:"/images/maps/covers/overpass.jpg",Inferno:"/images/maps/covers/inferno.jpg",Nuke:"/images/maps/covers/nuke.jpg",Anubis:"/images/maps/covers/anubis.jpg"};
type Player={id?:string;nickname:string;avatarUrl:string|null;steamAvatarUrl?:string|null};
type Match={id:string;playerOneId:string;playerTwoId:string|null;status:string;mode:string;mapName:string|null;betAmount:string|number;commission:string|number;playerOne:Player;playerTwo:Player|null;winner?:Player|null;serverConfig?:{connectUrl?:string|null;state?:string;managerRequested?:boolean}|null;startedAt?:string|null;endedAt?:string|null};
const steps=["РЎРѕР·РґР°РЅ","РРіСЂРѕРє 2","Ready","РЎРµСЂРІРµСЂ","РРіСЂР°","Р РµР·СѓР»СЊС‚Р°С‚"];
export default function MatchPage({params}:{params:Promise<{id:string}>}){
 const{t}=useLanguage();const[id,setId]=useState("");const[m,setM]=useState<Match|null>(null);const[user,setUser]=useState<any>(null);const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);const[cancelOpen,setCancelOpen]=useState(false);
 useEffect(()=>{params.then(p=>setId(p.id))},[params]);
 async function load(){if(!id)return;try{const [mr,ur]=await Promise.all([fetch(`/api/matches/${id}`,{cache:"no-store"}),fetch("/api/auth/me",{cache:"no-store"})]);const md=await mr.json(),ud=await ur.json();if(!mr.ok)throw 0;setM(md.match??md);setUser(ud.user??null)}catch{setMsg(t.matchLoadError)}}
 useEffect(()=>{load()},[id]);useEffect(()=>{if(!id)return;const timer=setInterval(load,3000);return()=>clearInterval(timer)},[id]);
 async function action(path:string){setBusy(true);setMsg("");try{const r=await fetch(`/api/matches/${id}/${path}`,{method:"POST"});const d=await r.json();if(!r.ok)throw new Error(d.error||"ERROR");setM(d.match??d);if(path==="start")setMsg(t.matchStarted)}catch(e){setMsg(e instanceof Error?e.message:t.startError)}finally{setBusy(false)}}
 function launchSteam(url:string){const frame=document.createElement("iframe");frame.style.display="none";frame.src=url;document.body.appendChild(frame);window.setTimeout(()=>frame.remove(),2000)}
 if(!m)return <><Header/><main className="min-h-screen pt-28 text-center text-zinc-500">{t.loading}</main></>;
 const pot=Number(m.betAmount)*(m.playerTwo?2:1),payout=pot-Number(m.commission??pot*.10),participant=Boolean(user&&[m.playerOneId,m.playerTwoId].includes(user.id));const mapImage=MAP_IMAGES[m.mapName||""];
 const activeStep=m.status==="WAITING_FOR_PLAYERS"?1:m.status==="READY"?3:m.status==="LIVE"?5:m.status==="FINISHED"?6:1;
 const p1=m.playerOne.avatarUrl||m.playerOne.steamAvatarUrl||"/avatars/premium/01-cyan.svg",p2=m.playerTwo?.avatarUrl||m.playerTwo?.steamAvatarUrl||"/avatars/premium/02-violet.svg";
 return <><Header/><main className="mx-auto min-h-screen max-w-6xl px-4 pb-20 pt-24 sm:px-6">
  <div className="mb-4 flex items-center justify-between gap-3"><Link href="/matches" className="text-sm font-bold text-zinc-500 hover:text-[var(--theme-accent)]">в†ђ {t.backMatches}</Link><span className={`status ${m.status==="LIVE"?"live":"waiting"}`}>{m.status}</span></div>
  <section className="panel overflow-hidden rounded-[28px]">
   <div className="relative h-56 sm:h-72"><Image src={mapImage||"/images/maps/covers/mirage.jpg"} alt={m.mapName||"CS2"} fill className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,5,7,.96),rgba(5,5,7,.35),rgba(5,5,7,.96))]"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(255,47,145,.18),transparent_45%)]"/><div className="absolute inset-x-5 bottom-7 text-center"><div className="text-xs font-black tracking-[.25em] text-[var(--theme-accent)]">CS2 В· 1V1 DUEL</div><h1 className="mt-2 text-3xl font-black sm:text-5xl">РњР°С‚С‡ #{m.id.slice(0,8).toUpperCase()}</h1><p className="mt-2 text-sm text-zinc-400">{m.mapName||"Mirage"} В· 1 vs 1 В· ${Number(m.betAmount).toFixed(2)}</p></div></div>
   <div className="p-5 sm:p-8">
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-6">{steps.map((s,i)=><div key={s} className="flex flex-col items-center gap-2 text-center"><span className={`step-circle ${i+1<=activeStep?"active":""}`}>{i+1}</span><span className={`text-[11px] ${i+1<=activeStep?"text-white":"text-zinc-600"}`}>{s}</span></div>)}</div>
    <div className="mt-7 grid gap-4 lg:grid-cols-[1fr_auto_1fr_auto] lg:items-stretch">
      <PlayerCard player={m.playerOne} avatar={p1} crown={true} bet={Number(m.betAmount)} ready={m.status!=="WAITING_FOR_PLAYERS"}/><div className="hidden items-center justify-center lg:flex text-2xl font-black text-[var(--theme-accent)]">VS</div>
      <PlayerCard player={m.playerTwo} avatar={p2} bet={Number(m.betAmount)} ready={Boolean(m.playerTwo)}/><div className="rounded-2xl border border-white/5 bg-white/[.025] p-4 lg:w-56"><div className="text-xs uppercase tracking-wider text-zinc-600">РљР°СЂС‚Р°</div><div className="mt-2 overflow-hidden rounded-xl"><Image src={mapImage||"/images/maps/covers/mirage.jpg"} alt="" width={320} height={150} className="h-24 w-full object-cover"/></div><div className="mt-3 flex justify-between text-sm"><b>{m.mapName||"Mirage"}</b><span className="text-zinc-500">1 vs 1</span></div><div className="mt-1 text-xs text-zinc-500">РЎС‚Р°РІРєР° <b className="text-white">${Number(m.betAmount).toFixed(2)}</b></div></div>
    </div>
    {m.status==="WAITING_FOR_PLAYERS"&&<Notice title="РћР¶РёРґР°РЅРёРµ РёРіСЂРѕРєР°" gold>РћР¶РёРґР°РµРј РІС‚РѕСЂРѕРіРѕ РёРіСЂРѕРєР°. РџРѕСЃР»Рµ РµРіРѕ РїРѕРґРєР»СЋС‡РµРЅРёСЏ Рё РїРѕРґС‚РІРµСЂР¶РґРµРЅРёСЏ СЃС‚Р°РІРєРё РґСѓСЌР»СЊ РїРµСЂРµР№РґС‘С‚ Рє Р·Р°РїСѓСЃРєСѓ СЃРµСЂРІРµСЂР° CS2.</Notice>}
    {m.status==="READY"&&<Notice title="РњР°С‚С‡ РіРѕС‚РѕРІ" >{m.serverConfig?.managerRequested?"РЎРµСЂРІРµСЂ DuelPlay Р·Р°РїСѓСЃРєР°РµС‚СЃСЏ Р°РІС‚РѕРјР°С‚РёС‡РµСЃРєРё. РљР°Рє С‚РѕР»СЊРєРѕ РѕРЅ Р±СѓРґРµС‚ РіРѕС‚РѕРІ, РїРѕСЏРІРёС‚СЃСЏ РєРЅРѕРїРєР° РїРѕРґРєР»СЋС‡РµРЅРёСЏ.":"РћР±Р° РёРіСЂРѕРєР° РіРѕС‚РѕРІС‹. РќР°Р¶РјРёС‚Рµ Start, С‡С‚РѕР±С‹ Р·Р°РїСѓСЃС‚РёС‚СЊ СЃРµСЂРІРµСЂ."}</Notice>}
    {m.status==="LIVE"&&<div className="mt-5 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.05] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-black text-emerald-300"><span className="site-live-dot"/> РњР°С‚С‡ РІ РїСЂРѕС†РµСЃСЃРµ</div><p className="mt-1 text-sm text-zinc-500">Р РµР·СѓР»СЊС‚Р°С‚ РѕРїСЂРµРґРµР»СЏРµС‚ СЃРµСЂРІРµСЂ CS2 Р°РІС‚РѕРјР°С‚РёС‡РµСЃРєРё.</p></div><span className="status live">LIVE</span></div><div className="mt-5 flex flex-wrap gap-3">{m.serverConfig?.connectUrl&&<a href={m.serverConfig.connectUrl} className="rounded-xl border border-emerald-400/25 px-5 py-3 text-sm font-black text-emerald-300">РџРѕРґРєР»СЋС‡РёС‚СЊСЃСЏ Рє СЃРµСЂРІРµСЂСѓ</a>}</div></div>}
    {m.status==="FINISHED"&&<Notice title="Р РµР·СѓР»СЊС‚Р°С‚ РїРѕРґС‚РІРµСЂР¶РґС‘РЅ СЃРµСЂРІРµСЂРѕРј" >РџРѕР±РµРґРёС‚РµР»СЊ: <b>{m.winner?.nickname||"вЂ”"}</b> В· Р’С‹РїР»Р°С‚Р° <b>${payout.toFixed(2)}</b></Notice>}
    {m.status==="CANCELLED"&&<Notice title="РњР°С‚С‡ РѕС‚РјРµРЅС‘РЅ">РЎС‚Р°РІРєРё РІРѕР·РІСЂР°С‰РµРЅС‹ СЃРѕРіР»Р°СЃРЅРѕ РїСЂР°РІРёР»Р°Рј DuelPlay.</Notice>}
    {msg&&<div aria-live="polite" className="mt-4 rounded-xl border border-white/10 bg-white/[.03] p-4 text-sm text-[var(--theme-accent)]">{msg}</div>}
    <div className="mt-6 flex flex-wrap gap-3">{participant&&user?.id===m.playerOneId&&m.status==="READY"&&!m.serverConfig?.managerRequested&&<button disabled={busy} onClick={()=>action("start")} className="rounded-2xl bg-[var(--theme-accent)] px-6 py-4 font-black text-black disabled:opacity-50">{busy?"вЂ¦":"Р—Р°РїСѓСЃС‚РёС‚СЊ РјР°С‚С‡"}</button>}{participant&&["WAITING_FOR_PLAYERS","READY"].includes(m.status)&&user?.id===m.playerOneId&&<button disabled={busy} onClick={()=>setCancelOpen(true)} className="cancel-match rounded-2xl border border-red-400/20 px-5 py-3 font-bold text-red-300">{t.cancel}</button>}</div>
    <div className="mt-7 grid gap-3 sm:grid-cols-3"><Info a="Р‘РђРќРљ" b={`$${pot.toFixed(2)}`}/><Info a="РљРћРњРРЎРЎРРЇ" b={`$${Number(m.commission).toFixed(2)}`}/><Info a="РџРћР‘Р•Р”РРўР•Р›Р¬ РџРћР›РЈР§РРў" b={`$${payout.toFixed(2)}`}/></div>
   </div>
  </section>
 </main></>
}
function PlayerCard({player,avatar,crown,bet,ready}:{player:Player|null;avatar:string;crown?:boolean;bet:number;ready:boolean}){return <div className="rounded-2xl border border-white/7 bg-white/[.025] p-5"><div className="flex items-center gap-4"><img src={avatar} alt="" className="h-16 w-16 rounded-2xl object-cover border border-white/10"/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="truncate">{player?.nickname||"РћР¶РёРґР°РЅРёРµ РёРіСЂРѕРєР°..."}</b>{crown&&<span title="РЎРѕР·РґР°С‚РµР»СЊ РґСѓСЌР»Рё" className="text-lg">рџ‘‘</span>}</div><div className="mt-1 text-xs text-zinc-500">{player?`РЎС‚Р°РІРєР° $${bet.toFixed(2)}`:"Р“РѕС‚РѕРІ РїРѕРґРєР»СЋС‡РёС‚СЊСЃСЏ"}</div></div></div><div className={`mt-5 inline-flex rounded-full px-3 py-1 text-[10px] font-black tracking-wider ${ready?"bg-emerald-400/10 text-emerald-300":"bg-amber-400/10 text-amber-300"}`}>{ready?"READY":"РћР–РР”РђРќРР•"}</div></div>}
function Notice({title,children,gold}:{title:string;children:React.ReactNode;gold?:boolean}){return <div className={`mt-5 rounded-2xl border p-5 ${gold?"border-amber-400/25 bg-amber-400/[.06]":"border-[var(--theme-accent)]/20 bg-[var(--theme-accent-bg)]"}`}><div className={`flex items-center gap-2 text-sm font-black ${gold?"text-amber-300":"text-[var(--theme-accent)]"}`}>{gold&&<span>в—Џ</span>}{title}</div><p className="mt-2 text-sm leading-6 text-zinc-400">{children}</p></div>}
function Info({a,b}:{a:string;b:string}){return <div className="rounded-2xl border border-white/5 bg-white/[.025] p-4"><div className="text-[10px] font-black tracking-wider text-zinc-600">{a}</div><div className="mt-1 font-black text-white">{b}</div></div>}


