"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect,useRef,useState } from "react";
import CenterModal from "@/components/Common/CenterModal";
import { useLanguage } from "@/components/Common/LanguageContext";
import { useAuth } from "@/components/Common/AuthContext";
import { languages } from "@/lib/language";
const MAP_IMAGES:Record<string,string>={Mirage:"/images/maps/mirage.jpg",Dust2:"/images/maps/dust2.jpg",Ancient:"/images/maps/ancient.jpg",Train:"/images/maps/train.jpg",Overpass:"/images/maps/overpass.jpg",Inferno:"/images/maps/inferno.jpg",Nuke:"/images/maps/nuke.jpg",Anubis:"/images/maps/anubis.jpg"};
type Player={id?:string;nickname:string;avatarUrl:string|null;steamAvatarUrl?:string|null};
type Match={id:string;playerOneId:string;playerTwoId:string|null;status:string;mode:string;mapName:string|null;betAmount:string|number;commission:string|number;playerOne:Player;playerTwo:Player|null;winner?:Player|null;serverConfig?:{connectUrl?:string|null;state?:string;managerRequested?:boolean;localTest?:boolean}|null;createdAt?:string;updatedAt?:string;startedAt?:string|null;endedAt?:string|null};
const MATCH_UI:any={
 RU:{matchTitle:"Матч",created:"Создан",player2:"Игрок 2",server:"Сервер",game:"Игра",result:"Результат",map:"Карта",bet:"Ставка",waiting:"Ожидание игрока",waitingText:"Ожидаем второго игрока. После его подключения и подтверждения ставки дуэль перейдёт к запуску сервера CS2.",ready:"Матч готов",serverStarting:"Сервер DuelPlay запускается автоматически. Как только он будет готов, появится кнопка подключения.",bothReady:"Оба игрока готовы. Нажмите Start, чтобы запустить сервер.",inProgress:"Матч в процессе",serverAuto:"Результат определяет сервер CS2 автоматически.",connect:"Подключиться к серверу",reconnect:"Переподключиться к серверу",connecting:"Подключение…",timeout:"Автоматическая отмена через",confirmed:"Результат подтверждён сервером",winner:"Победитель",payout:"Выплата",cancelled:"Матч отменён",refund:"Ставки возвращены согласно правилам DuelPlay.",start:"START",bank:"БАНК",commission:"КОМИССИЯ",winnerGets:"ПОБЕДИТЕЛЬ ПОЛУЧИТ",cancelMatch:"Отмена матча",confirmation:"Подтверждение",cancelQuestion:"Отменить дуэль?",cancelText:"Ставка будет возвращена тебе, а если второй игрок уже присоединился — и ему. Отмена необратима.",keep:"Оставить матч",yesCancel:"Да, отменить",cancelling:"Отмена…",creator:"Создатель дуэли",readyConnect:"Готов подключиться",waitingStatus:"ОЖИДАНИЕ",waitingPlayer:"Ожидание игрока...",readyStatus:"ГОТОВ",localTest:"ЛОКАЛЬНЫЙ ТЕСТ",localTestText:"Сервер смоделирован локально. Можно выбрать победителя для проверки выплаты.",testWin:"Победа",testFinish:"Завершить тест"},
 UA:{matchTitle:"Матч",created:"Створено",player2:"Гравець 2",server:"Сервер",game:"Гра",result:"Результат",map:"Карта",bet:"Ставка",waiting:"Очікування гравця",waitingText:"Очікуємо другого гравця. Після його підключення та підтвердження ставки дуель перейде до запуску сервера CS2.",ready:"Матч готовий",serverStarting:"Сервер DuelPlay запускається автоматично. Щойно він буде готовий, з’явиться кнопка підключення.",bothReady:"Обидва гравці готові. Натисніть Start, щоб запустити сервер.",inProgress:"Матч триває",serverAuto:"Результат автоматично визначає сервер CS2.",connect:"Підключитися до сервера",reconnect:"Перепідключитися до сервера",connecting:"Підключення…",timeout:"Автоматичне скасування через",confirmed:"Результат підтверджено сервером",winner:"Переможець",payout:"Виплата",cancelled:"Матч скасовано",refund:"Ставки повернено згідно з правилами DuelPlay.",start:"START",bank:"БАНК",commission:"КОМІСІЯ",winnerGets:"ПЕРЕМОЖЕЦЬ ОТРИМАЄ",cancelMatch:"Скасування матчу",confirmation:"Підтвердження",cancelQuestion:"Скасувати дуель?",cancelText:"Ставку буде повернено тобі, а якщо другий гравець уже приєднався — і йому. Скасування незворотне.",keep:"Залишити матч",yesCancel:"Так, скасувати",cancelling:"Скасування…",creator:"Творець дуелі",readyConnect:"Готовий підключитися",waitingStatus:"ОЧІКУВАННЯ",waitingPlayer:"Очікування гравця...",readyStatus:"ГОТОВИЙ",localTest:"ЛОКАЛЬНИЙ ТЕСТ",localTestText:"Сервер змодельовано локально. Можна обрати переможця для перевірки виплати.",testWin:"Перемога",testFinish:"Завершити тест"},
 EN:{matchTitle:"Match",created:"Created",player2:"Player 2",server:"Server",game:"Game",result:"Result",map:"Map",bet:"Bet",waiting:"Waiting for player",waitingText:"Waiting for the second player. After they connect and confirm the stake, the duel will move to CS2 server startup.",ready:"Match ready",serverStarting:"The DuelPlay server starts automatically. Once ready, the connection button will appear.",bothReady:"Both players are ready. Press Start to launch the server.",inProgress:"Match in progress",serverAuto:"The CS2 server determines the result automatically.",connect:"Connect to server",reconnect:"Reconnect to server",connecting:"Connecting…",timeout:"Automatic cancellation in",confirmed:"Result confirmed by server",winner:"Winner",payout:"Payout",cancelled:"Match cancelled",refund:"Stakes were returned according to DuelPlay rules.",start:"START",bank:"BANK",commission:"COMMISSION",winnerGets:"WINNER GETS",cancelMatch:"Cancel match",confirmation:"Confirmation",cancelQuestion:"Cancel the duel?",cancelText:"Your stake will be returned, and if the second player has already joined, theirs will be returned too. Cancellation cannot be undone.",keep:"Keep match",yesCancel:"Yes, cancel",cancelling:"Cancelling…",creator:"Duel creator",readyConnect:"Ready to connect",waitingStatus:"WAITING",waitingPlayer:"Waiting for player...",readyStatus:"READY",localTest:"LOCAL TEST",localTestText:"The server is simulated locally. Choose a winner to test the payout flow.",testWin:"Win",testFinish:"Finish test"},
 PL:{matchTitle:"Mecz",created:"Utworzono",player2:"Gracz 2",server:"Serwer",game:"Gra",result:"Wynik",map:"Mapa",bet:"Stawka",waiting:"Oczekiwanie na gracza",waitingText:"Czekamy na drugiego gracza. Po jego dołączeniu i potwierdzeniu stawki pojedynek przejdzie do uruchomienia serwera CS2.",ready:"Mecz gotowy",serverStarting:"Serwer DuelPlay uruchamia się automatycznie. Gdy będzie gotowy, pojawi się przycisk połączenia.",bothReady:"Obaj gracze są gotowi. Naciśnij Start, aby uruchomić serwer.",inProgress:"Mecz trwa",serverAuto:"Serwer CS2 automatycznie określa wynik.",connect:"Połącz z serwerem",reconnect:"Połącz ponownie z serwerem",connecting:"Łączenie…",timeout:"Automatyczne anulowanie za",confirmed:"Wynik potwierdzony przez serwer",winner:"Zwycięzca",payout:"Wypłata",cancelled:"Mecz anulowany",refund:"Stawki zwrócono zgodnie z zasadami DuelPlay.",start:"START",bank:"PULA",commission:"PROWIZJA",winnerGets:"ZWYCIĘZCA OTRZYMA",cancelMatch:"Anulowanie meczu",confirmation:"Potwierdzenie",cancelQuestion:"Anulować pojedynek?",cancelText:"Twoja stawka zostanie zwrócona, a jeśli drugi gracz już dołączył — również jego. Anulowania nie można cofnąć.",keep:"Zostaw mecz",yesCancel:"Tak, anuluj",cancelling:"Anulowanie…",creator:"Twórca pojedynku",readyConnect:"Gotowy do połączenia",waitingStatus:"OCZEKIWANIE",waitingPlayer:"Oczekiwanie na gracza...",readyStatus:"GOTOWY",localTest:"TEST LOKALNY",localTestText:"Serwer jest symulowany lokalnie. Wybierz zwycięzcę, aby sprawdzić wypłatę.",testWin:"Wygrana",testFinish:"Zakończ test"}
};
export default function MatchPage({params}:{params:Promise<{id:string}>}){
 const{language,t}=useLanguage();const{refresh:refreshAuth}=useAuth();const u=MATCH_UI[language]||MATCH_UI.RU;const steps=[u.created,u.player2,u.readyStatus,u.server,u.game,u.result];const[id,setId]=useState("");const[m,setM]=useState<Match|null>(null);const[user,setUser]=useState<any>(null);const[msg,setMsg]=useState("");const msgTimer=useRef<number|null>(null);const[busy,setBusy]=useState(false);const[cancelOpen,setCancelOpen]=useState(false);const[connectClicked,setConnectClicked]=useState(false);const[secondsLeft,setSecondsLeft]=useState<number|null>(null);
 useEffect(()=>{params.then(p=>{setId(p.id);try{setConnectClicked(localStorage.getItem(`duelplay-connect-${p.id}`)==="1")}catch{}})},[params]);
 async function load(){if(!id)return;try{const [mr,ur]=await Promise.all([fetch(`/api/matches/${id}`,{cache:"no-store"}),fetch("/api/auth/me",{cache:"no-store"})]);const md=await mr.json(),ud=await ur.json();if(!mr.ok)throw 0;setM(md.match??md);setUser(ud.user??null)}catch{setMsg(t.matchLoadError)}}
 useEffect(()=>{load()},[id]);useEffect(()=>{if(!id)return;const timer=setInterval(load,3000);return()=>clearInterval(timer)},[id]);
 useEffect(()=>{
 if(!m)return;
 if(!["WAITING_FOR_PLAYERS","READY"].includes(m.status)){setSecondsLeft(null);return}
 const base=m.status==="WAITING_FOR_PLAYERS"?m.createdAt:m.updatedAt;
 if(!base){setSecondsLeft(null);return}
 const timeoutMs=m.status==="WAITING_FOR_PLAYERS"?10*60*1000:5*60*1000;
 const update=()=>{
   const left=Math.max(0,Math.ceil((new Date(base).getTime()+timeoutMs-Date.now())/1000));
   setSecondsLeft(left);
   if(left<=0)load();
 };
 update();
 const timer=setInterval(update,1000);
 return()=>clearInterval(timer);
},[m?.status,m?.createdAt,m?.updatedAt,id]);

function formatCountdown(total:number){
 const min=Math.floor(total/60).toString().padStart(2,"0");
 const sec=(total%60).toString().padStart(2,"0");
 return `${min}:${sec}`;
}

function openServer(){
 if(!m?.serverConfig?.connectUrl)return;
 setConnectClicked(true);
 try{localStorage.setItem(`duelplay-connect-${m.id}`,"1")}catch{}
 window.location.href=m.serverConfig.connectUrl;
}

function showMessage(text:string){if(msgTimer.current)window.clearTimeout(msgTimer.current);setMsg(text);msgTimer.current=window.setTimeout(()=>setMsg(""),5000)}
useEffect(()=>()=>{if(msgTimer.current)window.clearTimeout(msgTimer.current)},[]);
useEffect(()=>{
 if(!msg)return;
 const steamMessages=Object.values(languages).map((x:any)=>String(x.steamAccountRequired));
 if(steamMessages.includes(msg))setMsg(t.steamAccountRequired);
},[language,t.steamAccountRequired]);
async function action(path:string){setBusy(true);setMsg("");try{const r=await fetch(`/api/matches/${id}/${path}`,{method:"POST"});const d=await r.json();if(!r.ok){const code=String(d.errorCode||"").trim().toUpperCase();const raw=String(d.error||"").trim();const rawLower=raw.toLowerCase();const joinErrors:Record<string,string>={AUTH_REQUIRED:t.loginRequired,OWN_MATCH:t.ownMatch,MATCH_FULL:t.full,INSUFFICIENT_BALANCE:t.walletRequired,JOIN_ERROR:t.joinError};const startErrors:Record<string,string>={AUTH_REQUIRED:t.loginRequired,STEAM_REQUIRED:t.steamAccountRequired,NOT_READY:t.startError,NOT_PARTICIPANT:t.startError,START_ERROR:t.startError};const isOwn=rawLower.includes("своему матчу")||rawLower.includes("own match")||rawLower.includes("własnego meczu")||rawLower.includes("власного матчу");const isFull=rawLower.includes("матч уже заполнен")||rawLower.includes("match is full")||rawLower.includes("mecz jest pełny")||rawLower.includes("матч уже заповнений");const localized=path==="join"?(joinErrors[code]||(isOwn?t.ownMatch:isFull?t.full:t.joinError)):(startErrors[code]||t.startError);throw new Error(localized||"ERROR")}await load();await refreshAuth();if(path==="start")showMessage(t.matchStarted);if(path==="join")showMessage(t.bothReady)}catch(e){showMessage(e instanceof Error?e.message:(path==="join"?t.joinError:t.startError))}finally{setBusy(false)}}
async function localFinish(winnerId:string){setBusy(true);setMsg("");try{const r=await fetch(`/api/matches/${id}/local-test`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({winnerId})});const d=await r.json();if(!r.ok)throw new Error(d.error||t.startError);await load();await refreshAuth();showMessage(t.finished)}catch(e){showMessage(e instanceof Error?e.message:t.startError)}finally{setBusy(false)}}
 if(!m)return <><main className="min-h-screen pt-28 text-center text-zinc-500">{t.loading}</main></>;
 const pot=Number(m.betAmount)*(m.playerTwo?2:1),payout=pot-Number(m.commission??pot*.10),participant=Boolean(user&&[m.playerOneId,m.playerTwoId].includes(user.id));const mapImage=MAP_IMAGES[m.mapName||""];
 const statusLabel=(status:string)=>({WAITING_FOR_PLAYERS:u.waitingStatus,READY:u.readyStatus,LIVE:"LIVE",FINISHED:u.confirmed,CANCELLED:u.cancelled}[status]||status);
 const activeStep=m.status==="WAITING_FOR_PLAYERS"?1:m.status==="READY"?3:m.status==="LIVE"?5:m.status==="FINISHED"?6:1;
 const p1=m.playerOne?.avatarUrl||m.playerOne?.steamAvatarUrl||"/avatars/premium/01-cyan.svg",p2=m.playerTwo?.avatarUrl||m.playerTwo?.steamAvatarUrl||"/avatars/premium/02-violet.svg";
 return <><main className="mx-auto min-h-screen max-w-6xl px-4 pb-20 pt-24 sm:px-6">
  <div className="mb-4 flex items-center justify-between gap-3"><Link href="/matches" className="text-sm font-bold text-zinc-500 hover:text-[var(--theme-accent)]">← {t.backMatches}</Link><span className={`status ${m.status==="LIVE"?"live":"waiting"}`}>{statusLabel(m.status)}</span></div>
  <section className="panel overflow-hidden rounded-[28px]">
   <div className="relative h-56 sm:h-72"><Image src={mapImage||"/images/maps/mirage.jpg"} alt={m.mapName||"CS2"} fill className="object-cover"/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,5,7,.96),rgba(5,5,7,.35),rgba(5,5,7,.96))]"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(255,47,145,.18),transparent_45%)]"/><div className="absolute inset-x-5 bottom-7 text-center"><div className="text-xs font-black tracking-[.25em] text-[var(--theme-accent)]">CS2 · 1х1 DUEL</div><h1 className="mt-2 text-3xl font-black sm:text-5xl">{u.matchTitle} #{m.id.slice(0,8).toUpperCase()}</h1><p className="mt-2 text-sm text-zinc-400">{m.mapName||"Mirage"} · 1х1 · ${Number(m.betAmount).toFixed(2)}</p></div></div>
   <div className="p-5 sm:p-8">
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-6">{steps.map((s,i)=><div key={s} className="flex flex-col items-center gap-2 text-center"><span className={`step-circle ${i+1<=activeStep?"active":""}`}>{i+1}</span><span className={`text-[11px] ${i+1<=activeStep?"text-white":"text-zinc-600"}`}>{s}</span></div>)}</div>
    <div className="mt-7 grid gap-4 lg:grid-cols-[1fr_auto_1fr_auto] lg:items-stretch">
      <PlayerCard player={m.playerOne} avatar={p1} crown={true} bet={Number(m.betAmount)} ready={m.status!=="WAITING_FOR_PLAYERS"} u={u}/><div className="hidden items-center justify-center lg:flex text-2xl font-black text-[var(--theme-accent)]">VS</div>
      <PlayerCard player={m.playerTwo} avatar={p2} bet={Number(m.betAmount)} ready={Boolean(m.playerTwo)} u={u}/><div className="rounded-2xl border border-white/5 bg-white/[.025] p-4 lg:w-56"><div className="text-xs uppercase tracking-wider text-zinc-600">{u.map}</div><div className="mt-2 overflow-hidden rounded-xl"><Image src={mapImage||"/images/maps/mirage.jpg"} alt="" width={320} height={150} className="h-24 w-full object-cover"/></div><div className="mt-3 flex justify-between text-sm"><b>{m.mapName||"Mirage"}</b><span className="text-zinc-500">1х1</span></div><div className="mt-1 text-xs text-zinc-500">{u.bet} <b className="text-white">${Number(m.betAmount).toFixed(2)}</b></div></div>
    </div>
    {m.status==="WAITING_FOR_PLAYERS"&&<>
      <div className="mt-5 rounded-2xl border border-amber-400/20 bg-amber-400/[.04] p-5"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2 text-sm font-black text-amber-300">{u.waiting}</div><p className="mt-2 text-sm leading-6 text-zinc-400">{u.waitingText}</p></div>{secondsLeft!==null&&<div className="shrink-0 text-right"><div className="text-[10px] font-black uppercase tracking-wider text-amber-400/60">{u.timeout}</div><div className="mt-1 font-mono text-2xl font-black tracking-wider text-amber-200">{formatCountdown(secondsLeft)}</div></div>}</div></div>
      {!participant&&user?.id!==m.playerOneId&&<div className="mt-5 flex justify-center">
        <button disabled={busy} onClick={()=>action("join")} className="w-full rounded-2xl bg-[var(--theme-accent)] px-6 py-4 text-base font-black text-black shadow-[0_0_28px_var(--theme-glow)] transition hover:brightness-110 active:scale-[.99] disabled:cursor-not-allowed disabled:opacity-50 sm:w-auto sm:min-w-[320px]">
          {busy?t.joining:`${t.join} · $${Number(m.betAmount).toFixed(2)}`}
        </button>
      </div>}
    </>}
    {m.status==="READY"&&<div className="mt-5 rounded-2xl border border-amber-400/20 bg-amber-400/[.04] p-5"><div className="flex items-center justify-between gap-4"><div className="min-w-0"><div className="text-sm font-black text-amber-300">{u.ready}</div><div className="mt-1 text-sm text-zinc-500">{m.serverConfig?.managerRequested?u.serverStarting:u.bothReady}</div></div>{secondsLeft!==null&&<div className="shrink-0 text-right"><div className="text-[10px] font-black uppercase tracking-wider text-amber-400/60">{u.timeout}</div><div className="mt-1 font-mono text-2xl font-black tracking-wider text-amber-200">{formatCountdown(secondsLeft)}</div></div>}</div></div>}
    {m.status==="LIVE"&&<div className="mt-5 rounded-2xl border border-emerald-400/20 bg-emerald-400/[.05] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2 text-sm font-black text-emerald-300"><span className="site-live-dot"/> {u.inProgress}</div><p className="mt-1 text-sm text-zinc-500">{m.serverConfig?.localTest?u.localTestText:u.serverAuto}</p></div><span className="status live">LIVE</span></div>{m.serverConfig?.localTest&&m.playerTwo&&<div className="mt-5 rounded-xl border border-amber-400/20 bg-amber-400/[.04] p-4"><div className="text-xs font-black tracking-wider text-amber-300">{u.localTest}</div><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>localFinish(m.playerOneId)} className="rounded-xl bg-[var(--theme-accent)] px-4 py-3 text-sm font-black text-black disabled:opacity-50">{u.testWin}: {m.playerOne.nickname}</button><button disabled={busy} onClick={()=>m.playerTwo&&localFinish(m.playerTwo.id||"")} className="rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm font-black disabled:opacity-50">{u.testWin}: {m.playerTwo.nickname}</button></div></div>}{m.serverConfig?.connectUrl&&<div className="mt-5 flex flex-wrap gap-3"><button type="button" onClick={openServer} disabled={!m.serverConfig.connectUrl||busy} className="inline-flex min-h-[48px] min-w-[220px] items-center justify-center rounded-xl border border-emerald-400/25 bg-emerald-400/[.03] px-5 py-3 text-sm font-black text-emerald-300 transition hover:bg-emerald-400/10 disabled:opacity-60">{busy?u.connecting:(connectClicked?u.reconnect:u.connect)}</button></div>}</div>}
    {m.status==="FINISHED"&&<Notice title={u.confirmed}>{u.winner}: <b>{m.winner?.nickname||"—"}</b> · {u.payout} <b>${payout.toFixed(2)}</b></Notice>}
    {m.status==="CANCELLED"&&<Notice title={u.cancelled}>{u.refund}</Notice>}
    {msg&&<div aria-live="polite" className="mt-4 rounded-xl border border-white/10 bg-white/[.03] p-4 text-sm text-[var(--theme-accent)]">{msg}</div>}
    <div className="mt-6 flex flex-wrap gap-3">{participant&&m.status==="READY"&&!m.serverConfig?.managerRequested&&<button disabled={busy} onClick={()=>action("start")} className="rounded-2xl bg-[var(--theme-accent)] px-6 py-4 font-black text-black disabled:opacity-50">{busy?"…":u.start}</button>}{participant&&["WAITING_FOR_PLAYERS","READY"].includes(m.status)&&user?.id===m.playerOneId&&<button disabled={busy} onClick={()=>setCancelOpen(true)} className="cancel-match rounded-2xl border border-red-400/20 px-5 py-3 font-bold text-red-300">{t.cancel}</button>}</div>
    <div className="mt-7 grid gap-3 sm:grid-cols-3"><Info a={u.bank} b={`$${pot.toFixed(2)}`}/><Info a={u.commission} b={`$${Number(m.commission).toFixed(2)}`}/><Info a={u.winnerGets} b={`$${payout.toFixed(2)}`}/></div>
   </div>
  </section>
  <CenterModal open={cancelOpen} title={u.cancelMatch} onClose={()=>{if(!busy)setCancelOpen(false)}}>
    <div className="rounded-2xl border border-red-400/15 bg-red-400/[.04] p-5">
      <div className="text-xs font-black uppercase tracking-widest text-red-300">{u.confirmation}</div>
      <h3 className="mt-2 text-xl font-black">{u.cancelQuestion}</h3>
      <p className="mt-2 text-sm leading-6 text-zinc-400">{u.cancelText}</p>
    </div>
    <div className="mt-5 flex gap-3"><button onClick={()=>setCancelOpen(false)} className="flex-1 rounded-2xl border border-white/10 py-3 font-bold">{u.keep}</button><button disabled={busy} onClick={async()=>{setCancelOpen(false);await action("cancel")}} className="flex-1 rounded-2xl bg-red-500/90 py-3 font-black text-white disabled:opacity-50">{busy?u.cancelling:u.yesCancel}</button></div>
  </CenterModal>
 </main></>
}
function PlayerCard({player,avatar,crown,bet,ready,u}:{player:Player|null;avatar:string;crown?:boolean;bet:number;ready:boolean;u:any}){return <div className="rounded-2xl border border-white/7 bg-white/[.025] p-5"><div className="flex items-center gap-4"><img src={avatar} alt="" className="h-16 w-16 rounded-2xl object-cover border border-white/10"/><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><b className="truncate">{player?.nickname||u.waitingPlayer}</b>{crown&&<span title={u.creator} className="text-lg">👑</span>}</div><div className="mt-1 text-xs text-zinc-500">{player?`${u.bet} $${bet.toFixed(2)}`:u.readyConnect}</div></div></div><div className={`mt-5 inline-flex rounded-full px-3 py-1 text-[10px] font-black tracking-wider ${ready?"bg-emerald-400/10 text-emerald-300":"bg-amber-400/10 text-amber-300"}`}>{ready?"READY":u.waitingStatus}</div></div>}
function Notice({title,children,gold}:{title:string;children:React.ReactNode;gold?:boolean}){return <div className={`mt-5 rounded-2xl border p-5 ${gold?"border-amber-400/25 bg-amber-400/[.06]":"border-[var(--theme-accent)]/20 bg-[var(--theme-accent-bg)]"}`}><div className={`flex items-center gap-2 text-sm font-black ${gold?"text-amber-300":"text-[var(--theme-accent)]"}`}>{gold&&<span>●</span>}{title}</div><p className="mt-2 text-sm leading-6 text-zinc-400">{children}</p></div>}
function Info({a,b}:{a:string;b:string}){return <div className="rounded-2xl border border-white/5 bg-white/[.025] p-4"><div className="text-[10px] font-black tracking-wider text-zinc-600">{a}</div><div className="mt-1 font-black text-white">{b}</div></div>}

