"use client";
import { useEffect, useState } from "react";
import Header from "@/components/Header/Header";
import { useLanguage } from "@/components/Common/LanguageContext";

type RankedUser={nickname:string;reputation:number;level:number;xp:number;avatarUrl:string|null};
const fallbackAvatar="/avatars/premium/01-cyan.svg";

export default function RatingPage(){
 const{t}=useLanguage();const[users,setUsers]=useState<RankedUser[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{fetch("/api/ranking",{cache:"no-store"}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error("RATING_LOAD_ERROR");setUsers(Array.isArray(d)?d:[])}).catch(()=>setError(t.ratingLoadError)).finally(()=>setLoading(false))},[]);
 const top=users.slice(0,3);const rest=users.slice(3);
 return <><Header/><main className="mx-auto min-h-screen max-w-7xl px-4 pb-20 pt-28 sm:px-6"><section className="panel overflow-hidden rounded-3xl p-7 sm:p-10"><div className="max-w-3xl"><span className="pill w-fit">{t.rating}</span><h1 className="mt-4 text-4xl font-black sm:text-5xl">{t.ratingTitle}</h1><p className="mt-3 text-zinc-500">{t.ratingText}</p></div>{loading?<div className="mt-10 rounded-2xl bg-white/[.03] p-10 text-center text-zinc-500">{t.loading}</div>:error?<div className="mt-10 rounded-2xl border border-red-400/20 bg-red-400/5 p-8 text-center text-red-300">{error}</div>:top.length===0?<div className="mt-10 rounded-2xl bg-white/[.03] p-10 text-center text-zinc-500">{t.noHistory}</div>:<><div className="mt-12 grid items-end gap-5 md:grid-cols-[1fr_1.15fr_1fr]">{top[1]&&<PodiumCard user={top[1]} rank={2}/>}<PodiumCard user={top[0]} rank={1}/>{top[2]&&<PodiumCard user={top[2]} rank={3}/>}</div>{rest.length>0&&<div className="mt-10"><div className="mb-4 flex items-end justify-between"><div><div className="text-xs font-black uppercase tracking-[.18em] text-pink-300">{t.topPlayers}</div><h2 className="mt-1 text-2xl font-black">DuelPlay Ranking</h2></div><span className="text-xs text-zinc-600">{users.length} {t.playersCount}</span></div><div className="overflow-hidden rounded-2xl border border-white/5 bg-white/[.015]">{rest.map((u,i)=><RankRow key={`${u.nickname}-${i}`} user={u} rank={i+4}/>)}</div></div>}</>}</section></main></>}

function PodiumCard({user,rank}:{user:RankedUser;rank:number}){const first=rank===1;const avatar=user.avatarUrl||fallbackAvatar;return <article className={`relative overflow-hidden rounded-3xl border ${first?"border-pink-400/35 bg-pink-400/[.06] md:-translate-y-5":"border-white/8 bg-white/[.025]"} p-6 text-center shadow-[0_20px_70px_rgba(0,0,0,.25)] transition duration-300 hover:-translate-y-2 hover:border-pink-400/30`}><div className="absolute inset-x-0 top-0 h-28 bg-gradient-to-b from-pink-400/[.12] to-transparent"/><div className="relative mx-auto w-fit"><div className={`${first?"h-28 w-28":"h-24 w-24"} aspect-square overflow-hidden rounded-3xl border-2 ${first?"border-pink-300/70":"border-white/15"} bg-black shadow-[0_12px_35px_rgba(0,0,0,.35)]`}><img src={avatar} alt="" className="avatar-square" onError={e=>{e.currentTarget.src=fallbackAvatar}}/></div><span className={`absolute -bottom-3 left-1/2 -translate-x-1/2 rounded-full border px-3 py-1 text-xs font-black ${first?"border-pink-300/30 bg-pink-400 text-black":"border-white/10 bg-[#0b0e13] text-pink-300"}`}>#{rank}</span></div><h2 className="mt-8 truncate text-xl font-black">{user.nickname}</h2><div className="mt-2 text-3xl font-black text-pink-400">{user.reputation}<span className="ml-1 text-xs text-zinc-500">REP</span></div><div className="mt-2 text-xs text-zinc-500">Level {user.level} · {user.xp} XP</div><div className="mx-auto mt-5 h-1 max-w-32 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-pink-400" style={{width:`${Math.min(100,Math.max(8,(user.reputation/1200)*100))}%`}}/></div></article>}
function RankRow({user,rank}:{user:RankedUser;rank:number}){const avatar=user.avatarUrl||fallbackAvatar;return <div className="group flex items-center gap-4 border-b border-white/5 px-4 py-4 last:border-b-0 transition hover:bg-white/[.035]"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white/[.035] text-xs font-black text-pink-300">#{rank}</span><div className="h-12 w-12 shrink-0 overflow-hidden rounded-xl border border-white/10 bg-black"><img src={avatar} alt="" className="avatar-square" onError={e=>{e.currentTarget.src=fallbackAvatar}}/></div><div className="min-w-0 flex-1"><div className="truncate font-bold">{user.nickname}</div><div className="mt-1 text-xs text-zinc-600">Level {user.level} · {user.xp} XP</div></div><div className="hidden h-1.5 w-28 overflow-hidden rounded-full bg-white/5 sm:block"><div className="h-full rounded-full bg-pink-400/70" style={{width:`${Math.min(100,Math.max(8,(user.reputation/1200)*100))}%`}}/></div><div className="text-right font-black text-pink-400">{user.reputation}<div className="text-[10px] text-zinc-600">REP</div></div></div>}
