"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useLanguage } from "@/components/Common/LanguageContext";

type Row={id:string;nickname:string;avatarUrl:string|null;level:number;xp:number;rating:number;wins:number;losses:number;played:number;position:number;league:string};
const periods=["global","daily","weekly","seasonal"] as const;
type Period=typeof periods[number];

export default function RatingPage(){
 const{t}=useLanguage(); const ru=t.leaderboardLabels;
 const [period,setPeriod]=useState<Period>("global"),[rows,setRows]=useState<Row[]>([]),[season,setSeason]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const label=ru;
 async function load(p:Period){setLoading(true);setError("");try{const r=await fetch(`/api/leaderboards?period=${p}&limit=100`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Leaderboard error");setRows(Array.isArray(d.rows)?d.rows:[]);setSeason(d.season||null)}catch(e){setError(e instanceof Error?e.message:"Leaderboard error");setRows([])}finally{setLoading(false)}}
 useEffect(()=>{void load(period)},[period]);
 const title=t.ratingTitle;
 return <main className="mx-auto min-h-screen max-w-7xl px-4 pb-20 pt-28 sm:px-6"><section className="panel overflow-hidden rounded-3xl p-7 sm:p-10"><div className="max-w-3xl"><span className="pill">RANKING</span><h1 className="mt-4 text-4xl font-black sm:text-5xl">{title}</h1><p className="mt-3 text-zinc-500">{t.ratingText}</p></div><div className="mt-8 flex flex-wrap gap-2">{periods.map(p=><button key={p} onClick={()=>setPeriod(p)} className={`rounded-xl px-4 py-2 text-sm font-bold transition ${period===p?"bg-pink-400 text-black":"bg-white/[.035] text-zinc-400 hover:text-white"}`}>{label[p]}</button>)}</div>{period==="seasonal"&&season&&<div className="mt-4 rounded-2xl border border-pink-400/15 bg-pink-400/[.04] p-4 text-sm"><b>{season.name}</b><span className="ml-2 text-zinc-500">{new Date(season.startsAt).toLocaleDateString()} — {new Date(season.endsAt).toLocaleDateString()}</span></div>}{loading?<div className="mt-8 rounded-2xl bg-white/[.03] p-10 text-center text-zinc-500">Loading…</div>:error?<div className="mt-8 rounded-2xl border border-red-400/20 bg-red-400/5 p-8 text-center text-red-300">{error}</div>:rows.length===0?<div className="mt-8 rounded-2xl bg-white/[.03] p-10 text-center text-zinc-500">{t.noResults}</div>:<div className="mt-8 overflow-hidden rounded-2xl border border-white/5 bg-white/[.015]"><div className="hidden grid-cols-[64px_1fr_100px_90px_90px_100px] gap-3 border-b border-white/5 px-4 py-3 text-[10px] font-black uppercase tracking-wider text-zinc-600 sm:grid"><span>#</span><span>Player</span><span>Rating</span><span>W</span><span>L</span><span>League</span></div>{rows.map(x=><Link href={`/profile/${encodeURIComponent(x.nickname)}`} key={x.id} className="grid grid-cols-[44px_1fr_auto] items-center gap-3 border-b border-white/5 px-4 py-4 last:border-b-0 transition hover:bg-white/[.035] sm:grid-cols-[64px_1fr_100px_90px_90px_100px]"><span className="font-black text-pink-300">#{x.position}</span><span className="flex min-w-0 items-center gap-3"><img src={x.avatarUrl||"/avatars/premium/01-cyan.svg"} alt="" className="h-10 w-10 shrink-0 rounded-xl object-cover"/><span className="min-w-0"><b className="block truncate">{x.nickname}</b><small className="text-zinc-600">Lv.{x.level} · {x.played} {t.matches}</small></span></span><b className="text-pink-400">{x.rating}</b><span className="hidden sm:block text-emerald-300">{x.wins}</span><span className="hidden sm:block text-red-300">{x.losses}</span><span className="hidden sm:block text-xs text-zinc-400">{x.league}</span></Link>)}</div>}</section></main>
}
