ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "allowChallenges" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "allowMessages" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "profileVisibility" VARCHAR(16) NOT NULL DEFAULT 'PUBLIC',
  ADD COLUMN IF NOT EXISTS "showStatsPublic" BOOLEAN NOT NULL DEFAULT true;
