"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useLanguage } from "../../components/Common/LanguageContext";

type Person={id:string;nickname:string;avatarUrl?:string|null;status?:string};
type SocialData={friends:any[];rivals:any[];pendingIncoming:any[];pendingOutgoing:any[];blocked:any[];mutes:any[];unreadMessages:number};
export default function SocialPage(){
 const {t}=useLanguage();
 const [d,setD]=useState<SocialData>({friends:[],rivals:[],pendingIncoming:[],pendingOutgoing:[],blocked:[],mutes:[],unreadMessages:0});
 const [uid,setUid]=useState(""); const [text,setText]=useState(""); const [messages,setMessages]=useState<any[]>([]); const [msg,setMsg]=useState(""); const [busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/social",{cache:"no-store"});const f=await r.json().catch(()=>({}));setD({friends:Array.isArray(f?.friends)?f.friends:[],rivals:Array.isArray(f?.rivals)?f.rivals:[],pendingIncoming:Array.isArray(f?.pendingIncoming)?f.pendingIncoming:[],pendingOutgoing:Array.isArray(f?.pendingOutgoing)?f.pendingOutgoing:[],blocked:Array.isArray(f?.blocked)?f.blocked:[],mutes:Array.isArray(f?.mutes)?f.mutes:[],unreadMessages:Number(f?.unreadMessages||0)})}
 useEffect(()=>{
  void load();
  const tick=()=>{ if(document.visibilityState==="visible") void load(); };
  const id=window.setInterval(tick,15000);
  document.addEventListener("visibilitychange",tick);
  return ()=>{window.clearInterval(id);document.removeEventListener("visibilitychange",tick)};
 },[]);
 async function action(url:string,body:any,method="POST"){setBusy(true);try{const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json().catch(()=>({}));setMsg(r.ok?"✓":x.error||t.error);if(r.ok)await load()}finally{setBusy(false)}}
 async function loadMessages(id=uid){if(!id)return;setUid(id);const r=await fetch("/api/messages?userId="+encodeURIComponent(id),{cache:"no-store"});const x=await r.json().catch(()=>[]);setMessages(Array.isArray(x)?x:[]);void fetch("/api/messages",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({all:true})}).then(()=>load()).catch(()=>{})}
 async function sendMessage(){if(!uid||!text.trim())return;setBusy(true);try{const r=await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({receiverId:uid,body:text.trim()})});const x=await r.json().catch(()=>({}));setMsg(r.ok?"✓":x.error||t.error);if(r.ok){setText("");await loadMessages(uid)}}finally{setBusy(false)}}
 const accepted=d.friends.filter(x=>x.status==="ACCEPTED");
 const friendPerson=(x:any)=>x.person||x.receiver||x.sender;
 return <main className="mx-auto min-h-screen max-w-7xl px-4 pb-20 pt-28"><section className="panel rounded-3xl p-6 sm:p-10">
  <div className="flex flex-wrap items-center gap-3"><span className="pill">SOCIAL CENTER</span>{d.unreadMessages>0&&<span className="rounded-full border border-pink-400/20 bg-pink-400/10 px-3 py-1 text-xs font-black text-pink-300">{d.unreadMessages} unread</span>}</div><h1 className="mt-4 text-4xl font-black">{t.socialTitle}</h1><p className="mt-2 max-w-3xl text-zinc-500">Friends, rivals and private messages in one place.</p>
  <div className="mt-7 grid gap-3 lg:grid-cols-[1fr_auto_auto_auto]"><input className="input" value={uid} onChange={e=>setUid(e.target.value)} placeholder={t.playerId}/><button disabled={busy} onClick={()=>action("/api/friends",{userId:uid,action:"add"})} className="rounded-xl bg-pink-400 px-5 py-3 font-black text-black">+ Friend</button><button disabled={busy} onClick={()=>action("/api/rivals",{targetId:uid})} className="rounded-xl border border-white/10 px-5 py-3 font-bold">Add Rival</button><button disabled={busy} onClick={()=>loadMessages()} className="rounded-xl border border-white/10 px-5 py-3 font-bold">Chat</button></div>{msg&&<p className="mt-3 text-sm text-pink-300">{msg}</p>}
  <div className="mt-8 grid gap-6 lg:grid-cols-2">
   <Panel title={`${t.friends} · ${accepted.length}`}>
    <div className="space-y-2">{accepted.length?accepted.map(x=>{const p=friendPerson(x);return <div key={x.id} className="flex items-center justify-between rounded-xl bg-white/[.025] p-3"><Link href={`/profile/${encodeURIComponent(p.nickname)}`} className="flex items-center gap-3"><img src={p.avatarUrl||"/avatars/premium/01-cyan.svg"} className="h-9 w-9 rounded-xl object-cover" alt=""/><span><b>{p.nickname}</b><span className="ml-2 text-xs text-zinc-600">{p.status||"ACTIVE"}</span></span></Link><div className="flex gap-2"><button disabled={busy} onClick={()=>loadMessages(p.id)} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Message</button><button disabled={busy} onClick={()=>action("/api/friends",{userId:p.id,action:"remove"})} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-zinc-400">Remove</button><button disabled={busy} onClick={()=>action("/api/social",{targetId:p.id,action:d.mutes.some((m:any)=>m.mutedUserId===p.id)?"unmute":"mute"})} className="rounded-lg border border-yellow-400/20 px-3 py-2 text-xs text-yellow-300">{d.mutes.some((m:any)=>m.mutedUserId===p.id)?"Unmute":"Mute"}</button><button disabled={busy} onClick={()=>action("/api/friends",{userId:p.id,action:"block"})} className="rounded-lg border border-red-400/20 px-3 py-2 text-xs text-red-300">Block</button></div></div>;}):<Empty text="No friends yet."/>}</div>
    {d.pendingIncoming.length>0&&<div className="mt-6"><h3 className="font-black">Pending requests · {d.pendingIncoming.length}</h3><div className="mt-3 space-y-2">{d.pendingIncoming.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-white/[.025] p-3"><Link href={`/profile/${encodeURIComponent(x.sender.nickname)}`} className="font-bold hover:text-pink-300">{x.sender.nickname}</Link><div className="flex gap-2"><button disabled={busy} onClick={()=>action("/api/friends",{userId:x.senderId,action:"accept"})} className="rounded-lg bg-emerald-400/15 px-3 py-2 text-xs text-emerald-300">Accept</button><button disabled={busy} onClick={()=>action("/api/friends",{userId:x.senderId,action:"decline"})} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Decline</button></div></div>)}</div></div>}
    {d.pendingOutgoing.length>0&&<div className="mt-6"><h3 className="font-black">Sent requests · {d.pendingOutgoing.length}</h3><div className="mt-3 space-y-2">{d.pendingOutgoing.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-white/[.025] p-3"><Link href={`/profile/${encodeURIComponent(x.receiver.nickname)}`} className="font-bold hover:text-pink-300">{x.receiver.nickname}</Link><button disabled={busy} onClick={()=>action("/api/friends",{userId:x.receiverId,action:"remove"})} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Cancel</button></div>)}</div></div>}
    {d.blocked.length>0&&<div className="mt-6"><h3 className="font-black">Blocked · {d.blocked.length}</h3><div className="mt-3 space-y-2">{d.blocked.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-white/[.025] p-3"><span className="font-bold">{x.receiver.nickname}</span><button disabled={busy} onClick={()=>action("/api/friends",{userId:x.receiverId,action:"unblock"})} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Unblock</button></div>)}</div></div>}
    {d.mutes.length>0&&<div className="mt-6"><h3 className="font-black">Muted · {d.mutes.length}</h3><div className="mt-3 space-y-2">{d.mutes.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-white/[.025] p-3"><span className="font-bold">{x.mutedUser.nickname}</span><button disabled={busy} onClick={()=>action("/api/social",{targetId:x.mutedUserId,action:"unmute"})} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Unmute</button></div>)}</div></div>}
   </Panel>
   <Panel title={`${t.rivals} · ${d.rivals.length}`}><div className="space-y-2">{d.rivals.length?d.rivals.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-white/[.025] p-3"><Link href={`/profile/${encodeURIComponent(x.target.nickname)}`} className="font-bold hover:text-pink-300">⚔ {x.target.nickname}</Link><button disabled={busy} onClick={()=>action(`/api/rivals?targetId=${encodeURIComponent(x.target.id)}`,{},"DELETE")} className="rounded-lg border border-white/10 px-3 py-2 text-xs">Remove</button></div>):<Empty text="No rivals yet."/>}</div></Panel>
  </div>
  <div className="mt-6 rounded-2xl border border-white/5 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black">{t.messages}</h2><p className="text-xs text-zinc-600">Select a friend or enter a player ID to open a private chat.</p></div>{uid&&<Link href={`/profile/${encodeURIComponent(uid)}`} className="text-sm text-pink-400">Open profile →</Link>}</div><div className="mt-4 max-h-72 space-y-2 overflow-auto">{messages.length?messages.map(x=><div key={x.id} className="rounded-xl bg-white/[.025] p-3 text-sm"><b>{x.sender?.nickname||"Player"}</b><span className="ml-2 text-zinc-400">{x.body}</span></div>):<Empty text="No messages in this chat."/>}</div><div className="mt-4 flex gap-2"><input className="input" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void sendMessage()}} placeholder={t.messagePlaceholder}/><button disabled={busy||!uid||!text.trim()} onClick={sendMessage} className="rounded-xl bg-pink-400 px-5 font-black text-black disabled:opacity-40">{t.send}</button></div></div>
  <div className="mt-6 grid gap-3 sm:grid-cols-3"><Link href="/matches" className="rounded-2xl border border-white/5 p-4 hover:border-pink-400/30"><b>⚔ Find a duel</b><span className="mt-1 block text-xs text-zinc-600">Play against the community</span></Link><Link href="/clans" className="rounded-2xl border border-white/5 p-4 hover:border-pink-400/30"><b>🛡 Clans</b><span className="mt-1 block text-xs text-zinc-600">Meet and manage your team</span></Link><Link href="/notifications" className="rounded-2xl border border-white/5 p-4 hover:border-pink-400/30"><b>🔔 Notifications</b><span className="mt-1 block text-xs text-zinc-600">Friend and challenge alerts</span></Link></div>
 </section></main>
}
function PersonRow({person,onAction,actionLabel}:{person:Person;onAction:()=>void;actionLabel:string}){return <div className="flex items-center justify-between rounded-xl bg-white/[.025] p-3"><Link href={`/profile/${encodeURIComponent(person.nickname)}`} className="flex items-center gap-3"><img src={person.avatarUrl||"/avatars/premium/01-cyan.svg"} className="h-9 w-9 rounded-xl object-cover" alt=""/><span><b>{person.nickname}</b><span className="ml-2 text-xs text-zinc-600">{person.status||"ACTIVE"}</span></span></Link><button onClick={onAction} className="rounded-lg border border-white/10 px-3 py-2 text-xs">{actionLabel}</button></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl border border-white/5 p-5"><h2 className="text-xl font-black">{title}</h2><div className="mt-4">{children}</div></section>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-white/5 p-5 text-center text-sm text-zinc-600">{text}</div>}
