import { leagueFromRating } from "@/lib/leagues";
import {NextResponse} from "next/server";
import {prisma} from "@/lib/prisma";
import {getCurrentUser} from "@/lib/current-user";
export async function GET(_:Request,{params}:{params:Promise<{nickname:string}>}){
 const {nickname}=await params;
 const u=await prisma.user.findUnique({where:{nickname},select:{id:true,nickname:true,avatarUrl:true,steamAvatarUrl:true,level:true,xp:true,reputation:true,createdAt:true,profileVisibility:true,showStatsPublic:true,allowChallenges:true,allowMessages:true,achievements:{include:{achievement:true}},matchesAsPlayerOne:{select:{id:true,status:true,mapName:true,winnerId:true,createdAt:true,betAmount:true}},matchesAsPlayerTwo:{select:{id:true,status:true,mapName:true,winnerId:true,createdAt:true,betAmount:true}}}});
 if(!u)return NextResponse.json({error:"Profile not found"},{status:404});
 const [stats,matchStats,clanMemberships,friendsSent,friendsReceived,rivals,rivalOf,collections,me]=await Promise.all([
  prisma.playerStats.findUnique({where:{userId:u.id}}),
  prisma.matchPlayerStat.findMany({where:{userId:u.id},orderBy:{createdAt:"desc"},take:30,select:{kills:true,deaths:true,headshots:true,damage:true,score:true,weapon:true,mapName:true,createdAt:true}}),
  prisma.clanMember.findMany({where:{userId:u.id},include:{clan:{select:{id:true,name:true,tag:true,logoUrl:true,rating:true,wins:true,losses:true}}}}),
  prisma.friend.findMany({where:{senderId:u.id,status:"ACCEPTED"},include:{receiver:{select:{id:true,nickname:true,avatarUrl:true,steamAvatarUrl:true}}},take:20}),
  prisma.friend.findMany({where:{receiverId:u.id,status:"ACCEPTED"},include:{sender:{select:{id:true,nickname:true,avatarUrl:true,steamAvatarUrl:true}}},take:20}),
  prisma.rival.findMany({where:{ownerId:u.id,status:"ACTIVE"},include:{target:{select:{id:true,nickname:true,avatarUrl:true}}},take:20}),
  prisma.rival.findMany({where:{targetId:u.id,status:"ACTIVE"},include:{owner:{select:{id:true,nickname:true,avatarUrl:true}}},take:20}),
  prisma.collectionClaim.findMany({where:{userId:u.id},orderBy:{claimedAt:"desc"},take:30,select:{claimedAt:true,collection:{select:{id:true,name:true}}}}),
  getCurrentUser()
 ]);
 const isMe=me?.id===u.id;
 let relation:null|{status:string}=null; if(me&&me.id!==u.id){relation=await prisma.friend.findFirst({where:{OR:[{senderId:me.id,receiverId:u.id},{senderId:u.id,receiverId:me.id}]},select:{status:true}})}
 const myRival=me&&me.id!==u.id?await prisma.rival.findUnique({where:{ownerId_targetId:{ownerId:me.id,targetId:u.id}},select:{status:true}}):null;
 const visibleToViewer=u.profileVisibility==="PUBLIC" || isMe || (u.profileVisibility==="FRIENDS" && relation?.status==="ACCEPTED");
 if(!visibleToViewer && !isMe) return NextResponse.json({profile:{id:u.id,nickname:u.nickname,avatarUrl:u.avatarUrl,steamAvatarUrl:u.steamAvatarUrl,level:u.level,xp:u.xp,reputation:u.reputation,profileVisibility:u.profileVisibility,showStatsPublic:false,allowChallenges:u.allowChallenges,allowMessages:u.allowMessages,friends:[],rivals:[],clans:[],achievements:[],recentMatches:[],collections:[],relation:relation?.status??null,myRival:myRival?.status??null,isMe:false}});
 const matches=[...u.matchesAsPlayerOne,...u.matchesAsPlayerTwo].sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt)).slice(0,12);
 const total=u.showStatsPublic ? (stats?.totalDuels??(u.matchesAsPlayerOne.length+u.matchesAsPlayerTwo.length)) : 0; const wins=stats?.wins??0; const kills=stats?.kills??matchStats.reduce((n,x)=>n+x.kills,0); const deaths=stats?.deaths??matchStats.reduce((n,x)=>n+x.deaths,0); const hs=stats?.headshots??matchStats.reduce((n,x)=>n+x.headshots,0);
 const rating=u.showStatsPublic?(stats?.rating??1000):0; const league=leagueFromRating(rating); const finishedMatchStats=matchStats.filter(x=>Number(x.kills)>=0&&Number(x.deaths)>=0); const avgKills=finishedMatchStats.length?finishedMatchStats.reduce((n,x)=>n+x.kills,0)/finishedMatchStats.length:0; const avgDeaths=finishedMatchStats.length?finishedMatchStats.reduce((n,x)=>n+x.deaths,0)/finishedMatchStats.length:0; const avgDamage=finishedMatchStats.length?finishedMatchStats.reduce((n,x)=>n+x.damage,0)/finishedMatchStats.length:0; const avgScore=finishedMatchStats.length?finishedMatchStats.reduce((n,x)=>n+x.score,0)/finishedMatchStats.length:0; const recentForm=matches.filter(x=>x.status==="FINISHED").slice(0,5).map(x=>x.winnerId===u.id?"W":x.winnerId?"L":"D"); const profileCompletion=[u.avatarUrl||u.steamAvatarUrl,u.level>0,u.createdAt,clanMemberships.length>0,u.achievements.length>0].filter(Boolean).length/5*100;
 const leaderboard=await prisma.playerStats.findMany({orderBy:{rating:"desc"},select:{userId:true}}); const leaguePosition=Math.max(0,leaderboard.findIndex(x=>x.userId===u.id)+1);
 return NextResponse.json({profile:{id:u.id,nickname:u.nickname,avatarUrl:u.avatarUrl,steamAvatarUrl:u.steamAvatarUrl,level:u.level,xp:u.xp,reputation:u.reputation,profileVisibility:u.profileVisibility,showStatsPublic:u.showStatsPublic,allowChallenges:u.allowChallenges,allowMessages:u.allowMessages,wins,losses:stats?.losses??Math.max(0,total-wins),winRate:total?(wins/total*100):0,totalDuels:total,winStreak:stats?.winStreak??0,bestStreak:stats?.bestStreak??0,rating,league,leaguePosition,kills,deaths,kd:deaths?kills/deaths:kills,headshots:hs,hsRate:kills?hs/kills*100:0,damage:stats?.damage??matchStats.reduce((n,x)=>n+x.damage,0),avgKills,avgDeaths,avgDamage,avgScore,recentForm,profileCompletion,ratingHistory:stats?.ratingHistory??[],achievements:u.achievements.map(x=>x.achievement),recentMatches:matches,joinedAt:u.createdAt,collections:collections.map(x=>({id:x.collection.id,name:x.collection.name,claimedAt:x.claimedAt})),clans:clanMemberships.map(x=>({role:x.role,...x.clan})),friends:[...friendsSent.map(x=>x.receiver),...friendsReceived.map(x=>x.sender)],rivals:[...rivals.map(x=>x.target),...rivalOf.map(x=>x.owner)],weaponStats:matchStats.reduce((a: Record<string, number>,x)=>{const k=x.weapon||"Other";a[k]=(a[k]||0)+1;return a},{}),mapStats:matchStats.reduce((a: Record<string, number>,x)=>{const k=x.mapName||"Unknown";a[k]=(a[k]||0)+1;return a},{}),relation:relation?.status??null,myRival:myRival?.status??null,isMe:me?.id===u.id}})}
